"""
Expand topics_extra.json with ~3000+ new medical topics across new and existing categories.
Run: python3 expand_topics.py
"""
import json, os

NEW_TOPICS = {

"pain-management": [
    "Chronic Low Back Pain Multimodal Treatment Approach",
    "Neuropathic Pain Gabapentin Pregabalin Duloxetine Comparison",
    "Cancer Pain WHO Analgesic Ladder Opioid Rotation",
    "Fibromyalgia Diagnosis ACR Criteria and Treatment",
    "Complex Regional Pain Syndrome CRPS Type I Type II",
    "Phantom Limb Pain Mechanisms and Mirror Therapy",
    "Postherpetic Neuralgia Prevention Valacyclovir Capsaicin Patch",
    "Trigeminal Neuralgia Carbamazepine Microvascular Decompression",
    "Spinal Cord Stimulation for Chronic Pain Indications",
    "Intrathecal Drug Delivery Systems for Chronic Pain",
    "Ketamine Infusion for Refractory Chronic Pain",
    "Low Dose Naltrexone Fibromyalgia Chronic Pain",
    "Myofascial Pain Syndrome Trigger Point Injection",
    "Temporomandibular Joint Disorder TMJ Pain Management",
    "Headache Classification ICHD-3 Migraine Tension Cluster",
    "Migraine Prophylaxis Topiramate Amitriptyline CGRP Antagonists",
    "Acute Migraine Treatment Triptans Gepants Ditans",
    "CGRP Antagonists Erenumab Fremanezumab Migraine Prevention",
    "Chronic Daily Headache Medication Overuse Headache",
    "Cervicogenic Headache Diagnosis Nerve Block Treatment",
    "Occipital Neuralgia Diagnosis Occipital Nerve Block",
    "Painful Diabetic Neuropathy Duloxetine Pregabalin Treatment",
    "Central Sensitization Chronic Pain Pathophysiology",
    "Opioid Use Disorder in Chronic Pain Patients Buprenorphine",
    "Palliative Sedation Refractory Pain End of Life",
    "Radiofrequency Ablation Facet Joint Pain",
    "Epidural Steroid Injection Lumbar Radiculopathy",
    "Platelet Rich Plasma PRP Injection Musculoskeletal Pain",
    "Pain Catastrophizing Psychological Intervention CBT",
    "Multimodal Analgesia Perioperative Pain Management",
    "Topical Analgesics Lidocaine Patch Diclofenac Gel",
    "Transcutaneous Electrical Nerve Stimulation TENS Chronic Pain",
    "Acupuncture Evidence Base Chronic Pain Conditions",
    "Meditation Mindfulness Chronic Pain Reduction",
    "Opioid Tapering Strategies Chronic Non-Cancer Pain",
    "Buprenorphine for Chronic Pain Off-Label Use",
    "Visceral Pain Mechanisms Irritable Bowel Syndrome",
    "Pelvic Pain Endometriosis Interstitial Cystitis Treatment",
    "Sickle Cell Pain Crisis Hydroxyurea Voxelotor Management",
    "Pediatric Chronic Pain Biopsychosocial Model",
    "Elderly Pain Assessment Cognitively Impaired Patients",
    "Work-Related Musculoskeletal Disorders Prevention Treatment",
    "Chronic Pelvic Pain Syndrome in Men Treatment Options",
    "Breakthrough Cancer Pain Oral Transmucosal Fentanyl",
    "Duloxetine SNRIs Mechanism Chronic Musculoskeletal Pain",
    "Cannabidiol CBD Evidence Chronic Pain Neuropathic",
    "Nerve Block Techniques Peripheral Regional Anesthesia",
    "Pain Assessment Tools VAS NRS FACES Scale",
    "Biofeedback Therapy Chronic Pain Headache",
    "Interdisciplinary Pain Rehabilitation Program Outcomes",
],

"radiology": [
    "CT Pulmonary Angiography CTPA Pulmonary Embolism Diagnosis",
    "MRI Brain Stroke DWI ADC Map Interpretation",
    "Chest X-Ray Systematic Interpretation Approach",
    "Abdominal CT Scan Acute Abdomen Interpretation",
    "Fluoroscopy Guided Procedures Risks and Benefits",
    "Ultrasound Guided Procedures Vascular Access Biopsy",
    "PET CT Staging Oncology FDG Uptake",
    "Cardiac MRI Myocarditis Cardiomyopathy Diagnosis",
    "Breast Imaging BI-RADS Classification Mammography",
    "Prostate MRI PI-RADS Scoring Cancer Detection",
    "Liver MRI LI-RADS Classification Hepatocellular Carcinoma",
    "CT Colonography Virtual Colonoscopy Technique",
    "Radiation Dose Optimization CT Protocols",
    "MRI Safety Implants Pacemakers Claustrophobia",
    "Contrast Media Reactions Premedication Protocol",
    "Gadolinium Retention NSF Nephrogenic Systemic Fibrosis",
    "Interventional Radiology Embolization Procedures",
    "TIPS Transjugular Intrahepatic Portosystemic Shunt",
    "Uterine Fibroid Embolization Technique Outcomes",
    "Percutaneous Tumor Ablation Radiofrequency Microwave",
    "Inferior Vena Cava Filter Placement Retrieval",
    "Carotid Artery Stenting Angioplasty Technique",
    "Renal Artery Stenosis Diagnosis Treatment Stenting",
    "Vertebroplasty Kyphoplasty Vertebral Compression Fracture",
    "Biliary Drainage ERCP Percutaneous Transhepatic",
    "Nephrostomy Tube Placement Ureteral Stenting",
    "Lung Biopsy CT Guided Pneumothorax Risk",
    "Brain Aneurysm Coiling Endovascular Treatment",
    "Acute Stroke Mechanical Thrombectomy Technique",
    "MRI Knee Meniscal Tears ACL Injury Grading",
    "Bone Density DEXA Scan T-Score Z-Score Interpretation",
    "Thyroid Ultrasound TI-RADS Nodule Evaluation",
    "Echocardiography Transthoracic vs Transesophageal",
    "Point of Care Ultrasound POCUS Emergency Applications",
    "FAST Exam Trauma Ultrasound Technique",
    "Carotid Intima Media Thickness Atherosclerosis Risk",
    "Doppler Ultrasound Deep Vein Thrombosis Diagnosis",
    "Renal Ultrasound Hydronephrosis Kidney Stone",
    "Fetal Ultrasound Second Trimester Anomaly Scan",
    "Nuclear Medicine Bone Scan Metastases Detection",
    "SPECT Myocardial Perfusion Imaging Stress Test",
    "Ventilation Perfusion VQ Scan Pulmonary Embolism",
    "Positron Emission Tomography Brain Neurology",
    "Gallium Scan Infection Inflammation Detection",
    "Radiograph Interpretation Fracture Types Classification",
    "Spine MRI Disc Herniation Stenosis Grading",
    "Shoulder MRI Rotator Cuff Tears Classification",
    "Hip MRI Labral Tears Femoroacetabular Impingement",
    "Ankle MRI Ligament Injuries Tendon Pathology",
    "Wrist MRI TFCC Tear Scaphoid Fracture",
],

"pathology": [
    "Histopathology Staining Techniques H&E Special Stains",
    "Immunohistochemistry Tumor Marker Interpretation",
    "Fine Needle Aspiration Cytology Thyroid Nodule",
    "Liquid Biopsy Circulating Tumor DNA ctDNA",
    "Molecular Pathology Next Generation Sequencing Tumors",
    "Frozen Section Intraoperative Diagnosis Technique",
    "Autopsy Findings Common Causes Sudden Death",
    "Celiac Disease Marsh Classification Duodenal Biopsy",
    "Barrett Esophagus Dysplasia Grading Biopsy Protocol",
    "Inflammatory Bowel Disease Pathology Crohn vs Colitis",
    "Colorectal Cancer Staging Pathology TNM System",
    "Lung Cancer Pathology Adenocarcinoma Squamous Cell",
    "Breast Cancer Pathology Hormone Receptor HER2 Status",
    "Lymphoma Classification WHO 2022 Hodgkin Non-Hodgkin",
    "Leukemia Pathology Bone Marrow Biopsy Interpretation",
    "Renal Biopsy Pathology Glomerulonephritis Classification",
    "Liver Biopsy Fibrosis Grading METAVIR Score",
    "Skin Biopsy Melanoma Breslow Thickness Clark Level",
    "Prostate Cancer Gleason Grading ISUP Grade Group",
    "Cervical Cancer HPV Pathology CIN Grading",
    "Thyroid Cancer Pathology Papillary Follicular Anaplastic",
    "Pancreatic Cancer Ductal Adenocarcinoma Pathology",
    "Bone Marrow Biopsy Interpretation Hematological Disorders",
    "Transplant Rejection Pathology Acute Chronic Classification",
    "Autoimmune Hepatitis Interface Hepatitis Rose Score",
    "Primary Biliary Cholangitis Bile Duct Granulomas",
    "IgA Nephropathy Oxford Classification MEST-C",
    "Membranous Nephropathy PLA2R Antibody Pathology",
    "Vasculitis Pathology Classification by Vessel Size",
    "Sarcoidosis Noncaseating Granuloma Pathology",
    "Tuberculosis Caseating Granuloma Ziehl-Neelsen Stain",
    "Amyloidosis Congo Red Stain Apple Green Birefringence",
    "Paget Disease Bone Pathology Mosaic Pattern",
    "Gout Pathology Monosodium Urate Crystal Deposition",
    "NASH NAFLD Pathology Ballooning NAS Score",
    "Pulmonary Fibrosis UIP Pattern Pathology",
    "Mesothelioma Pathology Calretinin WT1 Markers",
    "Gastrointestinal Stromal Tumor GIST KIT Pathology",
    "Neuroendocrine Tumor Grading Ki-67 Index",
    "Pediatric Tumors Wilms Neuroblastoma Pathology",
    "CNS Tumor WHO 2021 Classification IDH Mutation",
    "Ovarian Cancer Pathology Serous Endometrioid Types",
    "Testicular Cancer Pathology Seminoma Non-Seminoma",
    "Soft Tissue Sarcoma Classification Pathology",
    "Flow Cytometry Immunophenotyping Hematology",
    "FISH Fluorescence In Situ Hybridization Cancer Diagnosis",
    "PCR Molecular Testing Infectious Disease Pathology",
    "Electron Microscopy Nephropathology Applications",
    "Autopsy Pediatric Sudden Infant Death Syndrome",
    "Forensic Pathology Cause vs Manner of Death",
],

"toxicology": [
    "Acetaminophen Overdose N-Acetylcysteine Treatment Protocol",
    "Salicylate Poisoning Acid-Base Disturbance Treatment",
    "Tricyclic Antidepressant Overdose Sodium Bicarbonate",
    "Benzodiazepine Overdose Flumazenil Risks",
    "Opioid Overdose Naloxone Dosing Routes",
    "Methanol Ethylene Glycol Poisoning Fomepizole Treatment",
    "Carbon Monoxide Poisoning Hyperbaric Oxygen Therapy",
    "Cyanide Poisoning Hydroxocobalamin Antidote",
    "Organophosphate Poisoning Atropine Pralidoxime",
    "Digoxin Toxicity Digoxin Specific Antibody Fragments",
    "Beta Blocker Calcium Channel Blocker Overdose",
    "High Dose Insulin Euglycemic Therapy Calcium Channel Blocker",
    "Lipid Emulsion Therapy Local Anesthetic Systemic Toxicity",
    "Iron Poisoning Deferoxamine Chelation Treatment",
    "Lead Poisoning Chelation DMSA EDTA Treatment",
    "Mercury Poisoning Dimercaprol DMSA Treatment",
    "Arsenic Poisoning Mees Lines Treatment",
    "Warfarin Overdose Vitamin K Four Factor PCC",
    "DOAC Reversal Andexanet Idarucizumab",
    "Serotonin Syndrome Diagnosis Hunter Criteria Cyproheptadine",
    "Neuroleptic Malignant Syndrome Dantrolene Bromocriptine",
    "Lithium Toxicity Dialysis Indications",
    "Antipsychotic Overdose QTc Prolongation Management",
    "SSRI Overdose vs Serotonin Syndrome Distinction",
    "Cocaine Toxicity Cardiovascular Effects Treatment",
    "Methamphetamine Toxicity Hyperthermia Management",
    "MDMA Ecstasy Hyponatremia Serotonin Toxicity",
    "Synthetic Cannabinoids K2 Spice Toxicity",
    "Fentanyl Analogs High Potency Opioid Toxicity",
    "Xylazine Adulterated Fentanyl Wound Care Naloxone",
    "Snake Bite Envenomation Antivenom Protocol",
    "Spider Bite Black Widow Brown Recluse Treatment",
    "Mushroom Poisoning Amatoxin Liver Transplant",
    "Plant Toxin Poisoning Jimsonweed Oleander",
    "Food Poisoning Botulism Antitoxin Treatment",
    "Pesticide Poisoning Rodenticide Superwarfarin",
    "Drug-Induced Liver Injury DILI RUCAM Score",
    "Drug-Induced QT Prolongation Torsades de Pointes",
    "Drug-Induced Nephrotoxicity NSAIDs Aminoglycosides",
    "Drug-Induced Agranulocytosis Clozapine Carbimazole",
    "Alcohol Withdrawal Seizures CIWA Protocol Lorazepam",
    "Alcohol Intoxication Ethanol Metabolic Effects",
    "GHB Gamma Hydroxybutyrate Withdrawal Management",
    "Kratom Toxicity Mitragyna Speciosa Opioid Effects",
    "Poison Control Center Role Toxidrome Recognition",
    "Activated Charcoal Indications Contraindications",
    "Whole Bowel Irrigation Body Packer Smuggler",
    "Toxicology Screen Urine Drug Immunoassay Limitations",
    "Workplace Chemical Exposure OSHA Standards",
    "Pediatric Poisoning Household Products Prevention",
],

"palliative-care": [
    "Palliative Care vs Hospice Care Definitions Eligibility",
    "Goals of Care Conversation Techniques REMAP Framework",
    "Prognosis Communication Serious Illness Guide",
    "Advance Directive Living Will POLST DNR Orders",
    "Surrogate Decision Making Healthcare Proxy",
    "Dyspnea Management in Terminal Illness Opioids",
    "Refractory Dyspnea Palliative Sedation Indications",
    "Cancer Pain at End of Life Opioid Rotation",
    "Nausea Vomiting Palliative Antiemetic Choices",
    "Delirium at End of Life Haloperidol Management",
    "Constipation in Palliative Care Methylnaltrexone",
    "Cachexia Cancer Anorexia Megestrol Corticosteroids",
    "Hydration and Nutrition at End of Life Ethics",
    "Spiritual Care Chaplaincy in Palliative Care",
    "Psychosocial Support Family Caregiver Burnout",
    "Grief Complicated Grief Prolonged Grief Disorder",
    "Pediatric Palliative Care Communication with Families",
    "Neonatal Palliative Care Comfort Focused Care",
    "Palliative Care in ICU Family Meeting Approach",
    "Withdrawal of Life Sustaining Treatment Protocol",
    "Comfort Measures Only Orders Implementation",
    "Palliative Chemotherapy Goals Response Assessment",
    "Palliative Radiotherapy Bone Metastases Pain Relief",
    "Palliative Surgery Malignant Bowel Obstruction",
    "Heart Failure Palliative Care Deactivating ICD",
    "COPD End Stage Palliative Oxygen Opioids",
    "Dementia Advanced Stages Feeding Tube Decision",
    "ALS Palliative Care Respiratory Decision Making",
    "Renal Failure Conservative Management without Dialysis",
    "Liver Failure Hepatic Encephalopathy Symptom Control",
    "Existential Suffering Meaning Centered Psychotherapy",
    "Dignity Therapy Narrative Approach End of Life",
    "Prognostic Indicators Cancer 6 Month Prognosis",
    "Performance Status ECOG Karnofsky Scale Prognosis",
    "Palliative Care Quality Indicators NHPCO Standards",
    "Opioid Conversion Equianalgesic Dosing Table",
    "Subcutaneous Opioid Infusion Syringe Driver",
    "Death Rattle Terminal Secretions Glycopyrrolate",
    "Active Dying Signs Recognition Family Education",
    "Bereavement Support After Patient Death Programs",
],

"rehabilitation": [
    "Stroke Rehabilitation Motor Recovery Neuroplasticity",
    "Constraint Induced Movement Therapy CIMT Stroke",
    "Aphasia Rehabilitation Speech Language Therapy",
    "Dysphagia Post Stroke Assessment Swallowing Therapy",
    "Traumatic Brain Injury Rehabilitation Cognitive",
    "Spinal Cord Injury Rehabilitation FIM Score",
    "Wheelchair Prescription Spinal Cord Injury",
    "Orthotic Devices AFO Drop Foot Rehabilitation",
    "Amputee Rehabilitation Prosthetic Fitting Gait",
    "Cardiac Rehabilitation Phase I II III Programs",
    "Pulmonary Rehabilitation COPD Exercise Training",
    "Total Knee Replacement Rehabilitation Protocol",
    "Total Hip Replacement Rehabilitation Precautions",
    "Low Back Pain Rehabilitation McKenzie Method",
    "Rotator Cuff Repair Rehabilitation Progressive Exercise",
    "ACL Reconstruction Rehabilitation Return to Sport",
    "Aquatic Therapy Hydrotherapy Conditions and Benefits",
    "Occupational Therapy Activities Daily Living Stroke",
    "Cognitive Rehabilitation TBI Memory Attention",
    "Vestibular Rehabilitation Canalith Repositioning",
    "Balance Training Fall Prevention Elderly",
    "Gait Analysis Clinical Kinematic Assessment",
    "Functional Electrical Stimulation FES Rehabilitation",
    "Robot Assisted Rehabilitation Exoskeleton Gait",
    "Virtual Reality Rehabilitation Stroke Upper Limb",
    "Mirror Therapy Phantom Limb Stroke Rehabilitation",
    "Lymphedema Management Complete Decongestive Therapy",
    "Scar Management Silicone Sheet Pressure Garment",
    "Burns Rehabilitation Contracture Prevention Splinting",
    "Chronic Fatigue Syndrome Graded Exercise Therapy",
    "Fibromyalgia Aerobic Exercise Tai Chi Evidence",
    "Multiple Sclerosis Rehabilitation Fatigue Management",
    "Parkinson Disease Rehabilitation LSVT BIG Program",
    "Cerebral Palsy Rehabilitation Botulinum Toxin",
    "Pediatric Rehabilitation Developmental Milestones",
    "Cancer Rehabilitation Exercise Oncology Guidelines",
    "Post COVID Rehabilitation Long COVID Symptoms",
    "Vocational Rehabilitation Return to Work Programs",
    "Driving Assessment Post Neurological Injury",
    "Home Modification Assessment Occupational Therapy",
    "Pain Rehabilitation Interdisciplinary Program",
    "Speech Rehabilitation Alaryngeal Speech",
    "Manual Therapy Spinal Manipulation Evidence",
    "Dry Needling vs Acupuncture Physical Therapy",
    "Kinesio Taping Evidence Base Clinical Applications",
    "Transcranial Magnetic Stimulation TMS Rehabilitation",
    "Neuromuscular Electrical Stimulation NMES Muscle",
    "Ultrasound Therapeutic Musculoskeletal Conditions",
    "Iontophoresis Phonophoresis Drug Delivery",
    "Ergonomics Workplace Assessment Injury Prevention",
],

"public-health": [
    "Epidemiology Study Designs Cohort Case Control RCT",
    "Vaccine Preventable Diseases Herd Immunity Threshold",
    "Vaccination Schedule Adult Immunization Guidelines",
    "Influenza Vaccination Effectiveness Coverage Strategies",
    "COVID-19 Public Health Interventions Effectiveness",
    "Contact Tracing Digital Tools Infectious Disease",
    "Quarantine Isolation Principles Infectious Disease Control",
    "Tuberculosis Control Directly Observed Therapy DOTS",
    "HIV Prevention Pre-Exposure Prophylaxis PrEP Programs",
    "STI Screening Programs Population Level Interventions",
    "Malaria Control Vector Control Insecticide Nets",
    "Clean Water Access Waterborne Disease Prevention",
    "Sanitation Hygiene WASH Programs Global Health",
    "Food Safety Regulations Foodborne Illness Prevention",
    "Obesity Prevention Population Level Interventions",
    "Sugar Sweetened Beverage Tax Health Outcomes",
    "Tobacco Control Smoking Cessation Policy",
    "Alcohol Policy Minimum Unit Pricing Evidence",
    "Drug Decriminalization Public Health Approach",
    "Air Pollution Health Effects PM2.5 Standards",
    "Climate Change Health Impacts Adaptation",
    "Heat Wave Emergency Response Urban Heat Island",
    "Occupational Health Surveillance Hazard Assessment",
    "Maternal Mortality Reduction Global Strategies",
    "Child Nutrition Programs UNICEF WHO Guidelines",
    "School Health Programs Adolescent Health",
    "Mental Health Public Health Stigma Reduction",
    "Suicide Prevention Programs Evidence Based",
    "Violence Prevention Intimate Partner Violence",
    "Injury Prevention Road Safety Helmet Laws",
    "Cancer Screening Programs Population Level",
    "Colorectal Cancer Screening Colonoscopy vs FIT",
    "Cervical Cancer Screening HPV Test Pap Smear",
    "Breast Cancer Screening Mammography Guidelines",
    "Cardiovascular Disease Prevention Population",
    "Diabetes Prevention Program Lifestyle Intervention",
    "Hypertension Control Community Programs",
    "Health Disparities Social Determinants of Health",
    "Universal Health Coverage Definition Measurement",
    "Health System Strengthening Low Income Countries",
    "Global Disease Burden DALY QALY Measurement",
    "Neglected Tropical Diseases Mass Drug Administration",
    "Antibiotic Stewardship Programs Hospital Community",
    "Outbreak Investigation Steps Epidemiology",
    "Syndromic Surveillance Early Warning Systems",
    "One Health Approach Zoonotic Disease Prevention",
    "Reproductive Health Family Planning Access",
    "Adolescent Health Sexual Health Education",
    "Disability Public Health ICF Classification",
    "Aging Population Chronic Disease Management Programs",
],

"preventive-medicine": [
    "Preventive Services USPSTF Recommendations Overview",
    "Cardiovascular Risk Stratification Framingham ASCVD",
    "Statin Therapy Primary Prevention Guidelines",
    "Aspirin Primary Prevention Current Recommendations",
    "Hypertension Screening Management Primary Care",
    "Diabetes Screening HbA1c Fasting Glucose Criteria",
    "Prediabetes Intervention Metformin Lifestyle",
    "Obesity Screening BMI Waist Circumference",
    "Dyslipidemia Screening Non-Fasting Lipid Panel",
    "Thyroid Dysfunction Screening Recommendations",
    "Osteoporosis Screening FRAX Score DEXA Scan",
    "Colorectal Cancer Screening Age 45 Guidelines",
    "Lung Cancer Low Dose CT Screening Eligibility",
    "Abdominal Aortic Aneurysm Screening Men Smokers",
    "Prostate Cancer PSA Screening Shared Decision",
    "Skin Cancer Prevention Sun Protection Measures",
    "Depression Screening PHQ-2 PHQ-9 Primary Care",
    "Anxiety Screening GAD-7 Primary Care",
    "Alcohol Use Disorder Screening AUDIT CAGE",
    "Domestic Violence Screening HITS Tool Primary Care",
    "Cognitive Decline Screening Elderly MoCA MMSE",
    "Falls Risk Assessment STEADI Elderly",
    "Vision Screening Adults Glaucoma Macular Degeneration",
    "Hearing Screening Adults Presbycusis",
    "Dental Health Fluoride Periodontal Disease Prevention",
    "Sexually Transmitted Infection Screening Recommendations",
    "HIV Screening Universal Opt-Out Testing",
    "Hepatitis C Screening Baby Boomer Generation",
    "Hepatitis B Screening Vaccination Recommendations",
    "Travel Medicine Pre-Travel Consultation Vaccines",
    "Workplace Wellness Programs Effectiveness Evidence",
    "Smoking Cessation Brief Intervention 5 A's",
    "Physical Activity Prescription 150 Minutes Weekly",
    "Mediterranean Diet DASH Diet Cardiovascular Prevention",
    "Dietary Supplements Efficacy Safety Evidence",
    "Vitamin D Supplementation Evidence Benefits Harms",
    "Folic Acid Supplementation Neural Tube Defect Prevention",
    "Childhood Obesity Prevention Family Based Intervention",
    "Adolescent Vaccination HPV Meningococcal Tdap",
    "Healthy Aging Longevity Lifestyle Factors",
    "Chemoprevention Cancer Tamoxifen Finasteride",
    "Preconception Care Optimization Maternal Health",
    "Prenatal Care Schedule Screening Tests",
    "Newborn Screening Metabolic Disorders PKU",
    "Immunocompromised Vaccination Live vs Killed",
    "Genetic Counseling BRCA Lynch Syndrome Screening",
    "Environmental Health Home Assessment Lead Radon",
    "Safe Sleep Infant SIDS Prevention Guidelines",
    "Child Safety Car Seat Helmet Drowning Prevention",
    "Sun Screen Evidence Skin Cancer Prevention",
],

"sleep-medicine": [
    "Obstructive Sleep Apnea Diagnosis Polysomnography AHI",
    "CPAP Therapy Adherence Troubleshooting OSA",
    "BPAP Auto-CPAP Alternative Sleep Apnea Therapy",
    "Mandibular Advancement Device Sleep Apnea",
    "Upper Airway Stimulation Inspire Device OSA",
    "Central Sleep Apnea Adaptive Servo Ventilation",
    "Obesity Hypoventilation Syndrome NIV Treatment",
    "Insomnia Disorder CBT-I Cognitive Behavioral Therapy",
    "Sleep Hygiene Education Evidence Based",
    "Chronic Insomnia Pharmacotherapy Zolpidem Eszopiclone",
    "Orexin Receptor Antagonist Suvorexant Lemborexant",
    "Melatonin Circadian Rhythm Disorders Dosing",
    "Restless Legs Syndrome Diagnosis Dopaminergics Iron",
    "Periodic Limb Movement Disorder Diagnosis Treatment",
    "Narcolepsy Type 1 Cataplexy Hypocretin Deficiency",
    "Narcolepsy Type 2 Treatment Modafinil Sodium Oxybate",
    "Idiopathic Hypersomnia Clarithromycin Flumazenil",
    "Kleine Levin Syndrome Episodic Hypersomnia",
    "Circadian Rhythm Sleep Wake Disorders DSPS ASPS",
    "Shift Work Sleep Disorder Melatonin Modafinil",
    "REM Sleep Behavior Disorder Parkinson Biomarker",
    "Non-REM Parasomnias Sleepwalking Night Terrors",
    "Sleep Related Eating Disorder Zolpidem Association",
    "Bruxism Sleep Dental Occlusal Guard",
    "Pediatric Obstructive Sleep Apnea Adenotonsillectomy",
    "Pediatric Behavioral Insomnia Sleep Training",
    "Sleep and Cardiovascular Disease Associations",
    "Sleep Deprivation Immune Function Metabolic Effects",
    "Sleep and Obesity Bidirectional Relationship",
    "Sleep and Diabetes HbA1c Glycemic Control",
    "Sleep and Mental Health Depression Anxiety",
    "Sleep Architecture Stages REM NREM Physiology",
    "Actigraphy Sleep Wake Monitoring Clinical Use",
    "Home Sleep Apnea Testing vs Polysomnography",
    "Titration Protocol CPAP Pressure Setting",
    "Hypnotic Discontinuation Tapering Strategy",
    "Sleep Apnea Perioperative Risk Management",
    "Pregnancy Sleep Disorders Restless Legs Apnea",
    "Menopause Sleep Disturbance Hormone Therapy",
    "Alzheimer Sleep Disruption Melatonin Trazodone",
],

"addiction-medicine": [
    "Alcohol Use Disorder Diagnostic Criteria DSM-5",
    "Alcohol Dependence Pharmacotherapy Naltrexone Acamprosate",
    "Alcohol Withdrawal Syndrome CIWA-Ar Scale Lorazepam",
    "Severe Alcohol Withdrawal Delirium Tremens ICU",
    "Disulfiram Mechanism Compliance Monitoring",
    "Opioid Use Disorder Buprenorphine Induction Protocol",
    "Methadone Maintenance Treatment OUD",
    "Extended Release Naltrexone Vivitrol Opioid Use",
    "Naloxone Take Home Program Overdose Prevention",
    "Harm Reduction Needle Exchange Safe Injection",
    "Nicotine Dependence Pharmacotherapy Varenicline NRT",
    "Brief Motivational Intervention Alcohol Drugs",
    "Motivational Interviewing Addiction Technique",
    "12 Step Facilitation AA NA Evidence",
    "Cognitive Behavioral Therapy Substance Use Disorder",
    "Contingency Management Voucher Reinforcement",
    "Co-occurring Disorders Dual Diagnosis Treatment",
    "Cannabis Use Disorder Increasing Potency THC",
    "Synthetic Opioid Overdose Fentanyl High Dose Naloxone",
    "Stimulant Use Disorder Cocaine Meth No FDA Treatment",
    "Benzodiazepine Dependence Taper Schedule",
    "Prescription Drug Monitoring PDMP Use",
    "Screening for Substance Use AUDIT DAST CAGE",
    "Adolescent Substance Use Prevention SBIRT",
    "Addiction in Pregnancy Neonatal Abstinence Syndrome",
    "Neonatal Opioid Withdrawal Eat Sleep Console",
    "Alcohol Related Liver Disease Abstinence Recovery",
    "Addiction Neurobiology Reward Dopamine Pathway",
    "Social Determinants Addiction Poverty Trauma",
    "Trauma Informed Care Addiction Treatment",
    "Recovery Capital Community Support Programs",
    "Addiction Medicine Specialist Training Certification",
    "Gambling Disorder Behavioral Addiction Treatment",
    "Internet Gaming Disorder Recognition Treatment",
    "Food Addiction Ultra Processed Foods Evidence",
    "Kratom Addiction Novel Opioid Dependence",
    "Club Drug Addiction MDMA GHB Ketamine",
    "Inhalant Abuse Adolescents Brain Damage",
    "Anabolic Steroid Abuse Endocrine Effects",
    "Performance Enhancing Drug WADA Prohibited List",
],

"occupational-medicine": [
    "Occupational Asthma Diagnosis Causative Agents",
    "Silicosis Prevention Monitoring Quartz Exposure",
    "Asbestosis Mesothelioma Asbestos Exposure History",
    "Occupational COPD Coal Dust Mining Workers",
    "Hypersensitivity Pneumonitis Farmer Lung Bird Breeder",
    "Lead Poisoning Occupational Blood Lead Monitoring",
    "Noise Induced Hearing Loss Prevention Audiometry",
    "Occupational Skin Disease Contact Dermatitis",
    "Work Related Musculoskeletal Disorders Carpal Tunnel",
    "Ergonomic Assessment Lifting Repetitive Motion",
    "Radiation Safety Dosimetry Occupational Exposure",
    "Latex Allergy Healthcare Workers Prevention",
    "Bloodborne Pathogen Exposure Needlestick Protocol",
    "Healthcare Worker Burnout Moral Injury",
    "Shift Work Health Effects Metabolic Cardiovascular",
    "Heat Stress Illness Prevention Hydration OSHA",
    "Cold Stress Frostbite Hypothermia Workers",
    "Confined Space Entry Safety Permit Required",
    "Chemical Exposure Monitoring OSHA PEL TLV",
    "Respiratory Protection N95 PAPR Selection",
    "Fitness for Duty Evaluation Return to Work",
    "Disability Evaluation ADA Reasonable Accommodation",
    "Workers Compensation Medical Evaluation",
    "Impairment Rating AMA Guides Method",
    "Pre-employment Medical Examination Guidelines",
    "Surveillance Programs Occupational Disease Detection",
    "Vibration Syndrome Hand Arm Vibration White Finger",
    "Organic Solvent Neurotoxicity Painters",
    "Pesticide Organophosphate Agricultural Worker",
    "Formaldehyde Exposure Cancer Risk Healthcare",
    "Benzene Exposure Leukemia Risk Monitoring",
    "Heavy Metal Screening Occupational Chelation",
    "Stress Burnout Resilience Healthcare Physicians",
    "Physician Impairment Substance Abuse Reporting",
    "Second Victim Syndrome Medical Error Aftermath",
    "Workplace Wellness Programs ROI Evidence",
    "Telecommuting Ergonomics Remote Work Health",
    "Mining Health Safety Regulations Underground",
    "Construction Site Hazards Falls PPE Requirements",
    "Agricultural Health Farm Worker Hazards",
],

"immunology": [
    "Innate Immune System Pattern Recognition Receptors",
    "Adaptive Immunity T Cell B Cell Development",
    "Antibody Structure IgG IgM IgA IgE IgD Functions",
    "Complement System Classical Alternative Lectin Pathway",
    "Cytokine Network IL-1 IL-6 TNF Interferons",
    "Toll-Like Receptor Signaling Innate Immunity",
    "Major Histocompatibility Complex MHC Class I II",
    "T Cell Receptor Antigen Presentation CD4 CD8",
    "Regulatory T Cells Treg Immune Tolerance",
    "Th1 Th2 Th17 CD4 T Cell Differentiation",
    "B Cell Activation Germinal Center Affinity Maturation",
    "Natural Killer Cell Function Cancer Immunosurveillance",
    "Dendritic Cell Antigen Presentation Maturation",
    "Macrophage Polarization M1 M2 Inflammatory",
    "Autoimmunity Mechanisms Molecular Mimicry",
    "Primary Immunodeficiency CVID XLA SCID",
    "Secondary Immunodeficiency HIV Malnutrition",
    "Immunoglobulin Replacement Therapy IVIG SCIG",
    "Transplant Immunology HLA Matching Rejection",
    "Graft Versus Host Disease Acute Chronic Prevention",
    "Immunosuppression Protocols Transplant Calcineurin",
    "Biologics Mechanism TNF Inhibitors IL-17 JAK",
    "Checkpoint Inhibitor Immunotherapy Immune Adverse Events",
    "CAR-T Cell Therapy Mechanism Cytokine Release",
    "Allergic Sensitization IgE Mast Cell Basophil",
    "Anaphylaxis Immunopathology Epinephrine Mechanism",
    "Food Allergy Immunopathology Oral Immunotherapy",
    "Eosinophilic Disorders Hypereosinophilia Syndrome",
    "Mast Cell Activation Syndrome Diagnosis Treatment",
    "Hereditary Angioedema C1 Inhibitor Deficiency",
    "Common Variable Immunodeficiency Diagnosis Management",
    "Selective IgA Deficiency Complications",
    "Wiskott-Aldrich Syndrome Gene Therapy",
    "Chronic Granulomatous Disease NADPH Oxidase",
    "Complement Deficiency Meningococcal Susceptibility",
    "Immune Senescence Aging Vaccine Response",
    "Mucosal Immunity IgA Gut Barrier Function",
    "Microbiome Immune System Development",
    "Tumor Immunology PD-L1 Expression Biomarker",
    "Inflammasome NLRP3 Autoinflammatory Diseases",
],

"microbiology": [
    "Antimicrobial Resistance Mechanisms Beta-Lactamase",
    "MRSA Community Hospital Acquired Decolonization",
    "Extended Spectrum Beta-Lactamase ESBL Carbapenems",
    "Carbapenem Resistant Enterobacteriaceae CRE Treatment",
    "Vancomycin Resistant Enterococcus VRE Control",
    "Clostridium Difficile Spore Formation Transmission",
    "Clostridioides Difficile Treatment Fidaxomicin FMT",
    "Blood Culture Technique Contamination Interpretation",
    "Antibiotic Sensitivity Testing MIC Breakpoints",
    "Disk Diffusion Broth Microdilution Methods",
    "PCR Based Pathogen Detection Multiplex Panels",
    "Metagenomic Sequencing Infectious Disease Diagnosis",
    "Biofilm Formation Pathogenesis Catheter Infection",
    "Quorum Sensing Bacterial Communication",
    "Bacterial Toxin Mechanisms Exotoxin Endotoxin",
    "Gram Positive Cocci Staphylococcus Streptococcus",
    "Gram Negative Rods Enterobacteriaceae Pseudomonas",
    "Anaerobic Bacteria Bacteroides Clostridium Culture",
    "Mycobacterium Tuberculosis Diagnosis Culture DST",
    "Non-Tuberculous Mycobacteria MAC MAB Treatment",
    "Fungal Culture Identification Candida Aspergillus",
    "Antifungal Susceptibility Testing EUCAST CLSI",
    "Viral Culture vs PCR Respiratory Viruses",
    "Hepatitis B Viral Markers HBsAg HBeAg Interpretation",
    "HIV RNA Viral Load CD4 Count Monitoring",
    "Respiratory Syncytial Virus RSV Diagnosis Prevention",
    "Influenza Rapid Antigen vs PCR Sensitivity",
    "SARS-CoV-2 Variants Immune Escape Surveillance",
    "Prion Diseases Creutzfeldt-Jakob Diagnosis",
    "Rickettsia Spotted Fever Group Diagnosis Doxycycline",
    "Lyme Disease Borrelia Burgdorferi Two-Tier Testing",
    "Legionella Urinary Antigen Test Diagnosis",
    "Pneumococcal Urinary Antigen Test Sensitivity",
    "Cryptococcal Antigen Serum CSF Test",
    "Beta-D-Glucan Aspergillus Galactomannan Test",
    "Stool Culture Diarrheal Illness Campylobacter",
    "Helicobacter Pylori Urea Breath Test Stool Antigen",
    "Malaria Rapid Diagnostic Test Thick Smear",
    "Strongyloides Serology Hyperinfection Risk",
    "Infection Prevention Control Hospital Epidemiology",
],

"lab-medicine": [
    "Complete Blood Count Interpretation Reference Ranges",
    "White Blood Cell Differential Abnormalities",
    "Anemia Workup Algorithm Iron Studies Reticulocyte",
    "Coagulation Testing PT INR aPTT Interpretation",
    "D-Dimer Test Clinical Application Sensitivity",
    "Liver Function Tests ALT AST ALP GGT Patterns",
    "Kidney Function eGFR Creatinine Cystatin C",
    "Electrolyte Interpretation Sodium Potassium",
    "Arterial Blood Gas Interpretation Acid Base",
    "Thyroid Function Tests TSH T4 T3 Patterns",
    "HbA1c Measurement Interference Hemoglobin Variants",
    "Troponin High Sensitivity Assay Interpretation",
    "BNP NT-proBNP Heart Failure Diagnosis",
    "Procalcitonin Bacterial Infection Sepsis Marker",
    "C-Reactive Protein ESR Inflammatory Markers",
    "Ferritin Interpretation Iron Deficiency Inflammation",
    "Vitamin B12 Folate Testing Deficiency Diagnosis",
    "Vitamin D 25-OH Testing Interpretation Sufficiency",
    "Serum Protein Electrophoresis SPEP Monoclonal",
    "Immunofixation Electrophoresis Myeloma Diagnosis",
    "Flow Cytometry Clinical Applications Leukemia",
    "Bone Marrow Aspirate Biopsy Interpretation",
    "Cerebrospinal Fluid Analysis Meningitis Criteria",
    "Synovial Fluid Analysis Crystal Identification",
    "Pleural Fluid Analysis Light Criteria Exudate",
    "Urine Dipstick Microscopy Interpretation UTI",
    "Urine Protein Creatinine Ratio Spot Sample",
    "Spot Albumin Creatinine Ratio Diabetic Nephropathy",
    "Tumor Markers CEA CA 19-9 PSA CA-125 Utility",
    "Autoantibody Testing ANA Anti-dsDNA Anti-Smith",
    "ANCA Testing MPO PR3 Vasculitis Diagnosis",
    "Antiphospholipid Antibody Testing Lupus Anticoagulant",
    "Complement C3 C4 CH50 Lupus Nephritis",
    "Cryoglobulin Testing Type I II III",
    "HLA Typing Transplant Disease Association",
    "Genetic Testing Germline Somatic Variants",
    "Pharmacogenomics CYP2D6 CYP2C19 Drug Metabolism",
    "Point of Care Testing POCT Quality Assurance",
    "Laboratory Errors Preanalytical Analytical Issues",
    "Reference Interval Population Based Age Sex",
],

"clinical-nutrition": [
    "Malnutrition Screening NRS-2002 MNA MUST Tools",
    "Nutritional Assessment SOAP ABCD Method",
    "Enteral Nutrition Nasogastric vs Gastrostomy",
    "Parenteral Nutrition Total TPN Indications",
    "Refeeding Syndrome Prevention Phosphate Monitoring",
    "Short Bowel Syndrome Intestinal Adaptation Nutrition",
    "Inflammatory Bowel Disease Exclusive Enteral Nutrition",
    "Critical Illness Nutrition ESPEN ASPEN Guidelines",
    "Protein Requirements Critical Illness 1.2-2g kg",
    "Indirect Calorimetry Metabolic Rate Measurement",
    "Obesity Surgery Nutrition Bariatric Vitamin",
    "Celiac Disease Gluten Free Diet Compliance",
    "Phenylketonuria PKU Phenylalanine Restricted Diet",
    "Chronic Kidney Disease Nutrition Protein Restriction",
    "Liver Disease Nutrition Branch Chain Amino Acids",
    "Diabetes Medical Nutrition Therapy Carbohydrate",
    "Cardiovascular Disease Diet Mediterranean DASH",
    "Bone Health Calcium Vitamin D Intake",
    "Iron Deficiency Dietary Sources Absorption Enhancement",
    "Iodine Deficiency Goiter Prevention Salt Iodization",
    "Zinc Deficiency Wound Healing Immune Function",
    "Selenium Deficiency Keshan Disease Thyroid",
    "Folate Deficiency Neural Tube Defects Pregnancy",
    "Vitamin B12 Deficiency Vegan Vegetarian",
    "Vitamin C Deficiency Scurvy Diagnosis Treatment",
    "Omega-3 Fatty Acids Cardiovascular Brain Health",
    "Fiber Intake Recommendations Prebiotic Effect",
    "Probiotics Evidence Specific Strains Conditions",
    "Artificial Sweeteners Metabolic Effects Safety",
    "Ultra Processed Food Health Outcomes Evidence",
    "Mediterranean Diet Adherence Score Outcomes",
    "DASH Diet Hypertension Blood Pressure Reduction",
    "Ketogenic Diet Epilepsy Weight Loss Evidence",
    "Intermittent Fasting Mechanisms Metabolic Benefits",
    "Plant Based Diet Health Outcomes Protein Adequacy",
    "Food Insecurity Social Determinant Health Outcomes",
    "Eating Disorders Nutrition Rehabilitation Refeeding",
    "Sports Nutrition Carbohydrate Loading Protein",
    "Pediatric Nutrition Failure to Thrive Management",
    "Geriatric Nutrition Sarcopenia Prevention Protein",
],

"biochemistry": [
    "Enzyme Kinetics Michaelis Menten Km Vmax",
    "Glycolysis Pathway Regulation Clinical Relevance",
    "Krebs Cycle TCA Cycle Energy Production",
    "Oxidative Phosphorylation Electron Transport Chain",
    "Gluconeogenesis Pathway Regulation Fasting",
    "Glycogen Metabolism Storage Disease Disorders",
    "Fatty Acid Oxidation Beta Oxidation Ketogenesis",
    "Cholesterol Biosynthesis Statin Mechanism",
    "Lipoprotein Metabolism LDL HDL VLDL IDL",
    "Amino Acid Metabolism Urea Cycle Disorders",
    "Purine Pyrimidine Metabolism Gout Xanthine Oxidase",
    "Heme Synthesis Porphyria Disorders",
    "DNA Replication Repair Mechanisms Fidelity",
    "RNA Transcription Translation Protein Synthesis",
    "Gene Expression Regulation Epigenetics",
    "Signal Transduction Pathways Receptor Tyrosine Kinase",
    "G-Protein Coupled Receptor Signaling cAMP PKA",
    "Cell Cycle Regulation Cyclins CDK Checkpoints",
    "Apoptosis Pathways Intrinsic Extrinsic Caspase",
    "Reactive Oxygen Species Oxidative Stress Antioxidants",
    "Free Radical Biology Antioxidant Defense Systems",
    "Nitric Oxide Synthesis Vasodilation Signaling",
    "Eicosanoid Prostaglandin Synthesis NSAID Target",
    "Steroid Hormone Biosynthesis Cortisol Estrogen",
    "Thyroid Hormone Synthesis Iodine Peroxidase",
    "Insulin Signaling Pathway Glucose Transporter",
    "Glucagon Signaling cAMP Glycogen Breakdown",
    "Hemoglobin Structure Oxygen Dissociation Curve",
    "Sickle Cell Hemoglobin S Polymerization",
    "Enzyme Replacement Therapy Lysosomal Storage",
    "Pharmacokinetics ADME Drug Metabolism CYP",
    "Drug-Drug Interaction Enzyme Induction Inhibition",
    "Receptor Pharmacology Agonist Antagonist EC50",
    "Acid-Base Chemistry Henderson Hasselbalch",
    "Buffer Systems Bicarbonate CO2 Physiology",
    "Osmolality Tonicity Calculation Clinical",
    "Anion Gap Calculation Metabolic Acidosis",
    "Tumor Metabolism Warburg Effect Aerobic Glycolysis",
    "Metabolomics Biomarker Discovery Clinical",
    "Proteomics Mass Spectrometry Clinical Application",
],

"physiology": [
    "Cardiac Output Determinants Preload Afterload",
    "Frank-Starling Mechanism Cardiac Function",
    "Cardiac Action Potential Ion Channels",
    "Blood Pressure Regulation Baroreceptors RAAS",
    "Microcirculation Capillary Exchange Starling Forces",
    "Pulmonary Circulation Hypoxic Vasoconstriction",
    "Ventilation Perfusion Matching V/Q Ratio",
    "Work of Breathing Compliance Resistance",
    "Gas Exchange Fick Principle Diffusion Capacity",
    "Acid-Base Regulation Kidney Lung Buffer",
    "Renal Filtration GFR Autoregulation",
    "Tubular Reabsorption Secretion Nephron Segments",
    "Renin Angiotensin Aldosterone System Regulation",
    "Antidiuretic Hormone ADH Water Reabsorption",
    "Atrial Natriuretic Peptide ANP Heart Failure",
    "Gastrointestinal Motility Peristalsis Migrating Motor",
    "Gastric Acid Secretion Parietal Cell Proton Pump",
    "Bile Secretion Enterohepatic Circulation",
    "Pancreatic Secretion Enzyme Bicarbonate",
    "Liver Detoxification First Pass Metabolism",
    "Hypothalamic Pituitary Axis Feedback Regulation",
    "Growth Hormone IGF-1 Axis Deficiency Excess",
    "Thyroid Hormone Metabolism Peripheral Conversion",
    "Adrenal Axis HPA Cortisol Circadian",
    "Reproductive Hormones Menstrual Cycle Regulation",
    "Insulin Secretion Glucose Sensing Beta Cell",
    "Glucagon Counter-Regulatory Response Hypoglycemia",
    "Neuromuscular Junction Acetylcholine Transmission",
    "Skeletal Muscle Contraction Sliding Filament Theory",
    "Smooth Muscle Regulation Calcium Calmodulin",
    "Action Potential Nerve Conduction Velocity",
    "Synaptic Transmission Neurotransmitter Release",
    "Blood Brain Barrier Transport Mechanisms",
    "Thermoregulation Fever Hypothermia Mechanisms",
    "Exercise Physiology VO2 Max Lactate Threshold",
    "Altitude Physiology Acclimatization Hypoxia",
    "Diving Physiology Nitrogen Narcosis DCS",
    "Fluid Balance Compartments ICF ECF Osmosis",
    "Platelet Activation Aggregation Coagulation Cascade",
    "Fibrinolysis tPA Plasmin Antifibrinolytics",
],

"sexual-health": [
    "Sexually Transmitted Infections Screening Guidelines",
    "Gonorrhea Increasing Resistance Ceftriaxone Treatment",
    "Chlamydia Trachomatis Screening Treatment Azithromycin",
    "Syphilis Primary Secondary Tertiary Diagnosis Treatment",
    "Herpes Simplex Virus HSV-2 Genital Suppression",
    "Human Papillomavirus HPV Vaccination Genital Warts",
    "Trichomoniasis Diagnosis Metronidazole Treatment",
    "Bacterial Vaginosis Clue Cells Whiff Test",
    "Vulvovaginal Candidiasis Recurrent Treatment",
    "Pelvic Inflammatory Disease Diagnosis Treatment",
    "Epididymo-Orchitis Etiology Treatment",
    "HIV Pre-Exposure Prophylaxis PrEP Tenofovir",
    "HIV Post-Exposure Prophylaxis PEP 28 Day Protocol",
    "HIV Undetectable Untransmittable U=U Message",
    "Erectile Dysfunction PDE5 Inhibitors Evaluation",
    "Female Sexual Dysfunction Assessment Treatment",
    "Hypoactive Sexual Desire Disorder Flibanserin",
    "Gender Affirming Care Hormone Therapy",
    "Transgender Healthcare Hormone Monitoring",
    "Intersex Conditions DSD Diagnosis Management",
    "Sexual Dysfunction Antidepressant Induced",
    "Premature Ejaculation Dapoxetine Behavioral Therapy",
    "Vaginismus Pelvic Floor Physical Therapy",
    "Dyspareunia Evaluation Vulvodynia Localized",
    "Contraception Options Efficacy Comparison",
    "Emergency Contraception Levonorgestrel Copper IUD",
    "Long Acting Reversible Contraception LARC IUD Implant",
    "Fertility Awareness Methods Natural Family Planning",
    "Intimate Partner Violence Screening Mandatory Reporting",
    "Sexual Assault Medical Forensic Examination",
    "Adolescent Sexual Health Education Abstinence Plus",
    "LGBT Health Disparities Minority Stress Model",
    "Male Hypogonadism Testosterone Replacement",
    "Menopause Genitourinary Syndrome Vaginal Estrogen",
    "Sexual Health Aging Older Adults Counseling",
],

"mens-health": [
    "Prostate Cancer Screening PSA Shared Decision",
    "Benign Prostatic Hyperplasia Alpha Blockers 5-ARI",
    "Prostatitis Chronic Pelvic Pain Syndrome",
    "Male Infertility Semen Analysis Evaluation",
    "Azoospermia Non-Obstructive TESE Sperm Retrieval",
    "Varicocele Effect Fertility Surgical Repair",
    "Testosterone Deficiency Hypogonadism Diagnosis",
    "Testosterone Replacement Therapy Risks Benefits",
    "Anabolic Steroid Abuse Hypogonadism Fertility",
    "Erectile Dysfunction Cardiovascular Risk Marker",
    "Penile Cancer HPV Association Diagnosis",
    "Testicular Cancer Cryptorchidism Risk Self Exam",
    "Hydrocele Varicocele Inguinal Hernia Distinction",
    "Male Breast Cancer Gynecomastia Distinction",
    "Cardiovascular Disease Men Earlier Onset Risk",
    "Metabolic Syndrome Men Testosterone Association",
    "Male Depression Underdiagnosis Stoicism Barrier",
    "Male Suicide Higher Rate Risk Factors",
    "Andropause Late Onset Hypogonadism",
    "BPH LUTS Lower Urinary Tract Symptoms Management",
    "Hematospermia Blood in Semen Evaluation",
    "Peyronie Disease Penile Fibrosis Collagenase",
    "Priapism Ischemic Non-Ischemic Emergency",
    "Male Urinary Incontinence Post-Prostatectomy",
    "Kidney Stones Recurrence Prevention Citrate",
    "Occupational Cancer Risk Male Workers",
    "Male Osteoporosis Underdiagnosed Risk Factors",
    "Colorectal Cancer Screening Men Earlier Onset",
    "Skin Cancer Men Higher Mortality Sun Behavior",
    "Male Eating Disorders Muscle Dysmorphia",
],

"anesthesiology": [
    "Pre-Anesthesia Assessment ASA Classification",
    "Airway Assessment Mallampati Difficult Airway",
    "Rapid Sequence Induction Cricoid Pressure Succinylcholine",
    "Awake Fiber Optic Intubation Technique Indications",
    "Video Laryngoscopy Difficult Airway Management",
    "General Anesthesia Induction Maintenance Agents",
    "Propofol Infusion Syndrome Critical Care Risk",
    "Volatile Anesthetic Mechanism MAC Value",
    "Neuromuscular Blocking Agents Reversal Sugammadex",
    "Regional Anesthesia Neuraxial Epidural Spinal",
    "Peripheral Nerve Block Ultrasound Guided Technique",
    "Interscalene Block Shoulder Surgery Pneumothorax",
    "Femoral Nerve Block vs Adductor Canal Knee",
    "Transversus Abdominis Plane TAP Block",
    "Erector Spinae Plane Block Thoracic Abdominal",
    "Spinal Anesthesia Hypotension Prevention Treatment",
    "Epidural Analgesia Labor Opioid Local Anesthetic",
    "Post Dural Puncture Headache Blood Patch",
    "Malignant Hyperthermia Trigger Agents Dantrolene",
    "Anaphylaxis Under Anesthesia Latex Muscle Relaxant",
    "Awareness Under Anesthesia Prevention BIS Monitor",
    "PONV Prevention Ondansetron Dexamethasone",
    "Perioperative Fasting Guidelines NPO Rules",
    "Enhanced Recovery After Surgery ERAS Protocol",
    "Multimodal Analgesia Opioid Sparing Technique",
    "Pediatric Anesthesia Developmental Considerations",
    "Geriatric Anesthesia Cognitive Decline Risk",
    "Obstetric Anesthesia High Spinal Aspiration Risk",
    "Cardiac Anesthesia TEE Monitoring Protamine",
    "Thoracic Anesthesia One Lung Ventilation DLT",
    "Neuroanesthesia Cerebral Autoregulation ICP",
    "Total Intravenous Anesthesia TIVA TCI Propofol",
    "Ketamine Dissociative Anesthesia Emergence",
    "Dexmedetomidine Sedation ICU Procedural",
    "Postoperative Pulmonary Complications Prevention",
    "Perioperative Hypothermia Prevention Warming",
    "Blood Conservation Transfusion Trigger Cell Salvage",
    "Point of Care Coagulation TEG ROTEM Guided",
    "ICU Sedation Analgesia ABCDEF Bundle",
    "Chronic Pain Perioperative Management Opioid Tolerant",
],

"critical-care": [
    "Sepsis 3.0 Definition qSOFA SOFA Criteria",
    "Septic Shock Bundle 1 Hour 3 Hour Treatment",
    "Fluid Resuscitation Crystalloid vs Colloid",
    "Vasopressors Norepinephrine Vasopressin Angiotensin",
    "Mechanical Ventilation Modes Volume Pressure Control",
    "Lung Protective Ventilation ARDS 6mL kg Plateau",
    "ARDS Berlin Definition Mild Moderate Severe",
    "Prone Positioning ARDS Mortality Benefit",
    "Neuromuscular Blockade Early ARDS Cisatracurium",
    "Ventilator Weaning Readiness Criteria SBT",
    "Spontaneous Breathing Trial T-Piece PSV Method",
    "Extubation Failure Risk Factors Post-Extubation",
    "High Flow Nasal Cannula HFNC ARDS COVID",
    "Non-Invasive Ventilation BiPAP CPAP Indications",
    "Tracheostomy Timing Percutaneous vs Surgical",
    "Renal Replacement Therapy CRRT IHD Indications",
    "Continuous Renal Replacement Therapy CRRT Modes",
    "AKI in Sepsis Biomarkers NGAL Cystatin C",
    "ICU Nutrition Early Enteral Trophic Feeding",
    "Stress Ulcer Prophylaxis PPI H2 Blocker ICU",
    "DVT Prophylaxis Anticoagulation Compression ICU",
    "ICU Delirium Assessment CAM-ICU Prevention",
    "ABCDEF Bundle Liberation from ICU Ventilator",
    "Post-Intensive Care Syndrome PICS Family",
    "Cardiogenic Shock Intra-Aortic Balloon ECMO",
    "ECMO VA vs VV Indications Cannulation",
    "Targeted Temperature Management Post Cardiac Arrest",
    "Brain Death Declaration Testing Protocol",
    "Organ Donation After Brain Death DCD Protocol",
    "Massive Transfusion Protocol 1:1:1 Ratio",
    "Traumatic Hemorrhage Damage Control Resuscitation",
    "Burns Critical Care Fluid Parkland Formula",
    "Abdominal Compartment Syndrome Measurement",
    "Multi-Organ Dysfunction Failure Scoring SOFA",
    "ICU Acquired Weakness Rehabilitation Early",
    "Daily Sedation Interruption Awakening Trial",
    "Palliative Care ICU Integration End of Life",
    "Surviving Sepsis Campaign Guidelines 2021",
    "Corticosteroids Septic Shock Hydrocortisone",
    "Antimicrobial Stewardship ICU De-Escalation",
],

# Expansion of existing categories
"cardiology-new": [
    "Heart Failure with Preserved Ejection Fraction HFpEF",
    "ARNI Sacubitril Valsartan HFrEF Mortality Benefit",
    "SGLT2 Inhibitors Heart Failure Empagliflozin",
    "Cardiac Resynchronization Therapy CRT Indications",
    "Implantable Cardioverter Defibrillator ICD Primary Prevention",
    "Subcutaneous ICD S-ICD Leadless Pacemaker",
    "Transcatheter Aortic Valve Replacement TAVR Outcomes",
    "Mitral Valve Repair vs Replacement Outcomes",
    "MitraClip Transcatheter Mitral Valve Repair",
    "Tricuspid Regurgitation Management Emerging Therapies",
    "Hypertrophic Cardiomyopathy Mavacamten Treatment",
    "Cardiac Amyloidosis Transthyretin Tafamidis",
    "Inflammatory Cardiomyopathy Myocarditis Immunosuppression",
    "Peripartum Cardiomyopathy Bromocriptine Treatment",
    "Chagas Cardiomyopathy Trypanosoma Diagnosis",
    "Athletes Heart Differentiation Cardiomyopathy",
    "Sudden Cardiac Death Young Athletes Screening",
    "Brugada Syndrome Risk Stratification Quinidine",
    "Long QT Syndrome Drug-Induced Congenital",
    "Catecholaminergic Polymorphic VT Flecainide Beta",
    "Pericarditis Colchicine Aspirin Treatment",
    "Constrictive Pericarditis Pericardiectomy Diagnosis",
    "Cardiac Tamponade Pulsus Paradoxus Echocardiography",
    "Coronary Artery Spasm Vasospastic Angina Nitrates",
    "Spontaneous Coronary Artery Dissection SCAD Young Women",
    "Coronary CT Angiography Calcium Score Risk",
    "Fractional Flow Reserve FFR iFR Lesion Assessment",
    "Optical Coherence Tomography OCT Coronary Imaging",
    "Intravascular Ultrasound IVUS Plaque Assessment",
    "Rotational Atherectomy Calcified Lesion PCI",
    "Chronic Total Occlusion PCI Technique Outcomes",
    "Drug Eluting Stent DAPT Duration Optimization",
    "Antithrombotic Therapy AF PCI Triple Therapy",
    "Pulmonary Arterial Hypertension ERA PDE5 Prostacyclin",
    "Eisenmenger Syndrome Adult Congenital Management",
    "Patent Foramen Ovale Cryptogenic Stroke Closure",
    "Left Atrial Appendage Closure WATCHMAN AFib",
    "Renal Denervation Hypertension Resistant",
    "Cardio-Oncology Chemotherapy Cardiotoxicity",
    "Immune Checkpoint Inhibitor Myocarditis",
    "Cardiac Rehabilitation Digital Remote Programs",
    "Wearable Devices Arrhythmia Detection Algorithm",
    "AI ECG Interpretation Clinical Applications",
    "Heart Failure Remote Monitoring Telemonitoring",
    "Cardiorenal Syndrome Type Classification",
    "Diuretic Resistance Strategies Combination",
    "Ferric Carboxymaltose Iron Deficiency Heart Failure",
    "Vericiguat Heart Failure sGC Stimulator",
    "Finerenone Diabetic Cardiorenal Protection",
    "Obesity Cardiomyopathy Weight Loss Benefit",
],

"neurology-new": [
    "Multiple Sclerosis High Efficacy DMT Early Treatment",
    "Ocrelizumab Ofatumumab B Cell Depletion MS",
    "Natalizumab JC Virus PML Risk Stratification",
    "Cladribine Alemtuzumab Immune Reconstitution MS",
    "Neuromyelitis Optica Spectrum Disorder AQP4 MOG",
    "Eculizumab Inebilizumab Satralizumab NMOSD",
    "MOG-Associated Disease MOGAD Diagnosis Treatment",
    "Anti-NMDA Receptor Encephalitis Young Women",
    "LGI1 Encephalitis Faciobrachial Dystonic Seizures",
    "CASPR2 Encephalitis Morvan Syndrome",
    "Hashimoto Encephalopathy Steroid Responsive",
    "Alzheimer Disease Aducanumab Lecanemab Amyloid",
    "Tau PET Imaging Alzheimer Staging",
    "Lewy Body Dementia DLB REM Behavior Disorder",
    "Frontotemporal Dementia FTD C9orf72 TDP-43",
    "Progressive Supranuclear Palsy PSP Richardson",
    "Corticobasal Syndrome CBS Degeneration",
    "Huntington Disease Gene Therapy Tominersen",
    "ALS Riluzole Edaravone Tofersen Treatment",
    "Spinal Muscular Atrophy Nusinersen Gene Therapy",
    "Duchenne Muscular Dystrophy Exon Skipping Therapy",
    "Myasthenia Gravis Eculizumab Efgartigimod",
    "Lambert-Eaton Myasthenic Syndrome VGCC Antibody",
    "Chronic Inflammatory Demyelinating Polyneuropathy",
    "Multifocal Motor Neuropathy IVIg Treatment",
    "Guillain-Barre Syndrome Variants Miller Fisher",
    "Focal Epilepsy Laser Ablation Responsive Stimulation",
    "Dravet Syndrome Fenfluramine Cannabidiol",
    "Lennox-Gastaut Syndrome Cannabidiol Everolimus",
    "Tuberous Sclerosis mTOR Inhibitor Everolimus",
    "Sturge-Weber Syndrome Sirolimus Aspirin",
    "Transient Ischemic Attack ABCD2 Score Imaging",
    "Stroke Thrombolysis Tenecteplase vs Alteplase",
    "Mechanical Thrombectomy Extended Window DAWN DEFUSE",
    "Stroke Secondary Prevention Ticagrelor Clopidogrel",
    "Cerebral Venous Thrombosis Anticoagulation Pregnancy",
    "CADASIL Cerebral Autosomal Dominant Arteriopathy",
    "Idiopathic Intracranial Hypertension Acetazolamide",
    "Normal Pressure Hydrocephalus Shunt Outcomes",
    "Chiari Malformation Diagnosis Surgical Indication",
    "Syringomyelia Treatment Decompression Shunting",
    "Peripheral Neuropathy Small Fiber Skin Biopsy",
    "Brachial Plexus Injury Neuralgic Amyotrophy",
    "Meralgia Paresthetica Lateral Femoral Cutaneous",
    "Carpal Tunnel Syndrome NCS Guided Treatment",
    "Tarsal Tunnel Syndrome Tibial Nerve Entrapment",
    "Essential Tremor Propranolol Primidone MRI HIFU",
    "Tourette Syndrome Habit Reversal Training",
    "Restless Legs Syndrome Iron Dopamine Augmentation",
],

"oncology-new": [
    "Immunotherapy Combination Checkpoint Dual Blockade",
    "Tumor Mutational Burden Pembrolizumab Biomarker",
    "Microsatellite Instability MMR Deficiency Immunotherapy",
    "NTRK Fusion Larotrectinib Tumor Agnostic",
    "RET Fusion Selpercatinib Pralsetinib Treatment",
    "KRAS G12C Mutation Sotorasib Adagrasib Lung",
    "ALK Rearrangement Alectinib Brigatinib Lorlatinib",
    "EGFR Mutation Osimertinib Resistance Mechanisms",
    "HER2 Positive Breast Tucatinib T-DXd Trastuzumab",
    "BRCA Mutation Olaparib Rucaparib PARP Inhibitor",
    "CDK4/6 Inhibitor Palbociclib Ribociclib Breast",
    "PIK3CA Mutation Alpelisib Breast Cancer",
    "Antibody Drug Conjugate ADC Sacituzumab Govitecan",
    "Bispecific Antibody Blinatumomab Teclistamab",
    "CAR-T Therapy Toxicity CRS ICANS Management",
    "Chimeric Antigen Receptor T Cell Products",
    "Stem Cell Transplant Autologous Allogeneic Selection",
    "Graft Versus Tumor Effect GVT Relapse",
    "Minimal Residual Disease MRD Testing Leukemia",
    "Cell Free DNA Liquid Biopsy Cancer Detection",
    "Precision Oncology Tumor Profiling Foundation One",
    "Adaptive Trial Design Basket Umbrella Trials",
    "Real World Evidence Oncology Regulatory Approval",
    "Financial Toxicity Cancer Treatment Cost",
    "Palliative Chemotherapy Goals QoL vs OS",
    "Oligometastatic Disease SBRT Cure Potential",
    "Hypofractionation Radiotherapy Breast Prostate",
    "SBRT Stereotactic Body Lung Liver Pancreas",
    "Proton Therapy Advantages Pediatric Head Neck",
    "Immunotherapy Toxicity Steroid Management",
    "Tumor Lysis Syndrome Prevention Rasburicase",
    "Febrile Neutropenia Risk Stratification MASCC",
    "Antiemesis CINV Prophylaxis NK1 5-HT3",
    "Cancer Cachexia Anamorelin Multimodal",
    "Survivorship Care Plan Late Effects Monitoring",
    "Hereditary Breast Ovarian BRCA Testing Cascade",
    "Lynch Syndrome Universal Tumor Screening",
    "Li-Fraumeni Syndrome TP53 Surveillance",
    "Uveal Melanoma Tebentafusp Liver Metastasis",
    "Cholangiocarcinoma FGFR2 IDH1 Targeted Therapy",
    "Hepatocellular Carcinoma Atezolizumab Bevacizumab",
    "Gastric Cancer HER2 Claudin18.2 Targets",
    "Endometrial Cancer Pembrolizumab Lenvatinib",
    "Cervical Cancer Pembrolizumab Tisotumab",
    "Ovarian Cancer BRCA PARP Maintenance Olaparib",
    "Myeloma Quadruplet Induction Daratumumab",
    "Follicular Lymphoma Obinutuzumab Lenalidomide",
    "DLBCL Polatuzumab Vedotin R-CHP Regimen",
    "Mantle Cell Lymphoma Ibrutinib Venetoclax",
    "CLL BTK Inhibitor Venetoclax BCL-2",
    "MDS Imetelstat Luspatercept Lower Risk",
],

"psychiatry-new": [
    "Treatment Resistant Depression Esketamine Nasal",
    "Ketamine Infusion Treatment Resistant Depression",
    "Electroconvulsive Therapy ECT Indications Technique",
    "Transcranial Magnetic Stimulation TMS Major Depression",
    "Psychedelic Assisted Therapy Psilocybin PTSD",
    "MDMA Assisted Therapy PTSD Phase 3 Trials",
    "Bipolar II Disorder Underdiagnosis Quetiapine",
    "Rapid Cycling Bipolar Disorder Lamotrigine Clozapine",
    "Bipolar Depression Lumateperone Cariprazine",
    "Postpartum Depression Brexanolone Zuranolone",
    "Premenstrual Dysphoric Disorder SSRI Hormonal",
    "ADHD Adult Diagnosis Stimulant Nonstimulant",
    "Autism Spectrum Disorder Pharmacological Behavioral",
    "Intellectual Disability Psychiatric Comorbidity",
    "Borderline Personality Disorder DBT Evidence",
    "Antisocial Personality Disorder Treatment Challenges",
    "Narcissistic Personality Disorder Psychodynamic",
    "Obsessive Compulsive Disorder ERP Fluvoxamine",
    "OCD Spectrum Hoarding Body Dysmorphic Disorder",
    "Panic Disorder Agoraphobia SSRI CBT Treatment",
    "Social Anxiety Disorder Phenelzine Paroxetine",
    "Generalized Anxiety Disorder Buspirone Duloxetine",
    "Specific Phobia Exposure Therapy Systematic",
    "PTSD Prolonged Exposure EMDR CPT Comparison",
    "Complex PTSD Developmental Trauma ICD-11",
    "Dissociative Disorders Amnesia Depersonalization",
    "Somatic Symptom Disorder Functional Neurological",
    "Anorexia Nervosa Medical Complications Refeeding",
    "Bulimia Nervosa CBT-E Fluoxetine Treatment",
    "Binge Eating Disorder Lisdexamfetamine Treatment",
    "Avoidant Restrictive Food Intake Disorder ARFID",
    "Schizophrenia Long Acting Injectable Clozapine",
    "Treatment Resistant Schizophrenia Clozapine",
    "Negative Symptoms Schizophrenia Amisulpride",
    "First Episode Psychosis Early Intervention",
    "Schizoaffective Disorder Diagnosis Stability",
    "Delusional Disorder Types Forensic Implications",
    "Catatonia Lorazepam ECT Diagnosis",
    "Neuroleptic Malignant Syndrome Risk Factors",
    "Tardive Dyskinesia Valbenazine Deutetrabenazine",
    "Metabolic Syndrome Antipsychotic Monitoring",
    "Psychiatric Pharmacogenomics CYP2D6 2C19",
    "Collaborative Care Model Depression Primary Care",
    "Digital Mental Health Apps CBT Evidence",
    "Telepsychiatry Effectiveness Access Equity",
],

"endocrinology-new": [
    "Type 1 Diabetes Closed Loop Artificial Pancreas",
    "Continuous Glucose Monitor CGM Accuracy Flash",
    "Hybrid Closed Loop Insulin Pump Algorithm",
    "Diabetes Technology Time in Range TIR",
    "Latent Autoimmune Diabetes Adults LADA Treatment",
    "Maturity Onset Diabetes of Young MODY Genetic",
    "Gestational Diabetes Glyburide Metformin Insulin",
    "Diabetic Ketoacidosis DKA Euglycemic SGLT2",
    "Hyperosmolar Hyperglycemic State HHS Management",
    "Hypoglycemia Unawareness Treatment Prevention",
    "Glucagon Nasal Spray Auto-Injector Hypoglycemia",
    "GLP-1 Receptor Agonist Weight Loss Semaglutide",
    "Tirzepatide Dual GIP GLP-1 Agonist Outcomes",
    "Obesity Pharmacotherapy Phentermine Topiramate",
    "Bariatric Surgery Metabolic Effects Remission",
    "Cushing Disease Pasireotide Osilodrostat Treatment",
    "Adrenal Incidentaloma Workup Malignancy Assessment",
    "Adrenocortical Carcinoma Mitotane EDP-M",
    "Pheochromocytoma Paraganglioma Genetic Testing",
    "Primary Hyperaldosteronism Adrenal Vein Sampling",
    "Congenital Adrenal Hyperplasia Salt Wasting",
    "Acromegaly Surgery Medical Therapy Pegvisomant",
    "Prolactinoma Cabergoline Resistance Surgery",
    "Diabetes Insipidus Desmopressin Central Nephrogenic",
    "SIADH Hyponatremia Fluid Restriction Tolvaptan",
    "Primary Hyperparathyroidism Cinacalcet Surgery",
    "Hypoparathyroidism PTH Replacement Recombinant",
    "Thyroid Nodule Management ATA Guidelines Biopsy",
    "Papillary Thyroid Cancer Active Surveillance",
    "Radioactive Iodine Thyroid Cancer Risk Stratification",
    "Thyroid Hormone Replacement Desiccated T3 T4",
    "Graves Disease Antithyroid Drug Relapse Prediction",
    "Subclinical Hypothyroidism Treatment Threshold",
    "Thyroid Eye Disease Teprotumumab Treatment",
    "Hypogonadism Male Female Hormone Replacement",
    "Polycystic Ovary Syndrome Pathophysiology Treatment",
    "Inositol Myo-Inositol PCOS Insulin Sensitization",
    "Premature Ovarian Insufficiency HRT Fertility",
    "Turner Syndrome Growth Hormone Adult Management",
    "Klinefelter Syndrome Testosterone Replacement",
    "Autoimmune Polyglandular Syndrome Type I II",
    "Multiple Endocrine Neoplasia MEN1 MEN2 Screening",
    "Carcinoid Syndrome Octreotide Telotristat",
    "Insulinoma Diazoxide Everolimus Surgery",
    "Glucagonoma Necrolytic Migratory Erythema",
    "Lipodystrophy Leptin Replacement Metreleptin",
    "Obesity Hypogonadism Metabolic Hormone Axes",
    "Adipokine Leptin Adiponectin Metabolic Syndrome",
    "Thyroid Cancer Kinase Inhibitor Lenvatinib Sorafenib",
],

"pediatrics-new": [
    "Neonatal Sepsis Early Late Onset GBS Treatment",
    "Respiratory Distress Syndrome Surfactant Therapy",
    "Bronchopulmonary Dysplasia Prevention Caffeine",
    "Necrotizing Enterocolitis Prevention Probiotics",
    "Intraventricular Hemorrhage Grading Management",
    "Hypoxic Ischemic Encephalopathy Cooling Therapy",
    "Neonatal Abstinence Syndrome Scoring Treatment",
    "Jaundice Neonatal Phototherapy Exchange Transfusion",
    "Congenital Heart Disease Prostaglandin E1 Ductal",
    "Pediatric Sepsis Surviving Sepsis Campaign",
    "Kawasaki Disease IVIG Aspirin Echocardiography",
    "Multisystem Inflammatory Syndrome MIS-C COVID",
    "Juvenile Idiopathic Arthritis Biologic Treatment",
    "Pediatric Lupus Hydroxychloroquine Steroid",
    "Type 1 Diabetes Pediatric Closed Loop Pump",
    "Pediatric Obesity Management Family Intervention",
    "ADHD Pediatric Stimulant Monitoring",
    "Autism Spectrum Disorder Early Intervention ABA",
    "Childhood Anxiety CBT Parent Training",
    "Pediatric OCD ERP SSRI Treatment",
    "Tourette Syndrome Alpha Agonist Behavior",
    "Pediatric Epilepsy Ketogenic Diet SUDEP Risk",
    "Febrile Seizure Recurrence Risk Management",
    "Childhood Absence Epilepsy Ethosuximide",
    "Pediatric Migraine Topiramate Prevention",
    "Infant Botulism Honey Risk BabyBIG",
    "Pertussis Whooping Cough Macrolide Prevention",
    "Pediatric Pneumonia Antibiotic Selection Duration",
    "RSV Bronchiolitis Nirsevimab Prevention Therapy",
    "Croup Laryngotracheobronchitis Dexamethasone",
    "Epiglottitis Airway Emergency HiB Vaccine",
    "Foreign Body Aspiration Management Bronchoscopy",
    "Urinary Tract Infection Pediatric Imaging Guidelines",
    "Vesicoureteral Reflux Antibiotic Prophylaxis",
    "Nephrotic Syndrome Pediatric Steroid Cyclophosphamide",
    "Hemolytic Uremic Syndrome STEC Management",
    "Henoch Schonlein Purpura IgA Vasculitis",
    "Intussusception Pneumatic Reduction Diagnosis",
    "Pyloric Stenosis Projectile Vomiting Surgical",
    "Hirschsprung Disease Pull Through Procedure",
    "Failure to Thrive Organic Nonorganic Evaluation",
    "Child Maltreatment Medical Evaluation Fractures",
    "Safe Sleep SIDS Prevention Back to Sleep",
    "Vaccination Schedule Complete Catch Up",
    "School Readiness Developmental Screening Tools",
    "Adolescent Medicine Confidentiality HEADS",
    "Teen Depression Fluoxetine CBT Black Box",
    "Eating Disorders Adolescents Family Based Therapy",
    "Sports Concussion Return to Play Protocol",
    "Transition Adult Care Chronic Condition Youth",
],

"infectious-new": [
    "COVID-19 Antivirals Nirmatrelvir Remdesivir",
    "Long COVID Pathophysiology Autoimmunity Treatment",
    "Monkeypox Mpox Tecovirimat Treatment",
    "Ebola Virus Disease Atoltivimab Maftivimab",
    "Marburg Virus Disease Monoclonal Antibody",
    "Dengue Fever Dengvaxia Vaccine Warning",
    "Zika Virus Microcephaly Guillain-Barre",
    "Chikungunya Virus Arthritis Treatment",
    "West Nile Virus Neuroinvasive Disease",
    "Hantavirus Cardiopulmonary Syndrome",
    "Leptospirosis Weil Disease Penicillin",
    "Q Fever Coxiella Burnetii Doxycycline",
    "Tularemia Francisella Tularensis Gentamicin",
    "Plague Yersinia Pestis Streptomycin",
    "Anthrax Bacillus Anthracis Ciprofloxacin",
    "Drug Resistant Tuberculosis XDR-TB Bedaquiline",
    "Latent TB Treatment 3HP 4R Regimens",
    "HIV Opportunistic Infections PCP MAI CMV",
    "HIV Drug Resistance Integrase Inhibitor",
    "Cryptococcal Meningitis Flucytosine Amphotericin",
    "Aspergillosis Invasive Voriconazole Isavuconazole",
    "Mucormycosis Isavuconazole Liposomal Amphotericin",
    "Candida Auris Emerging Resistance Management",
    "Strongyloides Hyperinfection Immunosuppressed",
    "Chagas Disease Benznidazole Nifurtimox",
    "Visceral Leishmaniasis Liposomal Amphotericin",
    "Malaria Artemisinin Combination Therapy",
    "Severe Malaria IV Artesunate Management",
    "Hepatitis Delta Bulevirtide Pegylated Interferon",
    "Hepatitis E Virus Ribavirin Immunosuppressed",
    "Norovirus Outbreak Control Healthcare",
    "Clostridioides Difficile FMT Bezlotoxumab",
    "MRSA Bacteremia Daptomycin Ceftaroline",
    "Vancomycin AUC/MIC Monitoring Toxicity",
    "Beta Lactam Prolonged Infusion PK/PD Optimization",
    "Antimicrobial Stewardship Pharmacist Physician",
    "Infection Control Bundle CLABSI CAUTI VAP",
    "Healthcare Associated Infection Surveillance NHSN",
    "Diagnostic Stewardship Blood Culture Optimization",
    "Rapid Diagnostics FilmArray MALDI-TOF",
],

"pharmacology-new": [
    "Drug Pharmacokinetics Aging Elderly Dosing",
    "Pediatric Pharmacokinetics Weight Based Dosing",
    "Renal Dosing Adjustment Cockroft-Gault eGFR",
    "Hepatic Dosing Child-Pugh Score Drug Clearance",
    "Medication Reconciliation Transitions of Care",
    "High Alert Medications Safety Strategies",
    "Polypharmacy Deprescribing Elderly Criteria",
    "Beers Criteria Inappropriate Medications Elderly",
    "Drug Interaction Databases Clinical Significance",
    "CYP3A4 Inducers Inhibitors Common Drugs",
    "P-Glycoprotein Drug Interaction Mechanism",
    "Warfarin Drug Food Interaction Management",
    "Novel Oral Anticoagulant Drug Interactions",
    "Proton Pump Inhibitor Drug Interaction CYP2C19",
    "Statin Drug Interaction Rhabdomyolysis Risk",
    "Antibiotic Pharmacodynamics AUC MIC MBC",
    "Beta Lactam Time Dependent Killing Prolonged",
    "Aminoglycoside Once Daily Dosing Protocol",
    "Vancomycin AUC Guided Dosing New Guidelines",
    "Antiepileptic Drug Interaction Mechanisms",
    "Antidepressant Drug Interaction Serotonin Syndrome",
    "Antipsychotic Metabolic Monitoring Protocol",
    "Lithium Toxicity Drug Interactions NSAIDs Thiazide",
    "Oral Hypoglycemic Drug Interaction Considerations",
    "Thyroid Hormone Absorption Interaction",
    "Immunosuppressant Calcineurin Drug Level Monitoring",
    "HIV Antiretroviral Drug Interaction Complexity",
    "Antiretroviral Therapy Initiation Regimen Selection",
    "Antifungal Drug Interaction Azole CYP",
    "Chemotherapy Drug Interaction Management",
    "Medication Error Types Root Cause Analysis",
    "Adverse Drug Reaction Reporting Pharmacovigilance",
    "Drug Recall Black Box Warning Communication",
    "Off-Label Drug Use Evidence Legal Ethical",
    "Biosimilar vs Originator Interchangeability",
    "Generic Drug Bioequivalence Standards",
    "Narrow Therapeutic Index Drug Monitoring",
    "Therapeutic Drug Monitoring Cyclosporine Level",
    "Drug Allergy Cross Reactivity Penicillin Ceph",
    "Desensitization Protocol Drug Allergy Protocol",
    "Pregnancy Category Drug Safety Classification",
    "Lactation Drug Safety LactMed Database",
    "Medication Assisted Treatment Opioid Alcohol",
    "Dose Banding Chemotherapy Standardized Regimens",
    "Oral Chemotherapy Adherence Monitoring Strategy",
    "Pharmacist Prescribing Authority Collaborative",
    "Clinical Pharmacy Services Cost Effectiveness",
    "Drug Formulary Management Therapeutic Interchange",
    "Medication Therapy Management Comprehensive Review",
    "Electronic Prescribing Alert Fatigue Override",
],

"surgery-new": [
    "Enhanced Recovery After Surgery ERAS Colorectal",
    "Laparoscopic vs Robotic Surgery Comparison Outcomes",
    "Minimally Invasive Surgery Learning Curve",
    "Natural Orifice Surgery NOTES Transgastric",
    "Single Port Laparoscopy SILS Technique",
    "Fluorescence Guided Surgery ICG Biliary",
    "Surgical Site Infection Prevention Bundle",
    "Anastomotic Leak Prevention Technique Monitoring",
    "Bowel Preparation Oral Antibiotics Colorectal",
    "Damage Control Surgery Laparotomy Trauma",
    "Negative Pressure Wound Therapy Healing",
    "Hernia Repair Mesh vs Non-Mesh Selection",
    "Inguinal Hernia Laparoscopic TAPP TEP Repair",
    "Ventral Hernia Complex Abdominal Wall Repair",
    "Bariatric Surgery Selection Sleeve Bypass Band",
    "Roux-en-Y Gastric Bypass Dumping Syndrome",
    "Sleeve Gastrectomy GERD Complications",
    "Appendectomy Antibiotic Non-Operative Uncomplicated",
    "Cholecystectomy Laparoscopic Bile Duct Injury",
    "ERCP Complications Pancreatitis Sphincterotomy",
    "Pancreatic Fistula Grade A B C Management",
    "Liver Resection Segment Anatomy Pringle",
    "Liver Transplant Living Donor Outcomes",
    "Colorectal Cancer Surgery Principles Margins",
    "Rectal Cancer TME Technique Nerve Preservation",
    "Colostomy Ileostomy Reversal Timing",
    "Thyroid Surgery Parathyroid Preservation",
    "Parathyroid Surgery Minimally Invasive MIRP",
    "Breast Conserving Surgery Sentinel Node Biopsy",
    "Mastectomy Reconstruction Implant Flap Options",
    "Axillary Lymph Node Dissection vs SLNB",
    "Surgical Oncology Principles Margin Assessment",
    "Peritoneal Metastases HIPEC Cytoreduction",
    "Esophagectomy Minimally Invasive Anastomosis",
    "Gastrectomy D2 Lymph Node Dissection",
    "Whipple Procedure Pancreaticoduodenectomy",
    "Distal Pancreatectomy Spleen Preservation",
    "Adrenalectomy Laparoscopic Posterior Retroperitoneoscopic",
    "Splenectomy Vaccination Overwhelming Post-Splenectomy",
    "Vascular Surgery Endovascular vs Open AAA",
],

"dermatology-new": [
    "Psoriasis Biologics IL-17 IL-23 TNF Comparison",
    "Secukinumab Ixekizumab IL-17A Psoriasis",
    "Risankizumab Guselkumab Tildrakizumab IL-23",
    "Atopic Dermatitis Dupilumab Tralokinumab Biologic",
    "JAK Inhibitor Upadacitinib Abrocitinib Atopic",
    "Acne Vulgaris Isotretinoin iPLEDGE Protocol",
    "Hidradenitis Suppurativa Adalimumab Secukinumab",
    "Rosacea Subtype Treatment Ivermectin Doxycycline",
    "Alopecia Areata Baricitinib Ritlecitinib JAK",
    "Vitiligo Ruxolitinib Cream Topical JAK",
    "Pemphigus Vulgaris Rituximab Dexamethasone",
    "Bullous Pemphigoid Dupilumab Omalizumab",
    "Pyoderma Gangrenosum Cyclosporine Biologics",
    "Cutaneous Lupus Hydroxychloroquine Quinacrine",
    "Dermatomyositis Treatment IVIG Rituximab",
    "Systemic Sclerosis Skin Fibrosis Nintedanib",
    "Urticaria Chronic Spontaneous Omalizumab",
    "Prurigo Nodularis Dupilumab Difelikefalin",
    "Lichen Planus Oral Cutaneous Retinoids",
    "Basal Cell Carcinoma Hedgehog Vismodegib",
    "Squamous Cell Carcinoma Cemiplimab Pembrolizumab",
    "Melanoma BRAF MEK Immunotherapy Combination",
    "Merkel Cell Carcinoma Avelumab Pembrolizumab",
    "Cutaneous T Cell Lymphoma Mycosis Fungoides",
    "Phototherapy NB-UVB Excimer Laser Psoriasis",
    "Skin Microbiome Atopic Dermatitis Dysbiosis",
    "Wound Care Chronic Ulcer Biofilm Management",
    "Keloid Hypertrophic Scar Prevention Treatment",
    "Cosmetic Dermatology Botulinum Filler Evidence",
    "Dermoscopy Training Pattern Recognition Melanoma",
],

"emergency-new": [
    "HEART Score Chest Pain Risk Stratification",
    "High Sensitivity Troponin 0 1 2 Hour Protocol",
    "PECARN Pediatric Head CT Decision Rules",
    "Ottawa Ankle Knee Rules X-Ray Decision",
    "Well's Score Pulmonary Embolism DVT",
    "CURB-65 PSI Community Acquired Pneumonia",
    "Glasgow Coma Scale Interpretation Prognosis",
    "FOUR Score Coma Assessment Intubated",
    "Airway Assessment Emergency RSI Technique",
    "Shock Classification Distributive Cardiogenic",
    "Emergency Ultrasound POCUS Protocols RUSH",
    "Massive Hemorrhage Protocol Activation Criteria",
    "Traumatic Cardiac Arrest REBOA EDT",
    "Tension Pneumothorax Needle Decompression",
    "Cardiac Tamponade Pericardiocentesis Emergency",
    "Hypertensive Emergency Labetalol Nicardipine",
    "Acute Aortic Dissection Imaging Treatment",
    "Ischemic Stroke Emergency IV tPA Criteria",
    "Status Epilepticus Refractory Treatment Protocol",
    "Hyperkalemia ECG Changes Emergency Treatment",
    "Hypercalcemia Emergency Bisphosphonate Hydration",
    "Thyroid Storm Scoring Diagnosis Treatment",
    "Adrenal Crisis Hydrocortisone Emergency",
    "Anaphylaxis Epinephrine Auto-Injector Biphasic",
    "Angioedema ACEI Hereditary Treatment",
    "Drowning Management Hypothermia Rewarming",
    "Heat Stroke Evaporative Cooling Core Temperature",
    "Rhabdomyolysis Fluid Resuscitation Urine Output",
    "Crush Syndrome Compartment Syndrome",
    "Alcohol Intoxication Wernicke Prophylaxis",
    "Excited Delirium Ketamine Sedation",
    "Septic Shock Antibiotics within 1 Hour",
    "Urinary Tract Infection Treatment Outpatient",
    "Cellulitis Necrotizing Fasciitis Distinction",
    "Acute Abdomen Peritonitis Surgical Consultation",
    "Bowel Obstruction X-Ray CT Diagnosis",
    "Ectopic Pregnancy Beta-HCG Ultrasound Protocol",
    "Eclampsia Magnesium Seizure Prevention",
    "Epistaxis Anterior Posterior Control Methods",
    "Tooth Avulsion Reimplantation Protocol",
],

"ob-gyn-new": [
    "Preeclampsia Aspirin Prevention Low Risk High Risk",
    "Preeclampsia with Severe Features Magnesium Delivery",
    "HELLP Syndrome Recognition Management Delivery",
    "Postpartum Hemorrhage ATONE Uterotonic Protocol",
    "Postpartum Hemorrhage Surgical Radiological",
    "Obstetric Hemorrhage Massive Transfusion Protocol",
    "Group B Streptococcus Screening Prophylaxis",
    "Preterm Labor Progesterone Cerclage Prevention",
    "Preterm Premature Rupture Membranes Management",
    "Placenta Accreta Spectrum Diagnosis Management",
    "Placenta Previa Delivery Planning Cesarean",
    "Shoulder Dystocia Maneuvers HELPERR",
    "Cord Prolapse Emergency Management",
    "Neonatal Resuscitation NRP Algorithm",
    "VBAC Candidate Selection Trial of Labor",
    "Induction of Labor Bishop Score Methods",
    "Oxytocin Protocol Labor Augmentation",
    "Electronic Fetal Monitoring Interpretation",
    "Category I II III FHR Tracings Management",
    "Gestational Diabetes Insulin Oral Agents",
    "Hyperemesis Gravidarum Ondansetron Nutrition",
    "Intrahepatic Cholestasis Pregnancy Ursodeoxycholic",
    "Antiphospholipid Syndrome Pregnancy Loss LMWH",
    "Thyroid Disease Pregnancy TSH Targets",
    "Depression Pregnancy Postpartum SSRI Safety",
    "Domestic Violence Screening Pregnancy Universal",
    "Infertility Evaluation Female Factor Ovarian",
    "Ovarian Stimulation IUI IVF ICSI Protocol",
    "PCOS Ovulation Induction Letrozole Clomiphene",
    "Diminished Ovarian Reserve Management",
    "Endometriosis Staging Surgical Medical",
    "Uterine Fibroids Myomectomy Embolization",
    "Endometrial Ablation Heavy Menstrual Bleeding",
    "Cervical Cancer Prevention HPV Vaccination",
    "Colposcopy Biopsy LEEP Cervical Dysplasia",
    "Ovarian Cancer Early Detection Surgery",
    "Vulvar Cancer Diagnosis Treatment",
    "Menopause Hormone Therapy WHI Revised Guidance",
    "Genitourinary Syndrome Menopause Local Estrogen",
    "Pelvic Organ Prolapse POP-Q Surgical Options",
],

"symptoms-new": [
    "Dyspnea Acute Differential Diagnosis Approach",
    "Pleuritic Chest Pain Differential Diagnosis",
    "Palpitations Evaluation ECG Holter",
    "Syncope Evaluation ROSE Rule Risk Stratification",
    "Presyncope Orthostatic Hypotension Evaluation",
    "Dizziness Vertigo Differentiation Approach",
    "Tinnitus Evaluation Audiogram Management",
    "Hearing Loss Sudden Sensorineural Steroid",
    "Diplopia Evaluation Cranial Nerve Testing",
    "Visual Field Defect Localization Neuro-Ophthalmic",
    "Dysphagia Evaluation Oropharyngeal Esophageal",
    "Odynophagia Painful Swallowing Differential",
    "Heartburn Alarm Symptoms Endoscopy",
    "Abdominal Pain Chronic Functional vs Organic",
    "Acute Diarrhea Infectious vs Non-Infectious",
    "Chronic Diarrhea Osmotic Secretory Evaluation",
    "Hematochezia Lower GI Bleeding Evaluation",
    "Melena Upper GI Bleeding Hematemesis",
    "Jaundice Classification Pre-Hepatic Hepatic",
    "Ascites Evaluation Paracentesis SAAG",
    "Peripheral Edema Bilateral Unilateral Causes",
    "Lymphadenopathy Evaluation Reactive vs Malignant",
    "Night Sweats Evaluation Infectious Malignancy",
    "Weight Loss Involuntary Evaluation Workup",
    "Fatigue Chronic Evaluation Differential",
    "Polyuria Polydipsia Diabetes Insipidus",
    "Dysuria Evaluation UTI Prostatitis STI",
    "Hematuria Gross Microscopic Evaluation",
    "Proteinuria Evaluation Spot Ratio 24-Hour",
    "Oliguria Anuria Acute Kidney Injury",
    "Back Pain Red Flags Malignancy Infection",
    "Neck Pain Cervical Radiculopathy Evaluation",
    "Hip Pain Trochanteric Bursitis Evaluation",
    "Knee Pain Anterior Posterior Medial Lateral",
    "Shoulder Pain Rotator Cuff Evaluation",
    "Wrist Pain Carpal Tunnel Ganglia Evaluation",
    "Foot Pain Plantar Fasciitis Evaluation",
    "Skin Rash Systematic Evaluation Classification",
    "Pruritus Generalized Evaluation Systemic",
    "Alopecia Pattern Non-Pattern Evaluation",
],
}

# Add new topics to "cardiology", "neurology" etc with prefix to differentiate
# These get merged into the right keys
RENAME_MAP = {
    "cardiology-new": "cardiology",
    "neurology-new": "neurology",
    "oncology-new": "oncology",
    "psychiatry-new": "psychiatry",
    "endocrinology-new": "endocrinology",
    "pediatrics-new": "pediatrics",
    "infectious-new": "infectious-diseases",
    "pharmacology-new": "pharmacology",
    "surgery-new": "surgery-procedures",
    "dermatology-new": "dermatology",
    "emergency-new": "emergency",
    "ob-gyn-new": "ob-gyn",
    "symptoms-new": "symptoms",
}

if __name__ == "__main__":
    existing = {}
    if os.path.exists("topics_extra.json"):
        with open("topics_extra.json") as f:
            existing = json.load(f)

    # Normalize new topics — merge renamed categories
    normalized = {}
    for cat, topics in NEW_TOPICS.items():
        target = RENAME_MAP.get(cat, cat)
        normalized.setdefault(target, [])
        normalized[target].extend(topics)

    # Merge: add new topics to existing, skip duplicates
    added = 0
    for cat, new_topics in normalized.items():
        existing.setdefault(cat, [])
        seen = {t.lower() for t in existing[cat]}
        for t in new_topics:
            if t.lower() not in seen:
                existing[cat].append(t)
                seen.add(t.lower())
                added += 1

    with open("topics_extra.json", "w") as f:
        json.dump(existing, f, indent=2, ensure_ascii=False)

    total = sum(len(v) for v in existing.values())
    print(f"Added {added} new topics")
    print(f"Total in topics_extra.json: {total} topics across {len(existing)} categories")
