/**
 * Clinical descriptions for all 16 calculators in 7 languages.
 * Used in the calculator [slug]/page.tsx "About this calculator" section.
 */
import type { Lang } from "./data";

export const CALC_ABOUT: Record<string, Record<Lang, string>> = {

  "egfr-ckd-epi": {
    en: "The CKD-EPI 2021 equation estimates glomerular filtration rate from serum creatinine without a race variable, eliminating racial bias introduced by the 2009 formula. It is the KDIGO-recommended method for staging chronic kidney disease (CKD) and detecting progression. An eGFR below 60 mL/min/1.73 m² persisting for ≥3 months confirms CKD and guides drug dose adjustment, nephrology referral thresholds, and cardiovascular risk stratification.",
    ru: "Уравнение CKD-EPI 2021 оценивает СКФ по креатинину сыворотки без расовой поправки — она была источником систематической ошибки в формуле 2009 года. KDIGO рекомендует его как стандарт стадирования ХБП и мониторинга прогрессирования. рСКФ ниже 60 мл/мин/1,73 м², сохраняющаяся более 3 месяцев, подтверждает ХБП и определяет коррекцию доз препаратов, пороги направления к нефрологу и оценку кардиоваскулярного риска.",
    ar: "تقدّر معادلة CKD-EPI 2021 معدل الترشيح الكبيبي من كرياتينين المصل دون استخدام متغير العرق، ما يزيل التحيز الموجود في معادلة 2009. توصي إرشادات KDIGO باستخدامها معياراً لتصنيف مراحل مرض الكلى المزمن ورصد تطوره. معدل ترشيح أقل من 60 مل/دقيقة/1.73 م² لمدة ≥3 أشهر يؤكد تشخيص المرض ويوجّه تعديل جرعات الأدوية وإحالة المريض لأخصائي الكلى.",
    es: "La ecuación CKD-EPI 2021 estima la tasa de filtración glomerular a partir de la creatinina sérica sin variable racial, eliminando el sesgo de la fórmula 2009. Es el método estándar recomendado por KDIGO para clasificar la enfermedad renal crónica (ERC) y detectar su progresión. Un TFGe menor de 60 mL/min/1,73 m² durante ≥3 meses confirma ERC y orienta el ajuste de dosis, la derivación a nefrología y la estratificación del riesgo cardiovascular.",
    de: "Die CKD-EPI 2021-Gleichung schätzt die glomeruläre Filtrationsrate aus dem Serum-Kreatinin ohne Rassenvariable und beseitigt damit den Bias der Formel von 2009. KDIGO empfiehlt sie als Standardmethode zur CKD-Stadienbestimmung und Verlaufskontrolle. Eine eGFR unter 60 ml/min/1,73 m² über ≥3 Monate bestätigt eine CKD und leitet Dosisanpassungen, Nephrologieüberweisungen und kardiovaskuläre Risikostratifizierung.",
    fr: "L'équation CKD-EPI 2021 estime le DFG à partir de la créatinine sérique sans variable ethnique, éliminant le biais de la formule 2009. Recommandée par KDIGO comme méthode standard de stadification de la MRC et de surveillance de la progression. Un DFGe inférieur à 60 mL/min/1,73 m² persistant ≥3 mois confirme la MRC et guide l'adaptation posologique et l'orientation vers un néphrologue.",
    tr: "CKD-EPI 2021 denklemi, ırk değişkeni kullanmadan serum kreatinininden GFR'yi tahmin eder; 2009 formülündeki önyargıyı ortadan kaldırır. KDIGO, KBH evrelemesi ve ilerleme takibi için standart yöntem olarak önerir. ≥3 ay süren 60 mL/dak/1,73 m²'nin altındaki eGFR, KBH'yi doğrular ve ilaç doz ayarlaması ile nefroloji sevkini yönlendirir.",
  },

  "cockcroft-gault": {
    en: "The Cockcroft-Gault formula estimates creatinine clearance using age, sex, weight, and serum creatinine. Unlike eGFR, it was derived to predict drug clearance rather than true GFR, making it the standard referenced in drug labelling and pharmacokinetic studies. It is especially critical for dosing renally-cleared drugs such as aminoglycosides, vancomycin, digoxin, and direct oral anticoagulants.",
    ru: "Формула Кокрофта-Голта оценивает клиренс креатинина по возрасту, полу, весу и уровню креатинина сыворотки. В отличие от рСКФ, она разработана для прогнозирования клиренса лекарств, поэтому является стандартом в инструкциях по применению препаратов. Особенно важна при дозировании аминогликозидов, ванкомицина, дигоксина и прямых оральных антикоагулянтов.",
    ar: "تقدّر معادلة كوكروفت-غولت تصفية الكرياتينين باستخدام العمر والجنس والوزن وكرياتينين المصل. على عكس eGFR، صُممت للتنبؤ بتصفية الأدوية لا بمعدل الترشيح الفعلي، مما يجعلها المعيار في نشرات الأدوية. وهي ضرورية لجرعات الأمينوغليكوزيدات والفانكومايسين والديجوكسين ومضادات التخثر الفموية المباشرة.",
    es: "La fórmula de Cockcroft-Gault estima el aclaramiento de creatinina usando edad, sexo, peso y creatinina sérica. A diferencia del TFGe, fue derivada para predecir la eliminación de fármacos, siendo el estándar referenciado en la ficha técnica de medicamentos. Es especialmente crítica para dosificar fármacos eliminados por vía renal: aminoglucósidos, vancomicina, digoxina y anticoagulantes orales directos.",
    de: "Die Cockcroft-Gault-Formel schätzt die Kreatinin-Clearance anhand von Alter, Geschlecht, Gewicht und Serum-Kreatinin. Anders als die eGFR wurde sie zur Vorhersage der Medikamentenelimination entwickelt und ist daher Standard in Arzneimittelzulassungen. Besonders wichtig für die Dosierung renal eliminierter Medikamente wie Aminoglykoside, Vancomycin, Digoxin und direkte orale Antikoagulanzien.",
    fr: "La formule de Cockcroft-Gault estime la clairance de la créatinine à partir de l'âge, du sexe, du poids et de la créatinine sérique. Développée pour prédire l'élimination médicamenteuse, elle est le standard référencé dans les AMM. Particulièrement importante pour la posologie des médicaments à élimination rénale : aminosides, vancomycine, digoxine et anticoagulants oraux directs.",
    tr: "Cockcroft-Gault formülü, yaş, cinsiyet, ağırlık ve serum kreatinini kullanarak kreatinin klirensini tahmin eder. eGFR'den farklı olarak gerçek GFR değil, ilaç klerensi için geliştirilmiştir ve ilaç prospektüslerinde standart olarak kullanılır. Aminoglikozidler, vankomisin, digoksin ve direkt oral antikoagülanların dozlanmasında özellikle kritiktir.",
  },

  "aki": {
    en: "KDIGO 2012 defines acute kidney injury as a rise in serum creatinine ≥0.3 mg/dL within 48 h, a ≥50% rise within 7 days, or urine output below 0.5 mL/kg/h for ≥6 h. The three-stage classification guides monitoring intensity and intervention — from optimising fluids and avoiding nephrotoxins (Stage 1) to renal replacement therapy consideration (Stage 3). Both creatinine and urine output criteria are assessed simultaneously; the higher stage applies.",
    ru: "Критерии KDIGO 2012 определяют ОПП как повышение креатинина сыворотки на ≥0,3 мг/дл за 48 ч, рост на ≥50% за 7 дней или диурез менее 0,5 мл/кг/ч в течение ≥6 ч. Трёхстадийная классификация определяет интенсивность мониторинга: от оптимизации водного баланса и отмены нефротоксинов (I стадия) до рассмотрения заместительной почечной терапии (III стадия). Оцениваются оба критерия одновременно; применяется более высокая стадия.",
    ar: "تُعرّف إرشادات KDIGO 2012 الإصابة الكلوية الحادة بارتفاع كرياتينين المصل ≥0.3 ملغ/دل خلال 48 ساعة، أو ≥50% خلال 7 أيام، أو انخفاض إدرار البول إلى أقل من 0.5 مل/كغ/ساعة لمدة ≥6 ساعات. يحدد التصنيف الثلاثي شدة التدخل: من تحسين السوائل وتجنب السموم الكلوية (المرحلة 1) إلى تقييم العلاج ببدائل الكلى (المرحلة 3). يُطبَّق أعلى مرحلة ينطبق عليها أي من المعيارين.",
    es: "Los criterios KDIGO 2012 definen la lesión renal aguda como un aumento de creatinina sérica ≥0,3 mg/dL en 48 h, ≥50% en 7 días, o diuresis <0,5 mL/kg/h durante ≥6 h. La clasificación en tres estadios guía la intensidad del monitoreo e intervención: desde optimizar fluidos y evitar nefrotóxicos (Estadio 1) hasta considerar terapia de reemplazo renal (Estadio 3). Se evalúan ambos criterios simultáneamente; aplica el estadio más alto.",
    de: "KDIGO 2012 definiert AKI als Kreatininanstieg ≥0,3 mg/dl in 48 h, ≥50 % in 7 Tagen oder Urinausscheidung <0,5 ml/kg/h für ≥6 h. Das Drei-Stufen-System leitet Monitoring und Intervention: von Volumenoptimierung und Vermeidung von Nephrotoxinen (Stufe 1) bis zur Dialyseerwägung (Stufe 3). Beide Kriterien werden gleichzeitig bewertet; das höhere Stadium gilt.",
    fr: "KDIGO 2012 définit l'IRA comme une élévation de créatinine ≥26,5 μmol/L en 48 h, ≥1,5× en 7 jours ou diurèse <0,5 mL/kg/h pendant ≥6 h. La classification en 3 stades guide l'intensité de la surveillance : de l'optimisation volémique et l'arrêt des néphrotoxiques (Stade 1) à l'épuration extra-rénale (Stade 3). Les deux critères sont évalués simultanément ; le stade le plus élevé s'applique.",
    tr: "KDIGO 2012, AKI'yi 48 saatte ≥0,3 mg/dL veya 7 günde ≥%50 kreatinin artışı ya da ≥6 saat <0,5 mL/kg/saat idrar çıkışı olarak tanımlar. Üç aşamalı sınıflama, sıvı optimizasyonu ve nefrotoksin kaçınmasından (Evre 1) renal replasman tedavisi değerlendirmesine (Evre 3) kadar müdahale yoğunluğunu yönlendirir. Her iki kriter aynı anda değerlendirilir; daha yüksek evre uygulanır.",
  },

  "corrected-calcium": {
    en: "Total serum calcium is bound approximately 40% to albumin, so hypoalbuminaemia artificially lowers measured calcium despite potentially normal ionised calcium. The Payne formula (add 0.8 mg/dL per 1 g/dL drop in albumin below 4 g/dL) corrects for this. Correction is essential in critically ill patients, malnutrition, cirrhosis, and nephrotic syndrome — groups where hypoalbuminaemia is common and true calcium status drives arrhythmia and neuromuscular risk.",
    ru: "Около 40% общего кальция крови связано с альбумином, поэтому гипоальбуминемия искусственно снижает измеренный кальций при нормальном ионизированном кальции. Формула Пейна (прибавить 0,8 мг/дл на каждые 1 г/дл снижения альбумина ниже 4 г/дл) корригирует этот эффект. Коррекция обязательна у тяжелобольных, при недоедании, циррозе и нефротическом синдроме — состояниях, где гипоальбуминемия распространена.",
    ar: "يرتبط نحو 40% من الكالسيوم الكلي في المصل بالألبومين، لذا يُنخفض نقص الألبومين الكالسيوم المقاس بشكل مصطنع رغم أن الكالسيوم المتأين قد يكون طبيعياً. تُصحح معادلة باين هذا التأثير بإضافة 0.8 ملغ/دل لكل 1 غ/دل انخفاض في الألبومين عن 4 غ/دل. التصحيح ضروري في المرضى الحرجين والسوء التغذوي وتليف الكبد والمتلازمة الكلوية.",
    es: "Aproximadamente el 40% del calcio sérico total está unido a albúmina, por lo que la hipoalbuminemia disminuye artificialmente el calcio medido aunque el calcio ionizado sea normal. La fórmula de Payne (añadir 0,8 mg/dL por cada 1 g/dL de descenso de albúmina por debajo de 4 g/dL) corrige este efecto. Esencial en pacientes críticos, desnutrición, cirrosis y síndrome nefrótico.",
    de: "Etwa 40 % des Gesamtkalziums ist albumin-gebunden, sodass Hypoalbuminämie das gemessene Kalzium trotz normalem ionisiertem Kalzium künstlich senkt. Die Payne-Formel (0,8 mg/dl pro 1 g/dl Albuminabfall unter 4 g/dl addieren) korrigiert dies. Korrektur ist essenziell bei kritisch Kranken, Mangelernährung, Leberzirrhose und nephrotischem Syndrom.",
    fr: "Environ 40 % du calcium sérique total est lié à l'albumine ; l'hypoalbuminémie abaisse donc artificiellement le calcium mesuré malgré un calcium ionisé potentiellement normal. La formule de Payne (ajouter 0,8 mg/dL par 1 g/dL de baisse d'albumine sous 4 g/dL) corrige ce biais. Essentielle chez les patients de réanimation, dénutris, cirrhotiques ou en syndrome néphrotique.",
    tr: "Toplam serum kalsiyumunun yaklaşık %40'ı albümine bağlıdır; bu nedenle hipoalbüminemi, iyonize kalsiyum normal olsa bile ölçülen kalsiyumu yapay olarak düşürür. Payne formülü (4 g/dL altındaki her 1 g/dL albümin düşüşü için 0,8 mg/dL ekle) bunu düzeltir. Yoğun bakım hastaları, yetersiz beslenme, siroz ve nefrotik sendromda düzeltme zorunludur.",
  },

  "anion-gap": {
    en: "The anion gap (Na⁺ − [Cl⁻ + HCO₃⁻], normal 8–12 mEq/L) identifies unmeasured anions and classifies metabolic acidosis as high-gap (lactic acidosis, ketoacidosis, uraemia, toxins) or normal-gap (hyperchloraemic, diarrhoea, renal tubular acidosis). Albumin correction is essential — hypoalbuminaemia lowers the gap by ~2.5 mEq/L per 1 g/dL fall, masking true high-gap acidosis. The delta-delta ratio reveals concurrent mixed disorders.",
    ru: "Анионный разрыв (Na⁺ − [Cl⁻ + HCO₃⁻], норма 8–12 мэкв/л) позволяет выявить неизмеренные анионы и классифицировать метаболический ацидоз: с высоким разрывом (лактатацидоз, кетоацидоз, уремия, отравления) или нормальным (гиперхлоремический ацидоз, диарея, канальцевый ацидоз). Коррекция на альбумин обязательна: гипоальбуминемия снижает разрыв на ~2,5 мэкв/л на каждый 1 г/дл, маскируя истинный высокоанионный ацидоз.",
    ar: "تُحدد فجوة الأنيونات (Na⁺ − [Cl⁻ + HCO₃⁻]، طبيعي 8–12 ميلي مكافئ/ل) الأنيونات غير المقاسة وتُصنف الحماض الاستقلابي: ذو الفجوة العالية (حماض اللاكتات، الكيتو، البولينا، السموم) أو الطبيعي (فرط كلور الدم، الإسهال، حماض الأنابيب الكلوية). تصحيح الألبومين ضروري إذ ينخفض الفجوة بـ 2.5 ميلي مكافئ/ل لكل انخفاض 1 غ/دل في الألبومين.",
    es: "La brecha aniónica (Na⁺ − [Cl⁻ + HCO₃⁻], normal 8–12 mEq/L) identifica aniones no medidos y clasifica la acidosis metabólica: brecha alta (acidosis láctica, cetoacidosis, uremia, tóxicos) o normal (hiperclorémica, diarrea, acidosis tubular renal). La corrección por albúmina es esencial — la hipoalbuminemia reduce la brecha ~2,5 mEq/L por 1 g/dL, enmascarando una verdadera acidosis de brecha elevada.",
    de: "Die Anionenlücke (Na⁺ − [Cl⁻ + HCO₃⁻], Normwert 8–12 mEq/L) identifiziert nicht gemessene Anionen und klassifiziert metabolische Azidosen: hohe Lücke (Laktatazidose, Ketoazidose, Urämie, Toxine) oder normale Lücke (hyperchlorämisch, Diarrhö, RTA). Albumin-Korrektur ist essenziell — Hypoalbuminämie senkt die Lücke um ~2,5 mEq/L pro 1 g/dl Abfall.",
    fr: "Le trou anionique (Na⁺ − [Cl⁻ + HCO₃⁻], normal 8–12 mEq/L) identifie les anions non mesurés et classe l'acidose métabolique : trou élevé (acidose lactique, céto-acidose, urémie, toxiques) ou normal (hyperchlorémique, diarrhée, acidose tubulaire). La correction albumine est indispensable — l'hypoalbuminémie abaisse le trou de ~2,5 mEq/L par 1 g/dL de baisse.",
    tr: "Anyon açığı (Na⁺ − [Cl⁻ + HCO₃⁻], normal 8–12 mEq/L), ölçülmemiş anyonları belirler ve metabolik asidozu sınıflar: yüksek açık (laktik asidoz, ketoasidoz, üremî, toksinler) veya normal açık (hiperkloremik, ishal, renal tübüler asidoz). Albümin düzeltmesi zorunludur — hipoalbüminemi her 1 g/dL düşüş için açığı ~2,5 mEq/L azaltır.",
  },

  "meld": {
    en: "MELD (Model for End-stage Liver Disease) predicts 90-day mortality in chronic liver disease using bilirubin, INR, and creatinine. UNOS uses MELD-Na (which adds serum sodium) for transplant allocation in candidates with MELD ≥11. Scores are recalculated every 1–7 days depending on severity; a score above 40 carries approximately 70% 3-month waitlist mortality without transplantation.",
    ru: "Шкала MELD прогнозирует 90-дневную летальность при хронических заболеваниях печени по уровням билирубина, МНО и креатинина. UNOS использует MELD-Na (с добавлением натрия крови) для приоритизации кандидатов на трансплантацию с MELD ≥11. Шкала пересчитывается каждые 1–7 дней; значение выше 40 соответствует ~70% летальности за 3 месяца без трансплантации.",
    ar: "تتنبأ شكالة MELD بالوفيات خلال 90 يوماً في أمراض الكبد المزمنة باستخدام البيليروبين ومعامل التطبيع الدولي INR والكرياتينين. تستخدم UNOS نسخة MELD-Na (مع صوديوم المصل) لتحديد أولويات زرع الكبد عند المرشحين ذوي MELD ≥11. تُعاد حسابها كل 1-7 أيام؛ الدرجة فوق 40 تعني نحو 70% وفيات في قائمة الانتظار خلال 3 أشهر دون زرع.",
    es: "La escala MELD predice la mortalidad a 90 días en enfermedad hepática crónica usando bilirrubina, INR y creatinina. UNOS usa MELD-Na (añade sodio sérico) para priorizar la asignación de trasplante en candidatos con MELD ≥11. Se recalcula cada 1–7 días según gravedad; una puntuación mayor de 40 implica ~70% de mortalidad en lista de espera a 3 meses sin trasplante.",
    de: "Der MELD-Score sagt 90-Tages-Mortalität bei chronischer Lebererkrankung anhand von Bilirubin, INR und Kreatinin voraus. UNOS verwendet MELD-Na (mit Serum-Natrium) für die Transplantationspriorisierung bei Kandidaten mit MELD ≥11. Neuberechnung alle 1–7 Tage; Score über 40 bedeutet ~70 % Wartelistenmortalität in 3 Monaten ohne Transplantation.",
    fr: "Le score MELD prédit la mortalité à 90 jours dans les hépatopathies chroniques à partir de la bilirubine, de l'INR et de la créatinine. L'UNOS utilise le MELD-Na (avec sodium sérique) pour prioriser les candidats à la transplantation hépatique avec MELD ≥11. Recalculé tous les 1 à 7 jours ; un score >40 est associé à une mortalité d'attente d'environ 70 % à 3 mois sans transplantation.",
    tr: "MELD skoru, bilirubin, INR ve kreatinin kullanarak kronik karaciğer hastalığında 90 günlük mortaliteyi tahmin eder. UNOS, MELD ≥11 olan adaylarda MELD-Na'yı (serum sodyumu eklenmiş) karaciğer nakli önceliklendirmesi için kullanır. 1–7 günde bir yeniden hesaplanır; 40'ın üzerindeki skor, nakil olmaksızın 3 ayda ~%70 bekleme listesi mortalitesine karşılık gelir.",
  },

  "bmi": {
    en: "Body mass index (BMI = kg/m²) is the standard WHO screening tool for overweight and obesity. Classification: underweight <18.5, normal 18.5–24.9, overweight 25–29.9, obese Class I 30–34.9, Class II 35–39.9, Class III ≥40. In clinical practice, BMI is a starting point — waist circumference and body composition analysis add important context, particularly in Asian populations (lower risk thresholds) and athletes with high muscle mass.",
    ru: "Индекс массы тела (ИМТ = кг/м²) — стандартный скрининговый инструмент ВОЗ для выявления избыточного веса и ожирения. Классификация: дефицит массы <18,5, норма 18,5–24,9, избыточный вес 25–29,9, ожирение I 30–34,9, II 35–39,9, III ≥40. В клинической практике ИМТ — отправная точка; окружность талии и состав тела добавляют важный контекст, особенно для азиатских популяций и спортсменов.",
    ar: "مؤشر كتلة الجسم (وزن كغ / طول م²) هو أداة الفرز المعيارية لمنظمة الصحة العالمية للكشف عن زيادة الوزن والسمنة. التصنيف: نقص وزن <18.5، طبيعي 18.5–24.9، زيادة وزن 25–29.9، سمنة درجة I 30–34.9، II 35–39.9، III ≥40. في الممارسة السريرية، يُعدّ نقطة بداية؛ محيط الخصر وتحليل تركيب الجسم يضيفان سياقاً مهماً، خاصة في المجموعات الآسيوية.",
    es: "El índice de masa corporal (IMC = kg/m²) es la herramienta estándar de la OMS para detectar sobrepeso y obesidad. Clasificación: bajo peso <18,5, normal 18,5–24,9, sobrepeso 25–29,9, obesidad I 30–34,9, II 35–39,9, III ≥40. En la práctica clínica es un punto de partida — la circunferencia de cintura y la composición corporal añaden contexto importante, especialmente en poblaciones asiáticas y atletas.",
    de: "Der Body-Mass-Index (BMI = kg/m²) ist das WHO-Standardwerkzeug zum Screening auf Übergewicht und Adipositas. Klassifikation: Untergewicht <18,5, Normalgewicht 18,5–24,9, Übergewicht 25–29,9, Adipositas Grad I 30–34,9, Grad II 35–39,9, Grad III ≥40. In der Praxis ist der BMI ein Ausgangspunkt; Taillenumfang und Körperzusammensetzung liefern wichtigen Kontext.",
    fr: "L'indice de masse corporelle (IMC = kg/m²) est l'outil de dépistage OMS standard pour le surpoids et l'obésité. Classification : insuffisance pondérale <18,5, normal 18,5–24,9, surpoids 25–29,9, obésité I 30–34,9, II 35–39,9, III ≥40. En pratique clinique, l'IMC est un point de départ ; le tour de taille et la composition corporelle apportent un contexte crucial, notamment pour les populations asiatiques.",
    tr: "Vücut kitle indeksi (VKİ = kg/m²), fazla kilo ve obezite için standart WHO tarama aracıdır. Sınıflama: zayıf <18,5, normal 18,5–24,9, fazla kilolu 25–29,9, obezite Sınıf I 30–34,9, II 35–39,9, III ≥40. Klinik pratikte VKİ bir başlangıç noktasıdır; bel çevresi ve vücut kompozisyonu özellikle Asyalı popülasyonlar ve atletler için önemli bağlam sağlar.",
  },

  "cha2ds2-vasc": {
    en: "CHA₂DS₂-VASc scores annual stroke risk in non-valvular atrial fibrillation. ESC 2020 guidelines recommend initiating oral anticoagulation for men with score ≥2 and women with score ≥3. Anticoagulation should be considered at score ≥1 (men) or ≥2 (women) if there are no contraindications. Always use alongside HAS-BLED to identify correctable bleeding risk factors before prescribing.",
    ru: "Шкала CHA₂DS₂-VASc оценивает годовой риск инсульта при неклапанной фибрилляции предсердий. Рекомендации ESC 2020 предписывают назначать антикоагулянты при ≥2 баллах у мужчин и ≥3 баллах у женщин. Антикоагуляция рассматривается при ≥1 балле (мужчины) или ≥2 баллах (женщины) при отсутствии противопоказаний. Всегда используйте совместно с HAS-BLED.",
    ar: "تُقيّم شكالة CHA₂DS₂-VASc خطر السكتة الدماغية السنوي في الرجفان الأذيني غير الصمامي. توصي إرشادات ESC 2020 ببدء التخثر الفموي عند درجة ≥2 للرجال و≥3 للنساء. يُنظر في التخثر عند ≥1 (رجال) أو ≥2 (نساء) إذا لا توجد موانع. استخدمها دائماً مع مقياس HAS-BLED لتقييم خطر النزيف.",
    es: "La escala CHA₂DS₂-VASc puntúa el riesgo anual de ictus en fibrilación auricular no valvular. Las guías ESC 2020 recomiendan iniciar anticoagulación oral con puntuación ≥2 en hombres y ≥3 en mujeres. Debe considerarse con ≥1 (hombres) o ≥2 (mujeres) sin contraindicaciones. Siempre usar junto con HAS-BLED para identificar factores de riesgo hemorrágico corregibles.",
    de: "Der CHA₂DS₂-VASc-Score bewertet das jährliche Schlaganfallrisiko bei nicht-valvulärem Vorhofflimmern. ESC 2020 empfiehlt orale Antikoagulation ab Score ≥2 (Männer) und ≥3 (Frauen). Antikoagulation sollte bei ≥1 (Männer) bzw. ≥2 (Frauen) ohne Kontraindikationen erwogen werden. Immer zusammen mit HAS-BLED anwenden.",
    fr: "Le score CHA₂DS₂-VASc évalue le risque annuel d'AVC en fibrillation auriculaire non valvulaire. Les recommandations ESC 2020 préconisent une anticoagulation orale à partir d'un score ≥2 chez l'homme et ≥3 chez la femme. Utiliser systématiquement avec le score HAS-BLED pour identifier les facteurs hémorragiques corrigibles avant la prescription.",
    tr: "CHA₂DS₂-VASc skoru, non-valvüler atriyal fibrilasyonda yıllık inme riskini değerlendirir. ESC 2020 kılavuzları, erkeklerde ≥2, kadınlarda ≥3 skor için oral antikoagülasyon başlatılmasını önerir. Kontrendikasyon yoksa erkeklerde ≥1, kadınlarda ≥2 skorunda antikoagülasyon düşünülmelidir. Reçete öncesi düzeltilebilir kanama risk faktörlerini belirlemek için HAS-BLED ile birlikte kullanın.",
  },

  "has-bled": {
    en: "HAS-BLED estimates annual major bleeding risk in atrial fibrillation patients on anticoagulation. A score ≥3 indicates high bleeding risk and should prompt correction of modifiable factors — uncontrolled hypertension, labile INR (switch to NOAC), excess alcohol, nephropathy — rather than automatic anticoagulant avoidance. In most patients, AF stroke risk exceeds bleeding risk; HAS-BLED informs shared decision-making.",
    ru: "Шкала HAS-BLED оценивает риск крупных кровотечений у пациентов с ФП на антикоагулянтной терапии. Оценка ≥3 указывает на высокий риск и требует коррекции устранимых факторов: неконтролируемая АГ, лабильное МНО (перевод на НОАК), злоупотребление алкоголем, нефропатия. У большинства пациентов риск инсульта при ФП превышает риск кровотечения.",
    ar: "تُقدّر شكالة HAS-BLED خطر النزيف الرئيسي السنوي في المرضى المصابين بالرجفان الأذيني تحت العلاج المضاد للتخثر. الدرجة ≥3 تعني خطراً عالياً وتستوجب تصحيح العوامل القابلة للتعديل: ارتفاع ضغط الدم غير المنضبط، INR غير المستقر (التحويل لـ NOAC)، الكحول الزائد، اعتلال الكلى. في معظم المرضى، يتجاوز خطر السكتة الدماغية خطر النزيف.",
    es: "HAS-BLED estima el riesgo anual de hemorragia mayor en pacientes con FA bajo anticoagulación. Una puntuación ≥3 indica alto riesgo hemorrágico y debe impulsar la corrección de factores modificables: HTA no controlada, INR lábil (cambiar a ACOD), alcohol excesivo, nefropatía. En la mayoría, el riesgo de ictus supera al hemorrágico; HAS-BLED orienta la toma de decisiones compartida.",
    de: "HAS-BLED schätzt das jährliche Majorblu­tungs­risiko bei VHF-Patienten unter Antikoagulation. Score ≥3 bedeutet hohes Blutungsrisiko und erfordert Korrektur modifizierbarer Faktoren: unkontrollierter Blutdruck, labiler INR (Wechsel zu NOAK), Alkohol, Nephropathie. Bei den meisten Patienten überwiegt das Schlaganfallrisiko; HAS-BLED unterstützt die gemeinsame Entscheidungsfindung.",
    fr: "HAS-BLED estime le risque annuel d'hémorragie majeure chez les patients en FA sous anticoagulation. Un score ≥3 indique un risque hémorragique élevé et doit conduire à corriger les facteurs modifiables : HTA non contrôlée, INR labile (switch vers AOD), alcool, néphropathie. Chez la plupart des patients, le risque d'AVC dépasse le risque hémorragique ; HAS-BLED guide la décision partagée.",
    tr: "HAS-BLED, antikoagülan alan AF hastalarında yıllık majör kanama riskini tahmin eder. ≥3 skor yüksek kanama riskini gösterir ve düzeltilebilir faktörlerin düzeltilmesini gerektirir: kontrolsüz HT, labil INR (DOAC'a geçiş), aşırı alkol, nefropati. Çoğu hastada AF inme riski kanama riskini aşar; HAS-BLED paylaşımlı karar vermeyi destekler.",
  },

  "wells-dvt": {
    en: "The Wells DVT score stratifies pre-test probability of deep vein thrombosis in symptomatic outpatients. A score ≥2 (high probability) warrants proximal compression ultrasound regardless of D-dimer. A score of 0–1 with a negative high-sensitivity D-dimer effectively excludes DVT without imaging, reducing unnecessary Doppler studies by ~40%. Not validated in anticoagulated, pregnant, or postoperative patients.",
    ru: "Шкала Wells для ТГВ стратифицирует предтестовую вероятность тромбоза глубоких вен у амбулаторных пациентов с симптомами. Оценка ≥2 (высокая вероятность) требует ультразвукового исследования вен независимо от D-димера. Оценка 0–1 с отрицательным высокочувствительным D-димером надёжно исключает ТГВ, снижая число ненужных УЗИ на ~40%.",
    ar: "تُصنف شكالة Wells للخثار الوريدي العميق احتمالية التشخيص قبل الاختبار في المرضى الخارجيين ذوي الأعراض. الدرجة ≥2 (احتمالية عالية) تستدعي الإيكو الضغطي القريب بصرف النظر عن D-dimer. الدرجة 0–1 مع D-dimer سلبي عالي الحساسية تستبعد الخثار فعلياً دون تصوير، مما يقلل الفحوصات الزائدة بنحو 40%.",
    es: "La escala Wells para TVP estratifica la probabilidad pretest de trombosis venosa profunda en pacientes ambulatorios sintomáticos. Puntuación ≥2 (alta probabilidad) requiere ecografía de compresión proximal independientemente del dímero-D. Puntuación 0–1 con dímero-D negativo de alta sensibilidad excluye TVP sin necesidad de imagen, reduciendo ecografías innecesarias en ~40%.",
    de: "Der Wells-DVT-Score schichtet die Vortestwahrscheinlichkeit einer tiefen Beinvenenthrombose bei symptomatischen ambulanten Patienten. Score ≥2 erfordert proximale Kompressionssonographie unabhängig vom D-Dimer. Score 0–1 mit negativem hochsensitivem D-Dimer schließt TVT zuverlässig aus und reduziert unnötige Duplexsonographien um ~40 %.",
    fr: "Le score de Wells TVP stratifie la probabilité pré-test de thrombose veineuse profonde chez les patients symptomatiques. Un score ≥2 (haute probabilité) impose une écho-compression proximale indépendamment du D-dimère. Un score 0–1 avec un D-dimère négatif hautement sensible exclut la TVP sans imagerie, réduisant les écho-Doppler inutiles de ~40 %.",
    tr: "Wells DVT skoru, semptomatik ayaktan hastalarda derin ven trombozu için test öncesi olasılığı katmanlandırır. ≥2 skor (yüksek olasılık), D-dimer ne olursa olsun proksimal kompresyon ultrasonunu gerektirir. 0–1 skor ile negatif yüksek duyarlıklı D-dimer, görüntüleme yapmadan DVT'yi etkin biçimde dışlar ve gereksiz Doppler çalışmalarını ~%40 azaltır.",
  },

  "heart-score": {
    en: "The HEART score (History, ECG, Age, Risk factors, Troponin) safely identifies low-risk chest pain presentations in the ED. A score ≤3 carries <2% MACE risk at 6 weeks and supports discharge with outpatient follow-up. A score ≥7 is associated with >70% MACE risk and warrants early invasive evaluation. The HEART pathway outperforms TIMI and GRACE for risk stratification in undifferentiated chest pain.",
    ru: "Шкала HEART (Анамнез, ЭКГ, Возраст, Факторы риска, Тропонин) безопасно выявляет пациентов с низким риском при боли в груди в условиях скорой помощи. Оценка ≤3 соответствует <2% риска MACE за 6 недель и позволяет выписать пациента с амбулаторным наблюдением. Оценка ≥7 связана с >70% риском MACE и требует раннего инвазивного вмешательства.",
    ar: "تُحدد شكالة HEART (التاريخ، ECG، العمر، عوامل الخطر، التروبونين) بأمان المرضى ذوي الخطورة المنخفضة بالألم الصدري في قسم الطوارئ. الدرجة ≤3 تعني خطر MACE أقل من 2% خلال 6 أسابيع وتسمح بالخروج مع متابعة خارجية. الدرجة ≥7 تعني خطراً أكثر من 70% وتستدعي تقييماً تداخلياً مبكراً.",
    es: "La escala HEART (Historia, ECG, Edad, Factores de riesgo, Troponina) identifica de forma segura presentaciones de dolor torácico de bajo riesgo en urgencias. Puntuación ≤3 implica <2% de riesgo de MACE a 6 semanas y apoya el alta con seguimiento ambulatorio. Puntuación ≥7 se asocia con >70% de riesgo de MACE y requiere evaluación invasiva precoz.",
    de: "Der HEART-Score (Anamnese, EKG, Alter, Risikofaktoren, Troponin) identifiziert sicher niedrig-risiko Brustschmerz-Präsentationen in der Notaufnahme. Score ≤3 bedeutet <2 % MACE-Risiko in 6 Wochen und ermöglicht Entlassung mit ambulanter Nachsorge. Score ≥7 ist mit >70 % MACE-Risiko assoziiert und erfordert frühes invasives Vorgehen.",
    fr: "Le score HEART (Antécédents, ECG, Âge, Facteurs de risque, Troponine) identifie en toute sécurité les douleurs thoraciques à faible risque aux urgences. Un score ≤3 correspond à un risque d'événement cardiovasculaire majeur <2 % à 6 semaines et permet une sortie avec suivi ambulatoire. Un score ≥7 est associé à un risque >70 % et justifie une évaluation invasive précoce.",
    tr: "HEART skoru (Öykü, EKG, Yaş, Risk faktörleri, Troponin), acil serviste düşük riskli göğüs ağrısı başvurularını güvenle tanımlar. ≤3 skor, 6 haftada <%2 MACE riski taşır ve ayaktan takiple taburculuğu destekler. ≥7 skor, >%70 MACE riski ile ilişkilidir ve erken invazif değerlendirme gerektirir.",
  },

  "curb-65": {
    en: "CURB-65 stratifies severity of community-acquired pneumonia using confusion, urea >7 mmol/L, respiratory rate ≥30, blood pressure <90/60 mmHg, and age ≥65. Score 0–1 supports outpatient oral antibiotics; score 2 warrants hospitalisation; score ≥3 indicates severe CAP requiring ICU evaluation. Simpler than PSI/PORT but less granular for very-low-risk stratification in younger patients.",
    ru: "Шкала CURB-65 оценивает тяжесть внебольничной пневмонии по пяти признакам: спутанность сознания, мочевина >7 ммоль/л, ЧДД ≥30, АД <90/60 мм рт.ст., возраст ≥65 лет. Оценка 0–1 — амбулаторное лечение; 2 — госпитализация; ≥3 — тяжёлая пневмония, рассматривается перевод в ОРИТ. Проще PSI, но менее детальна для молодых пациентов.",
    ar: "تُصنف شكالة CURB-65 شدة الالتهاب الرئوي المكتسب من المجتمع بخمسة معايير: الارتباك، اليوريا >7 ملمول/ل، معدل التنفس ≥30، ضغط الدم <90/60، والعمر ≥65. الدرجة 0–1 تدعم العلاج الخارجي؛ الدرجة 2 تستدعي الدخول؛ الدرجة ≥3 تعني التهاباً حاداً يستوجب تقييم العناية المركزة.",
    es: "CURB-65 estratifica la gravedad de la neumonía adquirida en la comunidad: confusión, urea >7 mmol/L, frecuencia respiratoria ≥30, presión arterial <90/60 mmHg y edad ≥65. Puntuación 0–1: antibióticos orales ambulatorios; puntuación 2: hospitalización; ≥3: NAC grave con evaluación de UCI. Más simple que PSI pero menos granular en jóvenes de muy bajo riesgo.",
    de: "CURB-65 stratifiziert die Schwere einer ambulant erworbenen Pneumonie: Verwirrtheit, Harnstoff >7 mmol/l, AF ≥30/min, Blutdruck <90/60 mmHg, Alter ≥65 Jahre. Score 0–1: ambulante orale Antibiotika; Score 2: Hospitalisation; ≥3: schwere Pneumonie, Intensivstation erwägen. Einfacher als PSI, aber weniger differenziert für sehr niedrig-risiko Patienten.",
    fr: "CURB-65 stratifie la sévérité des pneumonies communautaires : confusion, urée >7 mmol/L, FR ≥30/min, PA <90/60 mmHg, âge ≥65 ans. Score 0–1 : antibiothérapie orale ambulatoire ; score 2 : hospitalisation ; ≥3 : pneumonie sévère avec évaluation en réanimation. Plus simple que le score PSI, mais moins discriminant pour les patients jeunes à très faible risque.",
    tr: "CURB-65, toplum kökenli pnömoni şiddetini beş değişkenle katmanlandırır: konfüzyon, üre >7 mmol/L, SS ≥30/dk, KB <90/60 mmHg, yaş ≥65. Skor 0–1: ayaktan oral antibiyotik; skor 2: hastane yatışı; ≥3: YBÜ değerlendirmesi gerektiren ağır pnömoni. PSI'dan daha basit ancak genç hastalarda düşük riskli tabakalandırma için daha az ayrıntılıdır.",
  },

  "qsofa": {
    en: "Quick SOFA is a 3-point bedside screen for patients outside the ICU at risk of poor outcome from suspected infection. Two or more criteria — altered mental status, respiratory rate ≥22/min, systolic BP ≤100 mmHg — predicts in-hospital mortality ≥10% and should trigger urgent reassessment, organ function testing, blood cultures, and early antibiotics. qSOFA is a screening alert, not a diagnostic tool for sepsis.",
    ru: "qSOFA — экспресс-скрининг у постели больного для выявления пациентов вне ОРИТ с риском неблагоприятного исхода при подозрении на инфекцию. Два и более критерия (нарушение сознания, ЧДД ≥22, АД сист. ≤100 мм рт.ст.) предсказывают внутрибольничную летальность ≥10% и требуют срочной переоценки, оценки функции органов, посевов крови и ранних антибиотиков. Это инструмент скрининга, а не диагностики сепсиса.",
    ar: "qSOFA هو فرز سريع بجانب السرير للمرضى خارج العناية المركزة المعرضين لخطر النتائج السيئة بسبب عدوى مشتبه بها. معياران أو أكثر (تغير الوعي، معدل التنفس ≥22/دقيقة، ضغط انقباضي ≤100) تتنبأ بوفيات داخل المستشفى ≥10% وتستدعي إعادة تقييم عاجلة وفحوصات وظائف الأعضاء وزراعات الدم والمضادات الحيوية المبكرة.",
    es: "qSOFA es una pantalla de 3 puntos a la cabecera del paciente para identificar fuera de UCI a pacientes con riesgo de mala evolución por infección sospechada. Dos o más criterios — alteración del estado mental, FR ≥22/min, PA sistólica ≤100 mmHg — predice mortalidad intrahospitalaria ≥10% y debe desencadenar reevaluación urgente, hemocultivos y antibióticos precoces.",
    de: "qSOFA ist ein 3-Punkte-Bettseitenscreen zur Identifikation von Nicht-ITS-Patienten mit Risiko für schlechte Outcomes bei vermuteter Infektion. Zwei oder mehr Kriterien (Bewusstseinsveränderung, AF ≥22/min, systolischer RR ≤100 mmHg) sagen eine Krankenhaussterblichkeit ≥10 % voraus und erfordern dringende Reassessment, Organfunktionstests, Blutkulturen und frühzeitige Antibiotika.",
    fr: "qSOFA est un score de dépistage rapide au lit du patient identifiant hors réanimation les sujets à risque de mauvais pronostic sur infection suspectée. Deux critères ou plus — altération de la conscience, FR ≥22/min, PAS ≤100 mmHg — prédit une mortalité hospitalière ≥10 % et impose une réévaluation urgente, hémocultures et antibiothérapie précoce.",
    tr: "qSOFA, yoğun bakım dışındaki hastalarda şüpheli enfeksiyona bağlı kötü sonuç riski için hızlı yatak başı taramasıdır. İki veya daha fazla kriter — bilinç değişikliği, SS ≥22/dk, sistolik KB ≤100 mmHg — ≥%10 hastane mortalitesini öngörür; acil yeniden değerlendirme, organ fonksiyon testleri, kan kültürleri ve erken antibiyotik gerektirir.",
  },

  "gcs": {
    en: "The Glasgow Coma Scale quantifies consciousness through eye opening (E 1–4), verbal response (V 1–5), and motor response (M 1–6). GCS ≤8 conventionally defines coma and is the standard threshold for considering airway protection. Serial scoring is more informative than a single measurement — a drop of ≥2 points warrants immediate reassessment for reversible causes including hypoglycaemia, opiate overdose, and rising intracranial pressure.",
    ru: "Шкала комы Глазго количественно оценивает уровень сознания по трём параметрам: открывание глаз (E 1–4), речевая реакция (V 1–5), двигательная реакция (M 1–6). ШКГ ≤8 традиционно определяет кому и является стандартным порогом для решения о защите дыхательных путей. Серийная оценка информативнее разовой: снижение на ≥2 балла требует немедленного поиска обратимых причин (гипогликемия, передозировка опиоидов, внутричерепная гипертензия).",
    ar: "تُقيّم مقياس غلاسكو للغيبوبة مستوى الوعي عبر ثلاثة مكونات: فتح العينين (E 1–4)، الاستجابة اللفظية (V 1–5)، والاستجابة الحركية (M 1–6). GCS ≤8 يعرّف الغيبوبة تقليدياً ويُعدّ عتبة قياسية للنظر في حماية مجرى الهواء. القياسات المتكررة أكثر إفادة من قياس واحد؛ انخفاض ≥2 نقطة يستدعي إعادة تقييم عاجلة للأسباب القابلة للعكس.",
    es: "La Escala de Coma de Glasgow cuantifica el nivel de conciencia mediante apertura ocular (E 1–4), respuesta verbal (V 1–5) y respuesta motora (M 1–6). GCS ≤8 define convencionalmente el coma y es el umbral estándar para considerar protección de la vía aérea. La evaluación seriada es más informativa que una medición única — una caída ≥2 puntos requiere reevaluación inmediata por causas reversibles.",
    de: "Die Glasgow Coma Scale quantifiziert das Bewusstsein über Augenöffnung (E 1–4), verbale Antwort (V 1–5) und motorische Reaktion (M 1–6). GCS ≤8 definiert konventionell Koma und ist der Standardschwellenwert für die Erwägung des Atemwegschutzes. Serielle Messungen sind informativer als Einzelwerte — ein Abfall um ≥2 Punkte erfordert sofortiges Reassessment reversibler Ursachen.",
    fr: "L'échelle de Glasgow quantifie le niveau de conscience par l'ouverture des yeux (Y 1–4), la réponse verbale (V 1–5) et la réponse motrice (M 1–6). Un score ≤8 définit le coma et constitue le seuil standard pour envisager la protection des voies aériennes. L'évaluation sériée est plus informative qu'une mesure isolée — une chute de ≥2 points justifie une réévaluation immédiate des causes réversibles.",
    tr: "Glasgow Koma Skalası, göz açma (E 1–4), verbal yanıt (V 1–5) ve motor yanıt (M 1–6) ile bilinç düzeyini sayısal olarak değerlendirir. GKS ≤8 geleneksel olarak komayı tanımlar ve hava yolu koruma kararı için standart eşiktir. Seri ölçümler tek ölçümden daha bilgi vericidir — ≥2 puan düşüş, hipoglisemi, opiyat aşırı dozu ve artan intrakraniyal basınç gibi geri döndürülebilir nedenler için acil yeniden değerlendirme gerektirir.",
  },

  "abcd2": {
    en: "The ABCD² score estimates 2-day stroke risk after a TIA using Age, Blood pressure, Clinical features, Duration, and Diabetes. A score ≥4 is associated with >4% 2-day stroke risk, warranting immediate dual antiplatelet therapy and urgent neurovascular imaging. ABCD² has limitations in distinguishing TIA from mimics; brain and vascular imaging is mandatory in all TIA presentations and should not be delayed by score calculation.",
    ru: "Шкала ABCD² оценивает риск инсульта в течение 2 дней после ТИА по пяти параметрам: возраст, АД, клинические признаки, продолжительность, диабет. Оценка ≥4 связана с >4% риском инсульта за 2 дня, требует немедленной двойной антиагрегантной терапии и срочной нейроваскулярной визуализации. Шкала не позволяет надёжно отличить ТИА от симуляторов; нейровизуализация обязательна.",
    ar: "تُقدّر شكالة ABCD² خطر السكتة الدماغية خلال يومين بعد النوبة الإقفارية العابرة بخمسة عوامل: العمر وضغط الدم والأعراض السريرية والمدة والسكري. الدرجة ≥4 تعني خطراً >4% خلال يومين، مما يستوجب علاجاً مزدوجاً فورياً بمضادات الصفيحات وتصوير وعائياً عصبياً عاجلاً. لا ينبغي تأخير التصوير الدماغي والوعائي لأي نوبة إقفارية عابرة.",
    es: "La escala ABCD² estima el riesgo de ictus a 2 días tras un AIT usando Edad, Presión arterial, Características clínicas, Duración y Diabetes. Puntuación ≥4 se asocia con >4% de riesgo de ictus a 2 días, requiriendo doble antiagregación inmediata e imagen neurovascular urgente. La neuroimagen es obligatoria en todo AIT y no debe retrasarse por el cálculo de la escala.",
    de: "Der ABCD²-Score schätzt das 2-Tages-Schlaganfallrisiko nach einer TIA anhand von Alter, Blutdruck, klinischen Merkmalen, Dauer und Diabetes. Score ≥4 ist mit >4 % 2-Tages-Risiko assoziiert und erfordert sofortige duale Thrombozytenhemmung und dringende neurovaskuläre Bildgebung. Bildgebung ist bei jeder TIA obligatorisch und darf nicht durch die Scoreberechnung verzögert werden.",
    fr: "Le score ABCD² estime le risque d'AVC à 2 jours après un AIT à partir de l'âge, de la pression artérielle, des caractéristiques cliniques, de la durée et du diabète. Un score ≥4 est associé à un risque >4 % à 2 jours et impose une double antiagrégation immédiate et une imagerie neurovasculaire urgente. L'imagerie cérébrale et vasculaire est obligatoire pour tout AIT et ne doit pas être retardée.",
    tr: "ABCD² skoru, Yaş, Kan basıncı, Klinik özellikler, Süre ve Diyabet kullanarak GİA sonrası 2 günlük inme riskini tahmin eder. ≥4 skor, >%4 2 günlük inme riskiyle ilişkilidir; acil çift antiplatelet tedavisi ve nörovasküler görüntüleme gerektirir. Beyin ve vasküler görüntüleme tüm GİA başvurularında zorunludur ve skor hesaplaması nedeniyle geciktirilmemelidir.",
  },

  "child-pugh": {
    en: "The Child-Pugh score classifies hepatic functional reserve in cirrhosis using bilirubin, albumin, INR, ascites severity, and hepatic encephalopathy grade. Class A (5–6 points) indicates well-compensated disease with >95% 1-year survival. Class B (7–9) represents significant impairment. Class C (10–15) carries 35–45% 1-year survival without transplantation. The score guides surgical candidacy, variceal bleeding mortality prediction, and drug dosing in hepatic impairment.",
    ru: "Шкала Чайлд-Пью классифицирует функциональный резерв печени при циррозе по уровням билирубина, альбумина, МНО, степени асцита и гепатической энцефалопатии. Класс A (5–6 баллов) — компенсированный цирроз, выживаемость >95% за 1 год. Класс B (7–9) — значительное снижение функции. Класс C (10–15) — 35–45% однолетняя выживаемость без трансплантации. Шкала определяет операбельность и дозирование препаратов.",
    ar: "تُصنف شكالة Child-Pugh الاحتياطي الوظيفي للكبد في التليف باستخدام البيليروبين والألبومين وINR وشدة الاستسقاء ودرجة الاعتلال الدماغي. الفئة A (5–6 نقاط): مرض معوّض بجيد مع بقاء >95% لسنة. الفئة B (7–9): ضعف وظيفي كبير. الفئة C (10–15): بقاء 35–45% لسنة دون زرع. تُوجّه الشكالة أهلية الجراحة وجرعات الأدوية.",
    es: "La escala Child-Pugh clasifica la reserva funcional hepática en cirrosis usando bilirrubina, albúmina, INR, gravedad de ascitis y grado de encefalopatía hepática. Clase A (5–6 puntos): enfermedad bien compensada con supervivencia >95% al año. Clase B (7–9): deterioro funcional significativo. Clase C (10–15): supervivencia 35–45% al año sin trasplante. Orienta la candidatura quirúrgica y el ajuste de dosis.",
    de: "Der Child-Pugh-Score klassifiziert die hepatische Funktionsreserve bei Zirrhose anhand von Bilirubin, Albumin, INR, Aszitesschwere und hepatischer Enzephalopathie. Klasse A (5–6 Punkte): gut kompensierte Erkrankung, >95 % 1-Jahres-Überleben. Klasse B (7–9): erhebliche Funktionseinschränkung. Klasse C (10–15): 35–45 % 1-Jahres-Überleben ohne Transplantation.",
    fr: "Le score de Child-Pugh classe la réserve fonctionnelle hépatique dans la cirrhose à partir de la bilirubine, de l'albumine, de l'INR, de la sévérité de l'ascite et du grade d'encéphalopathie. Classe A (5–6) : maladie bien compensée, survie >95 % à 1 an. Classe B (7–9) : altération fonctionnelle significative. Classe C (10–15) : survie 35–45 % à 1 an sans transplantation.",
    tr: "Child-Pugh skoru, bilirubin, albumin, INR, asit şiddeti ve hepatik ensefalopati derecesini kullanarak sirozda karaciğer fonksiyonel rezervini sınıflandırır. Sınıf A (5–6): >%95 1 yıllık sağkalım ile iyi kompanse hastalık. Sınıf B (7–9): belirgin fonksiyonel bozulma. Sınıf C (10–15): nakil olmaksızın %35–45 1 yıllık sağkalım. Cerrahi adaylık ve ilaç dozlama kararlarını yönlendirir.",
  },

  "wells-pe": {
    en: "The Wells PE score stratifies pre-test probability of pulmonary embolism in symptomatic patients. A score ≤1 (low probability) paired with a negative high-sensitivity D-dimer effectively excludes PE without imaging, avoiding CT radiation. A score ≥7 (high probability) should prompt direct CT pulmonary angiography without awaiting D-dimer. The score was validated in the landmark 2001 Wells trial and is endorsed by ESC and ACEP guidelines.",
    ru: "Шкала Уэллса стратифицирует предтестовую вероятность ТЭЛА у симптомных пациентов. При ≤1 балле (низкая вероятность) и отрицательном D-димере высокой чувствительности ТЭЛА исключается без визуализации. При ≥7 баллах (высокая вероятность) показана немедленная КТ-ангиография лёгочных артерий без ожидания D-димера. Шкала валидирована в исследовании Wells 2001 и рекомендована руководствами ESC и ACEP.",
    ar: "تُصنّف شكالة ويلز للانسداد الرئوي الاحتمالية قبل الاختبار للانسداد الرئوي في المرضى الذين تظهر عليهم الأعراض. نتيجة ≤1 (احتمالية منخفضة) مع D-dimer سلبي تستبعد الانسداد دون تصوير. نتيجة ≥7 (احتمالية عالية) تستدعي تصوير الأوعية الرئوية بالتصوير المقطعي فوراً. اعتُمدت الشكالة في دراسة ويلز 2001 وأوصت بها إرشادات ESC وACEP.",
    es: "El score de Wells para TEP estratifica la probabilidad pre-test de tromboembolia pulmonar en pacientes sintomáticos. Una puntuación ≤1 (probabilidad baja) con D-dímero negativo de alta sensibilidad descarta la TEP sin necesidad de imagen. Con ≥7 puntos (probabilidad alta) debe procederse directamente a angio-TC sin esperar el D-dímero. Validado en el ensayo Wells 2001 y respaldado por guías ESC y ACEP.",
    de: "Das Wells-PE-Schema stratifiziert die Vortestwahrscheinlichkeit einer Lungenembolie bei symptomatischen Patienten. Bei ≤1 Punkt (niedrige Wahrscheinlichkeit) und negativem hochsensitivem D-Dimer ist eine LE ohne Bildgebung ausgeschlossen. Bei ≥7 Punkten (hohe Wahrscheinlichkeit) ist eine direkte CT-PA ohne D-Dimer-Bestimmung indiziert. Validiert in der Wells-Studie 2001, empfohlen von ESC und ACEP.",
    fr: "Le score de Wells pour l'EP stratifie la probabilité pré-test d'embolie pulmonaire chez les patients symptomatiques. Un score ≤1 (probabilité faible) avec D-dimères négatifs hautement sensibles exclut l'EP sans imagerie. Un score ≥7 (probabilité élevée) justifie un angioscanner pulmonaire direct. Validé dans l'essai Wells 2001, recommandé par les guidelines ESC et ACEP.",
    tr: "Wells PE skoru, semptomatik hastalarda pulmoner emboli ön test olasılığını sınıflandırır. ≤1 puan (düşük olasılık) ve yüksek duyarlılıklı negatif D-dimer ile görüntüleme olmaksızın PE dışlanabilir. ≥7 puan (yüksek olasılık) durumunda D-dimer beklenmeksizin doğrudan BT pulmoner anjiyografi yapılmalıdır. 2001 Wells çalışmasında valide edilmiş, ESC ve ACEP kılavuzlarınca önerilmektedir.",
  },

  "sofa": {
    en: "The SOFA (Sequential Organ Failure Assessment) score quantifies organ dysfunction across 6 systems — respiratory, coagulation, liver, cardiovascular, CNS, and renal. Each system is scored 0–4, yielding a total of 0–24. An initial SOFA ≥2 is the diagnostic criterion for sepsis-associated organ dysfunction (Sepsis-3 definition). A score increase of ≥2 during ICU stay predicts in-hospital mortality above 10%. Serial reassessment guides escalation and de-escalation of organ support.",
    ru: "Шкала SOFA (Последовательная оценка органной недостаточности) количественно оценивает дисфункцию 6 органных систем: дыхательной, свёртывающей, печёночной, сердечно-сосудистой, ЦНС и почечной. Каждая система оценивается в 0–4 балла, итого 0–24. Исходный SOFA ≥2 является диагностическим критерием сепсис-ассоциированной органной дисфункции (Sepsis-3). Прирост ≥2 баллов за госпитализацию предсказывает летальность >10%.",
    ar: "تُقيّم شكالة SOFA (التقييم التسلسلي لفشل الأعضاء) خلل وظائف 6 أجهزة: التنفسي والتخثر والكبد والقلبي الوعائي والجهاز العصبي المركزي والكلوي. يُسجَّل كل جهاز من 0 إلى 4، بمجموع 0–24. SOFA الأولي ≥2 هو معيار تشخيص خلل الأعضاء المرتبط بالإنتان (تعريف Sepsis-3). يرتبط ارتفاع ≥2 نقطة خلال الإقامة في المستشفى بوفيات >10%.",
    es: "El score SOFA cuantifica la disfunción orgánica en 6 sistemas: respiratorio, coagulación, hígado, cardiovascular, SNC y renal. Cada sistema se puntúa de 0 a 4, con un total de 0–24. Un SOFA inicial ≥2 es el criterio diagnóstico de disfunción orgánica asociada a sepsis (definición Sepsis-3). Un incremento ≥2 puntos predice mortalidad hospitalaria >10%. La reevaluación seriada guía la escalada y desescalada del soporte orgánico.",
    de: "Der SOFA-Score quantifiziert Organdysfunktion in 6 Systemen: Atmung, Gerinnung, Leber, Herz-Kreislauf, ZNS und Niere. Jedes System wird mit 0–4 bewertet (Gesamt 0–24). Ein initialer SOFA ≥2 ist das diagnostische Kriterium für sepsisassoziierte Organdysfunktion (Sepsis-3-Definition). Ein Anstieg um ≥2 Punkte im Verlauf prognostiziert eine Krankenhaussterblichkeit >10%.",
    fr: "Le score SOFA quantifie la défaillance de 6 organes : respiratoire, coagulation, foie, cardiovasculaire, SNC et rénal. Chaque système est coté de 0 à 4 (total 0–24). Un SOFA initial ≥2 constitue le critère diagnostique de la dysfonction d'organe associée au sepsis (définition Sepsis-3). Une augmentation ≥2 points prédit une mortalité hospitalière >10%.",
    tr: "SOFA skoru, 6 organ sistemindeki fonksiyon bozukluğunu nicelleştirir: solunum, koagülasyon, karaciğer, kardiyovasküler, MSS ve renal. Her sistem 0–4 puan alır (toplam 0–24). Başlangıç SOFA ≥2, sepsisle ilişkili organ disfonksiyonunun tanı kriteridir (Sepsis-3 tanımı). Hastane içi ≥2 puanlık artış, %10'un üzerinde mortalite öngörür.",
  },

  "pregnancy-due-date": {
    en: "The estimated due date (EDD) is calculated using Naegele's rule: add 280 days (40 weeks) to the first day of the last menstrual period (LMP). This assumes a regular 28-day cycle with ovulation on day 14. Only about 5% of births occur on the exact EDD; a normal term delivery is 37–42 weeks. Gestational age established by first-trimester ultrasound (crown-rump length) is more accurate than LMP dating, particularly when cycles are irregular.",
    ru: "Предполагаемая дата родов (ПДР) рассчитывается по правилу Негеле: добавить 280 дней (40 недель) к первому дню последней менструации (ПМ). Правило предполагает регулярный 28-дневный цикл с овуляцией на 14-й день. Только ~5% родов происходят в точно рассчитанный день. Нормальные роды: 37–42 недели. УЗИ первого триместра (КТР) точнее ПМ, особенно при нерегулярном цикле.",
    ar: "يُحسب التاريخ المتوقع للولادة بقاعدة نيغيل: يُضاف 280 يوماً (40 أسبوعاً) إلى اليوم الأول من آخر دورة شهرية. تفترض القاعدة دورة منتظمة مدتها 28 يوماً مع الإباضة في اليوم 14. يُولد ~5% فقط في التاريخ المحدد بالضبط، والولادة الطبيعية بين 37–42 أسبوعاً. الموجات فوق الصوتية للثلاثي الأول (طول الجنين من الرأس للمؤخرة) أدق من حساب تاريخ الدورة.",
    es: "La fecha probable de parto (FPP) se calcula con la regla de Naegele: sumar 280 días (40 semanas) al primer día de la última menstruación (FUR). Asume un ciclo regular de 28 días con ovulación en el día 14. Solo ~5% de los partos ocurren exactamente en la FPP; el parto a término normal es 37–42 semanas. La ecografía del primer trimestre (longitud cráneo-rabadilla) es más precisa que la FUR, especialmente con ciclos irregulares.",
    de: "Der voraussichtliche Geburtstermin (VGT) wird nach der Naegele-Regel berechnet: 280 Tage (40 Wochen) zum ersten Tag der letzten Menstruation (LMP) addieren. Voraussetzung ist ein regelmäßiger 28-Tage-Zyklus mit Ovulation am Tag 14. Nur ~5 % der Geburten erfolgen exakt am errechneten Termin. Eine normale Termingeburt liegt bei 37–42 Wochen. Die Erstrimester-Sonographie (Scheitel-Steiß-Länge) ist präziser als die LMP-Datierung.",
    fr: "La date prévue d'accouchement (DPA) est calculée par la règle de Naegele : ajouter 280 jours (40 semaines) au premier jour des dernières règles (DDR). La règle suppose un cycle régulier de 28 jours avec ovulation au jour 14. Seulement ~5 % des naissances surviennent exactement à la DPA ; un accouchement à terme normal se situe entre 37 et 42 semaines. L'échographie du premier trimestre (longueur crânio-caudale) est plus précise que la datation par les DDR.",
    tr: "Tahmini doğum tarihi (TDT), Naegele kuralıyla hesaplanır: son adet döneminin (SAT) ilk gününe 280 gün (40 hafta) eklenir. Kural, 14. günde ovülasyonlu düzenli 28 günlük döngüyü varsayar. Doğumların yalnızca ~%5'i tam TDT'de gerçekleşir; normal doğum 37–42. haftalardadır. Birinci trimester ultrasonografisi (baş-popo uzunluğu), özellikle düzensiz döngülerde SAT'a göre daha doğrudur.",
  },

  "ideal-body-weight": {
    en: "The Devine formula (1974) estimates ideal body weight (IBW) as 50 kg (men) or 45.5 kg (women) for a height of 5 feet, adding 2.3 kg per additional inch. IBW is used as the reference weight for drug dosing — particularly for aminoglycosides, vancomycin, neuromuscular blockers, and ventilator tidal volume calculation (6 mL/kg IBW). When actual body weight exceeds 120% of IBW, the adjusted body weight (ABW = IBW + 0.4 × [actual − IBW]) is used to account for partial drug distribution into adipose tissue.",
    ru: "Формула Девина (1974) оценивает идеальный вес тела (ИМТ): 50 кг (мужчины) или 45,5 кг (женщины) при росте 152,4 см, плюс 2,3 кг на каждый дополнительный дюйм. ИМТ используется как референсный вес при дозировании препаратов — аминогликозидов, ванкомицина, миорелаксантов и при расчёте дыхательного объёма ИВЛ (6 мл/кг ИМТ). При фактическом весе >120% ИМТ применяется скорректированный вес (СВ = ИМТ + 0,4 × [факт. − ИМТ]).",
    ar: "تُقدّر معادلة ديفين (1974) الوزن المثالي للجسم بـ 50 كغ (رجال) أو 45.5 كغ (نساء) عند طول 152.4 سم، يُضاف 2.3 كغ لكل بوصة إضافية. يُستخدم الوزن المثالي مرجعاً لجرعات الأدوية، لا سيما الأمينوغليكوزيدات والفانكومايسين ومرخيات العضلات والحجم المدّي للتنفس الاصطناعي (6 مل/كغ). عند تجاوز الوزن الفعلي 120% من المثالي، يُستخدم الوزن المعدّل = الوزن المثالي + 0.4 × (الفعلي − المثالي).",
    es: "La fórmula de Devine (1974) estima el peso corporal ideal (IBW) como 50 kg (hombres) o 45,5 kg (mujeres) para una talla de 152,4 cm, añadiendo 2,3 kg por cada pulgada adicional. El IBW se utiliza como peso de referencia para dosificación farmacológica — especialmente aminoglucósidos, vancomicina, bloqueantes neuromusculares y cálculo del volumen tidal en ventilación (6 mL/kg IBW). Si el peso real supera el 120% del IBW, se usa el peso ajustado: ABW = IBW + 0,4 × (real − IBW).",
    de: "Die Devine-Formel (1974) schätzt das Idealgewicht (IBW) auf 50 kg (Männer) bzw. 45,5 kg (Frauen) bei 152,4 cm Körpergröße, zuzüglich 2,3 kg pro zusätzlichem Zoll. IBW dient als Referenzgewicht für die Medikamentendosierung — insbesondere Aminoglykoside, Vancomycin, Muskelrelaxanzien und Beatmungs-Tidalvolumen (6 ml/kg IBW). Bei Ist-Gewicht >120 % IBW gilt das angepasste Gewicht: ABW = IBW + 0,4 × (Ist − IBW).",
    fr: "La formule de Devine (1974) estime le poids idéal (IBW) à 50 kg (hommes) ou 45,5 kg (femmes) pour 152,4 cm, en ajoutant 2,3 kg par pouce supplémentaire. L'IBW est le poids de référence pour le dosage des médicaments — aminosides, vancomycine, curares et calcul du volume courant ventilatoire (6 mL/kg IBW). Si le poids réel dépasse 120 % de l'IBW, on utilise le poids ajusté : ABW = IBW + 0,4 × (réel − IBW).",
    tr: "Devine formülü (1974), ideal vücut ağırlığını (IBW) 152,4 cm için 50 kg (erkek) veya 45,5 kg (kadın) olarak tahmin eder; her ek inç için 2,3 kg eklenir. IBW, ilaç dozajında referans ağırlık olarak kullanılır — aminoglikozidler, vankomisin, nöromüsküler blokerler ve mekanik ventilasyon tidal hacim hesabı (6 mL/kg IBW). Gerçek ağırlık IBW'nin %120'sini aşarsa: ABW = IBW + 0,4 × (gerçek − IBW).",
  },

  "target-heart-rate": {
    en: "The Karvonen method calculates target heart rate using the heart rate reserve (HRR = HRmax − resting HR), producing training zones that are personalised to cardiovascular fitness level. The simplified estimate of HRmax is 220 minus age. Zone 1 (50–60% HRR) is used for warm-up and active recovery. Zone 2 (60–70%) optimises fat oxidation. Zone 3 (70–80%) improves aerobic capacity (VO2max). Zone 4 (80–90%) raises the anaerobic threshold for high-intensity training. For patients with cardiovascular disease, target zones should be confirmed with a stress test.",
    ru: "Метод Карвонена рассчитывает целевую ЧСС, используя резерв сердечного ритма (РСР = ЧСС макс − ЧСС покоя), создавая персонализированные тренировочные зоны. Упрощённая оценка ЧСС макс: 220 − возраст. Зона 1 (50–60% РСР) — разминка и восстановление. Зона 2 (60–70%) — оптимальное окисление жиров. Зона 3 (70–80%) — развитие аэробных способностей (МПК). Зона 4 (80–90%) — повышение анаэробного порога. При сердечно-сосудистых заболеваниях зоны уточняются нагрузочным тестом.",
    ar: "تحسب طريقة كارفونن معدل ضربات القلب المستهدف باستخدام احتياطي معدل ضربات القلب (HRR = الحد الأقصى − الراحة)، لإنشاء مناطق تدريب مخصصة لمستوى اللياقة القلبية الوعائية. التقدير المبسّط لأقصى معدل: 220 ناقص العمر. المنطقة 1 (50–60%): الإحماء والتعافي. المنطقة 2 (60–70%): تحسين أكسدة الدهون. المنطقة 3 (70–80%): رفع القدرة الهوائية. المنطقة 4 (80–90%): رفع العتبة اللاهوائية. لمرضى القلب، تُحدَّد المناطق باختبار الجهد.",
    es: "El método de Karvonen calcula la frecuencia cardíaca objetivo usando la reserva de FC (FCR = FCmáx − FC reposo), generando zonas de entrenamiento personalizadas según la condición cardiovascular. La estimación simplificada de FCmáx es 220 menos la edad. Zona 1 (50–60% FCR): calentamiento y recuperación activa. Zona 2 (60–70%): optimiza la oxidación de grasas. Zona 3 (70–80%): mejora la capacidad aeróbica (VO2máx). Zona 4 (80–90%): eleva el umbral anaeróbico. En pacientes con cardiopatía, las zonas deben confirmarse con prueba de esfuerzo.",
    de: "Die Karvonen-Methode berechnet die Zielherzfrequenz anhand der Herzfrequenzreserve (HFR = HFmax − Ruhe-HF) und erstellt individuelle Trainingszonen. HFmax-Schätzung: 220 minus Alter. Zone 1 (50–60 %): Aufwärmen/aktive Erholung. Zone 2 (60–70 %): Fettoxidation. Zone 3 (70–80 %): aerobe Kapazität (VO2max). Zone 4 (80–90 %): anaerobe Schwelle. Bei kardiovaskulären Erkrankungen sollten die Zonen durch Belastungstest bestätigt werden.",
    fr: "La méthode Karvonen calcule la fréquence cardiaque cible à partir de la réserve de FC (RCF = FCmax − FC repos), produisant des zones d'entraînement personnalisées. Estimation simplifiée de FCmax : 220 − âge. Zone 1 (50–60 % RCF) : échauffement et récupération active. Zone 2 (60–70 %) : oxydation des graisses. Zone 3 (70–80 %) : capacité aérobie (VO2max). Zone 4 (80–90 %) : seuil anaérobie. Pour les cardiaques, les zones doivent être confirmées par épreuve d'effort.",
    tr: "Karvonen yöntemi, kalp hızı rezervini (KHR = KH maks − dinlenme KH) kullanarak hedef kalp hızını hesaplar ve kardiyovasküler kondisyon düzeyine göre kişiselleştirilmiş antrenman bölgeleri oluşturur. Basit KH maks tahmini: 220 eksi yaş. Bölge 1 (50–60%): ısınma ve aktif iyileşme. Bölge 2 (60–70%): yağ oksidasyonu. Bölge 3 (70–80%): aerobik kapasite (VO2maks). Bölge 4 (80–90%): anaerobik eşik. Kardiyovasküler hastalığı olanlarda bölgeler egzersiz testi ile doğrulanmalıdır.",
  },

  "daily-calories": {
    en: "The Mifflin-St Jeor equation (1990) is the most accurate BMR formula for the general population, outperforming the older Harris-Benedict equation in multiple validation studies. BMR represents calories burned at complete rest. TDEE multiplies BMR by an activity factor (1.2–1.9) to estimate total daily energy expenditure including exercise, thermogenesis, and daily activity. A deficit of 500 kcal/day produces approximately 0.5 kg weight loss per week. For clinical use in obesity management, indirect calorimetry remains the gold standard.",
    ru: "Уравнение Миффлина-Сент-Жора (1990) — наиболее точная формула BMR для широкой популяции, превосходящая устаревшую формулу Харриса-Бенедикта в нескольких валидационных исследованиях. BMR — калории, сжигаемые в состоянии полного покоя. TDEE умножает BMR на коэффициент активности (1,2–1,9) для оценки суточных энергозатрат. Дефицит 500 ккал/сутки обеспечивает снижение веса ~0,5 кг в неделю. В клинической практике лечения ожирения золотым стандартом остаётся непрямая калориметрия.",
    ar: "معادلة ميفلين-سانت جيور (1990) هي أدق معادلات BMR للسكان العامين، وتتفوق على معادلة هاريس-بنيديكت القديمة في دراسات التحقق. BMR هو السعرات المحروقة في حالة الراحة التامة. يضرب TDEE قيمة BMR في معامل النشاط (1.2–1.9) لتقدير إجمالي الطاقة اليومية. عجز 500 سعرة/يوم يُنتج خسارة وزن ~0.5 كغ/أسبوع. في الإدارة السريرية للسمنة، يبقى قياس التمثيل الغذائي غير المباشر المعيار الذهبي.",
    es: "La ecuación de Mifflin-St Jeor (1990) es la fórmula de TMB más precisa para la población general, superando a la antigua ecuación de Harris-Benedict en múltiples estudios de validación. La TMB representa las calorías quemadas en reposo absoluto. El TDEE multiplica la TMB por un factor de actividad (1,2–1,9) para estimar el gasto energético diario total. Un déficit de 500 kcal/día produce aproximadamente 0,5 kg de pérdida de peso por semana. En el manejo clínico de la obesidad, la calorimetría indirecta sigue siendo el estándar de oro.",
    de: "Die Mifflin-St-Jeor-Gleichung (1990) ist die genaueste BMR-Formel für die Allgemeinbevölkerung und übertrifft die ältere Harris-Benedict-Gleichung in mehreren Validierungsstudien. Der BMR gibt den Kalorienverbrauch in völliger Ruhe an. Der TDEE multipliziert den BMR mit einem Aktivitätsfaktor (1,2–1,9) zur Schätzung des täglichen Gesamtenergieverbrauchs. Ein Defizit von 500 kcal/Tag entspricht ca. 0,5 kg Gewichtsverlust pro Woche. In der klinischen Adipositastherapie bleibt die indirekte Kalorimetrie der Goldstandard.",
    fr: "L'équation de Mifflin-St Jeor (1990) est la formule de BMR la plus précise pour la population générale, surpassant la formule de Harris-Benedict dans plusieurs études de validation. Le BMR représente les calories brûlées au repos complet. Le TDEE multiplie le BMR par un facteur d'activité (1,2–1,9) pour estimer la dépense énergétique totale quotidienne. Un déficit de 500 kcal/j entraîne une perte de poids d'environ 0,5 kg/semaine. En gestion clinique de l'obésité, la calorimétrie indirecte reste le gold standard.",
    tr: "Mifflin-St Jeor denklemi (1990), genel popülasyon için en doğru BMR formülüdür ve birden fazla validasyon çalışmasında eski Harris-Benedict denklemini geride bırakır. BMR, tam dinlenme halinde yakılan kalorileri temsil eder. TDEE, toplam günlük enerji harcamasını tahmin etmek için BMR'yi aktivite faktörüyle (1,2–1,9) çarpar. 500 kcal/gün açığı haftada yaklaşık 0,5 kg kilo kaybı sağlar. Obezite yönetiminde klinik altın standart dolaylı kalorimetredir.",
  },

};
