import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { cookies } from "next/headers";
import { getCategoryLabel } from "@/lib/categories";
import { ArticleNav } from "@/components/layout/ArticleNav";
import { CommentsBlock } from "@/components/ui/CommentsBlock";
import { ReportArticleButton } from "@/components/ui/ReportArticleButton";

export const dynamic = "force-dynamic";

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? "https://medmind.pro";
const API_URL = process.env.INTERNAL_API_URL ?? process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000/api/v1";
const SUPPORTED = ["en", "ru", "ar", "tr", "de", "fr", "es"];

type Lang = "en" | "ru" | "ar" | "es" | "de" | "fr" | "tr";

interface NewsDetail {
  id: string; slug: string; source_name: string; source_url: string;
  source_doi: string | null; title: string; summary: string;
  category: string; tags: string[] | null;
  original_published_at: string | null; fetched_at: string;
  author_display_name: string | null;
}

interface NewsPreview {
  id: string; slug: string; source_name: string;
  title: string; summary_excerpt: string; category: string;
  original_published_at: string | null; fetched_at: string;
}

interface RelatedArticle { slug: string; title: string; excerpt: string; category: string; }

const SOURCE_BADGE: Record<string, string> = {
  "WHO":     "bg-blue-100 text-blue-800",
  "medRxiv": "bg-purple-100 text-purple-800",
};

const UI: Record<Lang, Record<string, string>> = {
  en: { back: "← All News", source: "Source", doi: "DOI", pub_date: "Originally published",
        fetched: "Added to MedMind", disclaimer_label: "AI Summary",
        disclaimer: "This summary was generated by AI from publicly available content. Always consult the original publication and a qualified professional before clinical decision-making.",
        read_original: "Read original publication →", preprint: "Preprint — not peer-reviewed",
        related_articles: "Related articles on this topic", more_in_category: "More news in this category",
        all_news: "All news →", read_article: "Read article", read_more: "Read more",
        all_medical_news: "All medical news" },
  ru: { back: "← Все новости", source: "Источник", doi: "DOI", pub_date: "Первоначально опубликовано",
        fetched: "Добавлено в MedMind", disclaimer_label: "AI-реферат",
        disclaimer: "Этот реферат создан ИИ на основе публично доступных материалов. Всегда обращайтесь к оригинальной публикации и квалифицированному специалисту.",
        read_original: "Читать оригинал →", preprint: "Препринт — не рецензировался",
        related_articles: "Статьи по теме", more_in_category: "Ещё новости в этой категории",
        all_news: "Все новости →", read_article: "Читать статью", read_more: "Читать далее",
        all_medical_news: "Все медицинские новости" },
  ar: { back: "← جميع الأخبار", source: "المصدر", doi: "DOI", pub_date: "تاريخ النشر الأصلي",
        fetched: "أضيف إلى MedMind", disclaimer_label: "ملخص ذكاء اصطناعي",
        disclaimer: "هذا الملخص مُولَّد بالذكاء الاصطناعي من محتوى متاح للعموم. استشر دائماً المنشور الأصلي ومختصاً مؤهلاً.",
        read_original: "قراءة المنشور الأصلي →", preprint: "طبعة مسبقة — لم تُراجَع",
        related_articles: "مقالات ذات صلة", more_in_category: "المزيد من الأخبار في هذه الفئة",
        all_news: "جميع الأخبار →", read_article: "اقرأ المقالة", read_more: "اقرأ المزيد",
        all_medical_news: "جميع الأخبار الطبية" },
  es: { back: "← Todas las noticias", source: "Fuente", doi: "DOI", pub_date: "Publicado originalmente",
        fetched: "Añadido a MedMind", disclaimer_label: "Resumen IA",
        disclaimer: "Este resumen fue generado por IA a partir de contenido públicamente disponible. Consulte siempre la publicación original y a un profesional.",
        read_original: "Leer publicación original →", preprint: "Preimpresión — no revisada por pares",
        related_articles: "Artículos relacionados", more_in_category: "Más noticias en esta categoría",
        all_news: "Todas las noticias →", read_article: "Leer artículo", read_more: "Leer más",
        all_medical_news: "Todas las noticias médicas" },
  de: { back: "← Alle Nachrichten", source: "Quelle", doi: "DOI", pub_date: "Ursprünglich veröffentlicht",
        fetched: "Zu MedMind hinzugefügt", disclaimer_label: "KI-Zusammenfassung",
        disclaimer: "Diese Zusammenfassung wurde von KI aus öffentlich verfügbaren Inhalten erstellt. Konsultieren Sie stets die Originalveröffentlichung und einen Fachmann.",
        read_original: "Originalpublikation lesen →", preprint: "Preprint — nicht begutachtet",
        related_articles: "Verwandte Artikel", more_in_category: "Weitere Nachrichten in dieser Kategorie",
        all_news: "Alle Nachrichten →", read_article: "Artikel lesen", read_more: "Weiterlesen",
        all_medical_news: "Alle medizinischen Nachrichten" },
  fr: { back: "← Toutes les actualités", source: "Source", doi: "DOI", pub_date: "Publié originalement",
        fetched: "Ajouté à MedMind", disclaimer_label: "Résumé IA",
        disclaimer: "Ce résumé a été généré par IA à partir de contenu public. Consultez toujours la publication originale et un professionnel.",
        read_original: "Lire la publication originale →", preprint: "Préimpression — non évaluée",
        related_articles: "Articles connexes", more_in_category: "Plus d'actualités dans cette catégorie",
        all_news: "Toutes les actualités →", read_article: "Lire l'article", read_more: "Lire la suite",
        all_medical_news: "Toutes les actualités médicales" },
  tr: { back: "← Tüm Haberler", source: "Kaynak", doi: "DOI", pub_date: "Orijinal yayın tarihi",
        fetched: "MedMind'a eklendi", disclaimer_label: "YZ Özeti",
        disclaimer: "Bu özet, kamuya açık içeriklerden YZ tarafından oluşturulmuştur. Her zaman orijinal yayına ve uzman bir profesyonele danışın.",
        read_original: "Orijinal yayını oku →", preprint: "Ön baskı — hakemlik yapılmadı",
        related_articles: "İlgili makaleler", more_in_category: "Bu kategoride daha fazla haber",
        all_news: "Tüm haberler →", read_article: "Makaleyi oku", read_more: "Devamını oku",
        all_medical_news: "Tüm tıp haberleri" },
};

function fmtDate(s: string | null, lang: Lang): string {
  if (!s) return "";
  try {
    return new Intl.DateTimeFormat(lang, { year: "numeric", month: "long", day: "numeric" }).format(new Date(s));
  } catch { return s.split("T")[0]; }
}

function fmtDateShort(s: string | null, lang: Lang): string {
  if (!s) return "";
  try {
    return new Intl.DateTimeFormat(lang, { month: "short", day: "numeric" }).format(new Date(s));
  } catch { return s.split("T")[0]; }
}

async function fetchNews(slug: string, locale: string): Promise<NewsDetail | null> {
  try {
    const res = await fetch(`${API_URL}/news/${slug}?locale=${locale}`, { cache: "no-store" });
    if (res.status === 404) return null;
    if (!res.ok) return null;
    return await res.json();
  } catch { return null; }
}

async function fetchRelatedArticles(slug: string, locale: string): Promise<RelatedArticle[]> {
  try {
    const res = await fetch(`${API_URL}/news/${slug}/related-articles?locale=${locale}`, { cache: "no-store" });
    if (!res.ok) return [];
    const data = await res.json();
    return Array.isArray(data) ? data : [];
  } catch { return []; }
}

async function fetchMoreNews(category: string, locale: string, currentSlug: string): Promise<NewsPreview[]> {
  try {
    const res = await fetch(`${API_URL}/news?category=${category}&locale=${locale}&limit=7`, { cache: "no-store" });
    if (!res.ok) return [];
    const data = await res.json();
    const items: NewsPreview[] = Array.isArray(data) ? data : (data.items ?? []);
    return items.filter(n => n.slug !== currentSlug).slice(0, 4);
  } catch { return []; }
}

export async function generateMetadata({
  params,
  searchParams,
}: {
  params: { slug: string };
  searchParams?: { lang?: string; locale?: string };
}): Promise<Metadata> {
  const cookieLocale = cookies().get("medmind_locale")?.value;
  // Middleware rewrites /ar/news/slug → /news/slug?lang=ar; also support ?locale=
  const rawLocale = searchParams?.lang || searchParams?.locale || cookieLocale;
  const locale = rawLocale && SUPPORTED.includes(rawLocale) ? rawLocale : "en";
  const article = await fetchNews(params.slug, locale);
  if (!article) return { title: "News not found" };

  const enUrl = `${SITE_URL}/news/${article.slug}`;
  const canonical = locale !== "en" ? `${SITE_URL}/${locale}/news/${article.slug}` : enUrl;
  return {
    title: article.title,
    description: article.summary.slice(0, 200),
    alternates: {
      canonical,
      languages: {
        "x-default": enUrl,
        en: enUrl,
        ...(SUPPORTED.filter((l) => l !== "en").reduce((acc, l) => ({
          ...acc,
          [l]: `${SITE_URL}/${l}/news/${article.slug}`,
        }), {} as Record<string, string>)),
      },
    },
    openGraph: {
      title: article.title,
      description: article.summary.slice(0, 200),
      url: canonical,
      siteName: "MedMind AI",
      type: "article",
      publishedTime: article.original_published_at ?? undefined,
    },
  };
}

export default async function NewsDetailPage({
  params,
  searchParams,
}: {
  params: { slug: string };
  searchParams?: { lang?: string; locale?: string };
}) {
  const cookieLocale = cookies().get("medmind_locale")?.value;
  const rawLocale = searchParams?.lang || searchParams?.locale || cookieLocale;
  const lang = (rawLocale && SUPPORTED.includes(rawLocale) ? rawLocale : "en") as Lang;
  const ui = UI[lang] ?? UI.en;
  const slug = params.slug;

  const [article, related] = await Promise.all([
    fetchNews(slug, lang),
    fetchRelatedArticles(slug, lang),
  ]);

  if (!article) notFound();

  const moreNews = await fetchMoreNews(article.category, lang, slug);

  const isPreprint = article.source_name === "medRxiv";
  const isTeacher  = article.author_display_name != null &&
    !["WHO", "PubMed", "medRxiv"].includes(article.source_name ?? "");

  const breadcrumbSchema = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      { "@type": "ListItem", position: 1, name: "Home", item: SITE_URL },
      { "@type": "ListItem", position: 2, name: "News", item: `${SITE_URL}/news` },
      { "@type": "ListItem", position: 3, name: article.title, item: `${SITE_URL}/news/${slug}` },
    ],
  };

  return (
    <div className="min-h-screen bg-bg" dir={lang === "ar" ? "rtl" : "ltr"}>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }}
      />

      <ArticleNav />

      <main className="max-w-4xl mx-auto px-4 sm:px-6 py-10">
        <Link
          href="/news"
          className="inline-flex items-center gap-1.5 font-syne font-semibold text-sm text-ink-2 hover:text-ink transition-colors mb-8"
        >
          {ui.back}
        </Link>

        <article>
          {/* Category + badges */}
          <div className="flex flex-wrap items-center gap-2 mb-4">
            <span className="text-xs font-syne font-bold text-red uppercase tracking-wider">
              {getCategoryLabel(article.category, lang)}
            </span>
            <span className={`text-xs font-syne font-bold px-2 py-0.5 rounded-full ${SOURCE_BADGE[article.source_name] ?? "bg-amber-100 text-amber-800"}`}>
              {article.source_name}
            </span>
            {isPreprint && (
              <span className="text-xs font-syne px-2 py-0.5 rounded-full bg-yellow-100 text-yellow-800">
                ⚠ {ui.preprint}
              </span>
            )}
          </div>

          {/* H1 — always in initial HTML for SEO */}
          <h1 className="font-syne font-extrabold text-2xl sm:text-3xl lg:text-4xl text-ink leading-tight mb-6">
            {article.title}
          </h1>

          {/* Meta strip */}
          <div className="grid sm:grid-cols-2 gap-3 bg-surface border border-border rounded-xl p-4 mb-8 text-sm">
            <div>
              <span className="block font-syne font-semibold text-xs text-ink-3 uppercase tracking-wide mb-0.5">{ui.source}</span>
              <span className="font-syne font-semibold text-ink">{article.source_name}</span>
            </div>
            {article.source_doi && (
              <div>
                <span className="block font-syne font-semibold text-xs text-ink-3 uppercase tracking-wide mb-0.5">{ui.doi}</span>
                <a
                  href={`https://doi.org/${article.source_doi}`}
                  target="_blank" rel="noopener noreferrer"
                  className="font-mono text-xs text-red hover:underline break-all"
                >
                  {article.source_doi}
                </a>
              </div>
            )}
            {article.original_published_at && (
              <div>
                <span className="block font-syne font-semibold text-xs text-ink-3 uppercase tracking-wide mb-0.5">{ui.pub_date}</span>
                <span className="text-ink">{fmtDate(article.original_published_at, lang)}</span>
              </div>
            )}
            {isTeacher && article.author_display_name && (
              <div>
                <span className="block font-syne font-semibold text-xs text-ink-3 uppercase tracking-wide mb-0.5">Contributed by</span>
                <span className="text-ink">{article.author_display_name}</span>
              </div>
            )}
          </div>

          {/* Body */}
          <div className="space-y-5 mb-10">
            {article.summary.split(/\n\n+/).map((para, i) => (
              <p key={i} className="text-sm sm:text-base leading-relaxed text-ink">{para}</p>
            ))}
          </div>

          {/* Disclaimer */}
          <div className="bg-amber-50 border border-amber-200 rounded-xl p-4 mb-6">
            <p className="text-xs text-amber-800 font-syne leading-relaxed">
              <span className="font-bold">{ui.disclaimer_label}: </span>{ui.disclaimer}
            </p>
          </div>

          {/* Report inaccuracy */}
          <div className="flex justify-end mb-4">
            <ReportArticleButton contentType="news" contentId={article.id} locale={locale} />
          </div>

          {/* CTA */}
          <a
            href={article.source_url}
            target="_blank" rel="noopener noreferrer"
            className="inline-flex items-center gap-2 font-syne font-bold text-sm bg-ink text-[#f0ede8] px-6 py-3 rounded-xl hover:bg-red transition-colors"
          >
            {ui.read_original}
          </a>
        </article>

        {/* Related MedMind articles */}
        {related.length > 0 && (
          <section className="mt-14 border-t border-border pt-10">
            <h2 className="font-syne font-extrabold text-xl text-ink mb-6">{ui.related_articles}</h2>
            <div className="grid sm:grid-cols-2 gap-4">
              {related.map(r => (
                <Link
                  key={r.slug}
                  href={`/articles/${r.slug}`}
                  className="group bg-surface border border-border rounded-xl p-5 hover:border-ink hover:shadow-sm transition-all"
                >
                  <span className="text-xs font-syne font-bold text-red uppercase tracking-wide block mb-2">
                    {getCategoryLabel(r.category, lang)}
                  </span>
                  <h3 className="font-syne font-bold text-sm text-ink group-hover:text-red transition-colors leading-snug mb-2 line-clamp-2">
                    {r.title}
                  </h3>
                  <p className="text-xs text-ink-2 leading-relaxed line-clamp-3">{r.excerpt}</p>
                  <span className="mt-3 inline-flex items-center gap-1 text-xs font-syne font-semibold text-red">
                    {ui.read_article}
                    <svg className="w-3 h-3 group-hover:translate-x-0.5 transition-transform" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5"><path d="M5 12h14M12 5l7 7-7 7"/></svg>
                  </span>
                </Link>
              ))}
            </div>
          </section>
        )}

        {/* More news in category */}
        {moreNews.length > 0 && (
          <section className="mt-14 border-t border-border pt-10">
            <div className="flex items-center justify-between mb-6">
              <h2 className="font-syne font-extrabold text-xl text-ink">{ui.more_in_category}</h2>
              <Link
                href={`/news?category=${article.category}`}
                className="text-xs font-syne font-semibold text-red hover:underline"
              >
                {ui.all_news}
              </Link>
            </div>
            <div className="grid sm:grid-cols-2 gap-4">
              {moreNews.map(n => (
                <Link
                  key={n.slug}
                  href={`/news/${n.slug}`}
                  className="group bg-surface border border-border rounded-xl p-5 hover:border-red/40 hover:shadow-sm transition-all flex flex-col"
                >
                  <div className="flex items-center justify-between gap-2 mb-3">
                    <span className={`text-xs font-syne font-bold px-2 py-0.5 rounded-full flex-shrink-0 ${SOURCE_BADGE[n.source_name] ?? "bg-amber-100 text-amber-800"}`}>
                      {n.source_name}
                    </span>
                    <span className="text-xs text-ink-3 font-syne">
                      {fmtDateShort(n.original_published_at || n.fetched_at, lang)}
                    </span>
                  </div>
                  <h3 className="font-syne font-bold text-sm text-ink group-hover:text-red transition-colors leading-snug mb-2 line-clamp-3 flex-1">
                    {n.title}
                  </h3>
                  <p className="text-xs text-ink-2 leading-relaxed line-clamp-2 mb-3">{n.summary_excerpt}</p>
                  <span className="inline-flex items-center gap-1 text-xs font-syne font-semibold text-red mt-auto">
                    {ui.read_more}
                    <svg className="w-3 h-3 group-hover:translate-x-0.5 transition-transform" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5"><path d="M5 12h14M12 5l7 7-7 7"/></svg>
                  </span>
                </Link>
              ))}
            </div>
            <div className="mt-6 text-center">
              <Link
                href="/news"
                className="inline-flex items-center gap-2 font-syne font-semibold text-sm border border-border text-ink-2 hover:text-ink hover:border-ink px-5 py-2.5 rounded-xl transition-all"
              >
                {ui.all_medical_news}
              </Link>
            </div>
          </section>
        )}

        <CommentsBlock contentType="news" slug={slug} />

        {/* Footer links */}
        <div className="mt-14 pt-8 border-t border-border flex flex-wrap justify-center gap-4 text-xs text-ink-3 font-syne">
          <Link href="/news" className="hover:text-ink transition-colors">News</Link>
          <span>·</span>
          <Link href="/articles" className="hover:text-ink transition-colors">Articles</Link>
          <span>·</span>
          <Link href="/calculators" className="hover:text-ink transition-colors">Calculators</Link>
        </div>
      </main>
    </div>
  );
}
