"use client";

import { useState, useEffect } from "react";
import Link from "next/link";
import { useI18n } from "@/lib/i18n";
import { useParams, useSearchParams } from "next/navigation";
import { getCategoryLabel } from "@/lib/categories";

type Lang = "en" | "ru" | "ar" | "es" | "de" | "fr" | "tr";

interface NewsDetail {
  id: string; slug: string; source_name: string; source_url: string;
  source_doi: string | null; title: string; summary: string;
  category: string; tags: string[] | null;
  original_published_at: string | null; fetched_at: string;
  author_display_name: string | null;
}

interface RelatedArticle { slug: string; title: string; excerpt: string; category: string; }

const LANGS: { value: Lang; flag: string }[] = [
  { value: "en", flag: "🇬🇧" }, { value: "ru", flag: "🇷🇺" }, { value: "de", flag: "🇩🇪" },
  { value: "fr", flag: "🇫🇷" }, { value: "ar", flag: "🇸🇦" }, { value: "tr", flag: "🇹🇷" },
  { value: "es", flag: "🇪🇸" },
];

const SOURCE_BADGE: Record<string, string> = {
  "WHO":     "bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-300",
  "medRxiv": "bg-purple-100 text-purple-800 dark:bg-purple-900/30 dark:text-purple-300",
};

const UI: Record<Lang, Record<string, string>> = {
  en: { back: "← All News", source: "Source", doi: "DOI", pub_date: "Originally published",
        fetched: "Added to MedMind", disclaimer_label: "AI Summary",
        disclaimer: "This summary was generated by AI from publicly available content. Always consult the original publication and a qualified professional before clinical decision-making.",
        read_original: "Read original publication →", preprint: "Preprint — not peer-reviewed",
        related_articles: "Related articles on this topic", related_news: "More news",
        author: "Contributed by" },
  ru: { back: "← Все новости", source: "Источник", doi: "DOI", pub_date: "Первоначально опубликовано",
        fetched: "Добавлено в MedMind", disclaimer_label: "AI-реферат",
        disclaimer: "Этот реферат создан ИИ на основе публично доступных материалов. Всегда обращайтесь к оригинальной публикации и квалифицированному специалисту.",
        read_original: "Читать оригинал →", preprint: "Препринт — не рецензировался",
        related_articles: "Статьи по теме", related_news: "Больше новостей",
        author: "Добавил(а)" },
  ar: { back: "← جميع الأخبار", source: "المصدر", doi: "DOI", pub_date: "تاريخ النشر الأصلي",
        fetched: "أضيف إلى MedMind", disclaimer_label: "ملخص ذكاء اصطناعي",
        disclaimer: "هذا الملخص مُولَّد بالذكاء الاصطناعي من محتوى متاح للعموم. استشر دائماً المنشور الأصلي ومختصاً مؤهلاً.",
        read_original: "قراءة المنشور الأصلي →", preprint: "طبعة مسبقة — لم تُراجَع",
        related_articles: "مقالات ذات صلة", related_news: "المزيد من الأخبار",
        author: "بواسطة" },
  es: { back: "← Todas las noticias", source: "Fuente", doi: "DOI", pub_date: "Publicado originalmente",
        fetched: "Añadido a MedMind", disclaimer_label: "Resumen IA",
        disclaimer: "Este resumen fue generado por IA a partir de contenido públicamente disponible. Consulte siempre la publicación original y a un profesional.",
        read_original: "Leer publicación original →", preprint: "Preimpresión — no revisada por pares",
        related_articles: "Artículos relacionados", related_news: "Más noticias",
        author: "Añadido por" },
  de: { back: "← Alle Nachrichten", source: "Quelle", doi: "DOI", pub_date: "Ursprünglich veröffentlicht",
        fetched: "Zu MedMind hinzugefügt", disclaimer_label: "KI-Zusammenfassung",
        disclaimer: "Diese Zusammenfassung wurde von KI aus öffentlich verfügbaren Inhalten erstellt. Konsultieren Sie stets die Originalveröffentlichung und einen Fachmann.",
        read_original: "Originalpublikation lesen →", preprint: "Preprint — nicht begutachtet",
        related_articles: "Verwandte Artikel", related_news: "Weitere Nachrichten",
        author: "Beigetragen von" },
  fr: { back: "← Toutes les actualités", source: "Source", doi: "DOI", pub_date: "Publié originalement",
        fetched: "Ajouté à MedMind", disclaimer_label: "Résumé IA",
        disclaimer: "Ce résumé a été généré par IA à partir de contenu public. Consultez toujours la publication originale et un professionnel.",
        read_original: "Lire la publication originale →", preprint: "Préimpression — non évaluée",
        related_articles: "Articles connexes", related_news: "Plus d'actualités",
        author: "Contribué par" },
  tr: { back: "← Tüm Haberler", source: "Kaynak", doi: "DOI", pub_date: "Orijinal yayın tarihi",
        fetched: "MedMind'a eklendi", disclaimer_label: "YZ Özeti",
        disclaimer: "Bu özet, kamuya açık içeriklerden YZ tarafından oluşturulmuştur. Her zaman orijinal yayına ve uzman bir profesyonele danışın.",
        read_original: "Orijinal yayını oku →", preprint: "Ön baskı — hakemlik yapılmadı",
        related_articles: "İlgili makaleler", related_news: "Daha fazla haber",
        author: "Katkıda bulunan" },
};

function fmtDate(s: string | null, lang: Lang): string {
  if (!s) return "";
  try { return new Intl.DateTimeFormat(lang, { year: "numeric", month: "long", day: "numeric" }).format(new Date(s)); }
  catch { return s.split("T")[0]; }
}

const API = process.env.NEXT_PUBLIC_API_URL ?? "/api/v1";

export default function NewsDetailPage() {
  const params = useParams();
  const searchParams = useSearchParams();
  const slug = params?.slug as string;
  const { locale, setLocale } = useI18n();
  const langParam = searchParams?.get("locale") as Lang | null;
  const lang = (langParam && LANGS.some(l => l.value === langParam) ? langParam
    : LANGS.some(l => l.value === locale) ? locale as Lang : "en");
  const ui = UI[lang];

  const [article, setArticle]       = useState<NewsDetail | null>(null);
  const [related, setRelated]       = useState<RelatedArticle[]>([]);
  const [loading, setLoading]       = useState(true);
  const [notFound, setNotFound]     = useState(false);

  useEffect(() => {
    if (!slug) return;
    setLoading(true);
    Promise.all([
      fetch(`${API}/news/${slug}?locale=${lang}`),
      fetch(`${API}/news/${slug}/related-articles?locale=${lang}`),
    ]).then(async ([newsRes, relRes]) => {
      if (newsRes.status === 404) { setNotFound(true); return; }
      const [newsData, relData] = await Promise.all([newsRes.json(), relRes.ok ? relRes.json() : []]);
      setArticle(newsData);
      setRelated(Array.isArray(relData) ? relData : []);
    }).catch(() => setNotFound(true))
      .finally(() => setLoading(false));
  }, [slug, lang]);

  const isPreprint = article?.source_name === "medRxiv";
  const isTeacher  = article?.author_display_name != null && !["WHO", "PubMed", "medRxiv"].includes(article.source_name);

  if (loading) return (
    <div className="min-h-screen bg-bg flex items-center justify-center">
      <div className="w-8 h-8 border-2 border-ink border-t-transparent rounded-full animate-spin" />
    </div>
  );

  if (notFound || !article) return (
    <div className="min-h-screen bg-bg flex flex-col items-center justify-center gap-4">
      <div className="text-5xl">📰</div>
      <p className="font-syne text-ink-2">Article not found.</p>
      <Link href="/news" className="font-syne font-semibold text-sm text-red hover:underline">{ui.back}</Link>
    </div>
  );

  return (
    <div className="min-h-screen bg-bg" dir={lang === "ar" ? "rtl" : "ltr"}>
      {/* Nav */}
      <nav className="bg-surface border-b border-border sticky top-0 z-50">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 py-3 flex items-center justify-between gap-3">
          <Link href="/" className="font-syne font-extrabold text-xl tracking-tight text-ink flex-shrink-0">
            Med<span className="text-red">Mind</span>
          </Link>
          <div className="hidden md:flex items-center gap-1 text-sm font-syne font-semibold text-ink-2">
            <Link href="/articles" className="hover:text-ink px-3 py-2 transition-colors">Articles</Link>
            <Link href="/news" className="text-ink hover:text-red px-3 py-2 transition-colors">
              {lang === "ru" ? "Новости" : lang === "ar" ? "أخبار" : lang === "de" ? "Nachrichten" : lang === "fr" ? "Actualités" : lang === "es" ? "Noticias" : lang === "tr" ? "Haberler" : "News"}
            </Link>
            <Link href="/calculators" className="hover:text-ink px-3 py-2 transition-colors">
              {lang === "ru" ? "Калькуляторы" : lang === "ar" ? "آلات حاسبة" : lang === "de" ? "Rechner" : lang === "fr" ? "Calculateurs" : lang === "es" ? "Calculadoras" : lang === "tr" ? "Hesap makineleri" : "Calculators"}
            </Link>
          </div>
          <select value={lang} onChange={e => setLocale(e.target.value)}
            className="text-xs font-syne border border-border rounded px-1.5 py-1 bg-bg text-ink focus:outline-none">
            {LANGS.map(l => <option key={l.value} value={l.value}>{l.flag}</option>)}
          </select>
        </div>
      </nav>

      <main className="max-w-4xl mx-auto px-4 sm:px-6 py-10">
        <Link href="/news" className="inline-flex items-center gap-1.5 font-syne font-semibold text-sm text-ink-2 hover:text-ink transition-colors mb-8">
          {ui.back}
        </Link>

        <article>
          {/* Category + badges */}
          <div className="flex flex-wrap items-center gap-2 mb-4">
            <span className="text-xs font-syne font-bold text-red uppercase tracking-wider">
              {getCategoryLabel(article.category, lang)}
            </span>
            <span className={`text-xs font-syne font-bold px-2 py-0.5 rounded-full ${SOURCE_BADGE[article.source_name] ?? "bg-amber-100 text-amber-800"}`}>
              {article.source_name}
            </span>
            {isPreprint && (
              <span className="text-xs font-syne px-2 py-0.5 rounded-full bg-yellow-100 text-yellow-800 dark:bg-yellow-900/30 dark:text-yellow-300">
                ⚠ {ui.preprint}
              </span>
            )}
          </div>

          {/* Title */}
          <h1 className="font-syne font-extrabold text-2xl sm:text-3xl lg:text-4xl text-ink leading-tight mb-6">
            {article.title}
          </h1>

          {/* Meta strip */}
          <div className="grid sm:grid-cols-2 gap-3 bg-surface border border-border rounded-xl p-4 mb-8 text-sm">
            <div>
              <span className="block font-syne font-semibold text-xs text-ink-3 uppercase tracking-wide mb-0.5">{ui.source}</span>
              <span className="font-syne font-semibold text-ink">{article.source_name}</span>
            </div>
            {article.source_doi && (
              <div>
                <span className="block font-syne font-semibold text-xs text-ink-3 uppercase tracking-wide mb-0.5">{ui.doi}</span>
                <a href={`https://doi.org/${article.source_doi}`} target="_blank" rel="noopener noreferrer"
                  className="font-mono text-xs text-red hover:underline break-all">{article.source_doi}</a>
              </div>
            )}
            {article.original_published_at && (
              <div>
                <span className="block font-syne font-semibold text-xs text-ink-3 uppercase tracking-wide mb-0.5">{ui.pub_date}</span>
                <span className="text-ink">{fmtDate(article.original_published_at, lang)}</span>
              </div>
            )}
            {isTeacher && article.author_display_name && (
              <div>
                <span className="block font-syne font-semibold text-xs text-ink-3 uppercase tracking-wide mb-0.5">{ui.author}</span>
                <span className="text-ink">{article.author_display_name}</span>
              </div>
            )}
          </div>

          {/* Body */}
          <div className="space-y-5 mb-10">
            {article.summary.split(/\n\n+/).map((para, i) => (
              <p key={i} className="text-sm sm:text-base leading-relaxed text-ink">{para}</p>
            ))}
          </div>

          {/* Disclaimer */}
          <div className="bg-amber-50 dark:bg-amber-900/10 border border-amber-200 dark:border-amber-800 rounded-xl p-4 mb-6">
            <p className="text-xs text-amber-800 dark:text-amber-300 font-syne leading-relaxed">
              <span className="font-bold">{ui.disclaimer_label}: </span>{ui.disclaimer}
            </p>
          </div>

          {/* CTA */}
          <a href={article.source_url} target="_blank" rel="noopener noreferrer"
            className="inline-flex items-center gap-2 font-syne font-bold text-sm bg-ink text-[#f0ede8] px-6 py-3 rounded-xl hover:bg-red transition-colors">
            {ui.read_original}
          </a>
        </article>

        {/* Related articles */}
        {related.length > 0 && (
          <section className="mt-16 border-t border-border pt-10">
            <h2 className="font-syne font-extrabold text-xl text-ink mb-6">{ui.related_articles}</h2>
            <div className="grid sm:grid-cols-2 gap-4">
              {related.map(r => (
                <Link key={r.slug} href={`/articles/${r.slug}`}
                  className="group bg-surface border border-border rounded-xl p-5 hover:border-ink hover:shadow-sm transition-all">
                  <span className="text-xs font-syne font-bold text-red uppercase tracking-wide block mb-2">
                    {getCategoryLabel(r.category, lang)}
                  </span>
                  <h3 className="font-syne font-bold text-sm text-ink group-hover:text-red transition-colors leading-snug mb-2 line-clamp-2">
                    {r.title}
                  </h3>
                  <p className="text-xs text-ink-2 leading-relaxed line-clamp-2">{r.excerpt}</p>
                </Link>
              ))}
            </div>
          </section>
        )}

        {/* Footer */}
        <div className="mt-14 pt-8 border-t border-border flex flex-wrap justify-center gap-4 text-xs text-ink-3 font-syne">
          <Link href="/news" className="hover:text-ink transition-colors">{lang === "ru" ? "Новости" : "News"}</Link>
          <span>·</span>
          <Link href="/articles" className="hover:text-ink transition-colors">Articles</Link>
          <span>·</span>
          <Link href="/calculators" className="hover:text-ink transition-colors">Calculators</Link>
          <span>·</span>
          <Link href="/symptoms" className="hover:text-ink transition-colors">Symptoms</Link>
        </div>
      </main>
    </div>
  );
}
