/**
 * Article category helpers shared between server and client components.
 * Keys map to articles.cat_* locale keys.
 */

/** @deprecated use CategoryIcon from lib/medical-icons instead */
export const CATEGORY_ICONS: Record<string, string> = {
  diseases: "", drugs: "", procedures: "", symptoms: "",
  diagnostics: "", emergency: "", nutrition: "", pediatrics: "",
  cardiology: "", neurology: "", oncology: "", surgery: "",
  psychiatry: "", endocrinology: "", "infectious-diseases": "",
  veterinary: "", pharmacology: "", "internal-medicine": "",
  "ob-gyn": "", orthopedics: "", rheumatology: "", hematology: "",
  nephrology: "", pulmonology: "", ophthalmology: "", ent: "",
  urology: "", geriatrics: "", dermatology: "",
};

/** Maps slug → locale key suffix (for t("articles.cat_<key>")) */
export const CATEGORY_KEY: Record<string, string> = {
  diseases: "cat_diseases",
  drugs: "cat_drugs",
  procedures: "cat_procedures",
  symptoms: "cat_symptoms",
  diagnostics: "cat_diagnostics",
  emergency: "cat_emergency",
  nutrition: "cat_nutrition",
  pediatrics: "cat_pediatrics",
  cardiology: "cat_cardiology",
  neurology: "cat_neurology",
  oncology: "cat_oncology",
  surgery: "cat_surgery",
  psychiatry: "cat_psychiatry",
  endocrinology: "cat_endocrinology",
  "infectious-diseases": "cat_infectious_diseases",
  veterinary: "cat_veterinary",
  pharmacology: "cat_pharmacology",
  "internal-medicine": "cat_internal_medicine",
  "ob-gyn": "cat_ob_gyn",
  orthopedics: "cat_orthopedics",
  rheumatology: "cat_rheumatology",
  hematology: "cat_hematology",
  nephrology: "cat_nephrology",
  pulmonology: "cat_pulmonology",
  ophthalmology: "cat_ophthalmology",
  ent: "cat_ent",
  urology: "cat_urology",
  geriatrics: "cat_geriatrics",
  dermatology: "cat_dermatology",
};

/** Static labels — all 7 languages. Source of truth for server + client components. */
const STATIC_LABELS: Record<string, Record<string, string>> = {
  en: {
    // original 29
    diseases: "Diseases & Conditions",
    drugs: "Drugs & Medications",
    procedures: "Procedures & Techniques",
    symptoms: "Symptoms & Signs",
    diagnostics: "Diagnostics & Lab Tests",
    emergency: "Emergency Medicine",
    nutrition: "Nutrition & Prevention",
    pediatrics: "Pediatrics",
    cardiology: "Cardiology",
    neurology: "Neurology",
    oncology: "Oncology",
    surgery: "Surgery",
    psychiatry: "Psychiatry",
    endocrinology: "Endocrinology",
    "infectious-diseases": "Infectious Diseases",
    veterinary: "Veterinary Medicine",
    pharmacology: "Pharmacology",
    "internal-medicine": "Internal Medicine",
    "ob-gyn": "Obstetrics & Gynecology",
    orthopedics: "Orthopedics",
    rheumatology: "Rheumatology",
    hematology: "Hematology",
    nephrology: "Nephrology",
    pulmonology: "Pulmonology",
    ophthalmology: "Ophthalmology",
    ent: "ENT (Ear, Nose & Throat)",
    urology: "Urology",
    geriatrics: "Geriatrics",
    dermatology: "Dermatology",
    // 35 new categories
    "drug-reference": "Drug Reference",
    "surgery-procedures": "Surgical Procedures",
    "allergy-immunology": "Allergy & Immunology",
    "diagnostics-interpretation": "Diagnostics Interpretation",
    "travel-medicine": "Travel Medicine",
    "sports-medicine": "Sports Medicine",
    genetics: "Genetics",
    "mental-health": "Mental Health",
    "infectious-specific": "Infectious Diseases (Specific)",
    "clinical-syndromes": "Clinical Syndromes",
    "public-health": "Public Health",
    rehabilitation: "Rehabilitation",
    "pediatrics-specific": "Pediatrics (Specific)",
    radiology: "Radiology",
    toxicology: "Toxicology",
    "palliative-care": "Palliative Care",
    "cardiology-advanced": "Advanced Cardiology",
    "womens-health": "Women's Health",
    "pain-management": "Pain Management",
    "preventive-medicine": "Preventive Medicine",
    "addiction-medicine": "Addiction Medicine",
    pathology: "Pathology",
    "neurology-advanced": "Advanced Neurology",
    "occupational-medicine": "Occupational Medicine",
    "sleep-medicine": "Sleep Medicine",
    immunology: "Immunology",
    biochemistry: "Biochemistry",
    anesthesiology: "Anesthesiology",
    physiology: "Physiology",
    microbiology: "Microbiology",
    "critical-care": "Critical Care",
    "sexual-health": "Sexual Health",
    "mens-health": "Men's Health",
    "lab-medicine": "Laboratory Medicine",
    "clinical-nutrition": "Clinical Nutrition",
    // News category aliases
    "infectious-disease": "Infectious Diseases",
    gastroenterology: "Gastroenterology",
    obstetrics: "Obstetrics",
    "general-medicine": "General Medicine",
  },

  ru: {
    diseases: "Болезни и состояния",
    drugs: "Лекарства и препараты",
    procedures: "Процедуры и техники",
    symptoms: "Симптомы и признаки",
    diagnostics: "Диагностика и анализы",
    emergency: "Скорая помощь",
    nutrition: "Питание и профилактика",
    pediatrics: "Педиатрия",
    cardiology: "Кардиология",
    neurology: "Неврология",
    oncology: "Онкология",
    surgery: "Хирургия",
    psychiatry: "Психиатрия",
    endocrinology: "Эндокринология",
    "infectious-diseases": "Инфекционные болезни",
    veterinary: "Ветеринарная медицина",
    pharmacology: "Фармакология",
    "internal-medicine": "Терапия",
    "ob-gyn": "Акушерство и гинекология",
    orthopedics: "Ортопедия",
    rheumatology: "Ревматология",
    hematology: "Гематология",
    nephrology: "Нефрология",
    pulmonology: "Пульмонология",
    ophthalmology: "Офтальмология",
    ent: "ЛОР-болезни",
    urology: "Урология",
    geriatrics: "Гериатрия",
    dermatology: "Дерматология",
    "drug-reference": "Справочник препаратов",
    "surgery-procedures": "Хирургические процедуры",
    "allergy-immunology": "Аллергология и иммунология",
    "diagnostics-interpretation": "Интерпретация анализов",
    "travel-medicine": "Медицина путешествий",
    "sports-medicine": "Спортивная медицина",
    genetics: "Генетика",
    "mental-health": "Психическое здоровье",
    "infectious-specific": "Инфекционные болезни (специфические)",
    "clinical-syndromes": "Клинические синдромы",
    "public-health": "Общественное здоровье",
    rehabilitation: "Реабилитация",
    "pediatrics-specific": "Педиатрия (специфическая)",
    radiology: "Радиология",
    toxicology: "Токсикология",
    "palliative-care": "Паллиативная помощь",
    "cardiology-advanced": "Кардиология (углублённая)",
    "womens-health": "Женское здоровье",
    "pain-management": "Управление болью",
    "preventive-medicine": "Профилактическая медицина",
    "addiction-medicine": "Наркология",
    pathology: "Патология",
    "neurology-advanced": "Неврология (углублённая)",
    "occupational-medicine": "Профессиональная медицина",
    "sleep-medicine": "Медицина сна",
    immunology: "Иммунология",
    biochemistry: "Биохимия",
    anesthesiology: "Анестезиология",
    physiology: "Физиология",
    microbiology: "Микробиология",
    "critical-care": "Интенсивная терапия",
    "sexual-health": "Сексуальное здоровье",
    "mens-health": "Мужское здоровье",
    "lab-medicine": "Лабораторная медицина",
    "clinical-nutrition": "Клиническое питание",
    "infectious-disease": "Инфекционные болезни",
    gastroenterology: "Гастроэнтерология",
    obstetrics: "Акушерство",
    "general-medicine": "Общая медицина",
  },

  de: {
    diseases: "Krankheiten & Zustände",
    drugs: "Medikamente & Arzneimittel",
    procedures: "Verfahren & Techniken",
    symptoms: "Symptome & Zeichen",
    diagnostics: "Diagnostik & Laborwerte",
    emergency: "Notfallmedizin",
    nutrition: "Ernährung & Prävention",
    pediatrics: "Pädiatrie",
    cardiology: "Kardiologie",
    neurology: "Neurologie",
    oncology: "Onkologie",
    surgery: "Chirurgie",
    psychiatry: "Psychiatrie",
    endocrinology: "Endokrinologie",
    "infectious-diseases": "Infektionskrankheiten",
    veterinary: "Veterinärmedizin",
    pharmacology: "Pharmakologie",
    "internal-medicine": "Innere Medizin",
    "ob-gyn": "Gynäkologie & Geburtshilfe",
    orthopedics: "Orthopädie",
    rheumatology: "Rheumatologie",
    hematology: "Hämatologie",
    nephrology: "Nephrologie",
    pulmonology: "Pneumologie",
    ophthalmology: "Augenheilkunde",
    ent: "HNO-Heilkunde",
    urology: "Urologie",
    geriatrics: "Geriatrie",
    dermatology: "Dermatologie",
    "drug-reference": "Arzneimittelreferenz",
    "surgery-procedures": "Chirurgische Eingriffe",
    "allergy-immunology": "Allergologie & Immunologie",
    "diagnostics-interpretation": "Befundinterpretation",
    "travel-medicine": "Reisemedizin",
    "sports-medicine": "Sportmedizin",
    genetics: "Genetik",
    "mental-health": "Psychische Gesundheit",
    "infectious-specific": "Infektionskrankheiten (spezifisch)",
    "clinical-syndromes": "Klinische Syndrome",
    "public-health": "Öffentliche Gesundheit",
    rehabilitation: "Rehabilitation",
    "pediatrics-specific": "Pädiatrie (spezifisch)",
    radiology: "Radiologie",
    toxicology: "Toxikologie",
    "palliative-care": "Palliativmedizin",
    "cardiology-advanced": "Erweiterte Kardiologie",
    "womens-health": "Frauengesundheit",
    "pain-management": "Schmerztherapie",
    "preventive-medicine": "Präventivmedizin",
    "addiction-medicine": "Suchtmedizin",
    pathology: "Pathologie",
    "neurology-advanced": "Erweiterte Neurologie",
    "occupational-medicine": "Arbeitsmedizin",
    "sleep-medicine": "Schlafmedizin",
    immunology: "Immunologie",
    biochemistry: "Biochemie",
    anesthesiology: "Anästhesiologie",
    physiology: "Physiologie",
    microbiology: "Mikrobiologie",
    "critical-care": "Intensivmedizin",
    "sexual-health": "Sexuelle Gesundheit",
    "mens-health": "Männergesundheit",
    "lab-medicine": "Labormedizin",
    "clinical-nutrition": "Klinische Ernährung",
    "infectious-disease": "Infektionskrankheiten",
    gastroenterology: "Gastroenterologie",
    obstetrics: "Geburtshilfe",
    "general-medicine": "Allgemeinmedizin",
  },

  fr: {
    diseases: "Maladies & Conditions",
    drugs: "Médicaments & Traitements",
    procedures: "Procédures & Techniques",
    symptoms: "Symptômes & Signes",
    diagnostics: "Diagnostics & Analyses",
    emergency: "Médecine d'urgence",
    nutrition: "Nutrition & Prévention",
    pediatrics: "Pédiatrie",
    cardiology: "Cardiologie",
    neurology: "Neurologie",
    oncology: "Oncologie",
    surgery: "Chirurgie",
    psychiatry: "Psychiatrie",
    endocrinology: "Endocrinologie",
    "infectious-diseases": "Maladies infectieuses",
    veterinary: "Médecine vétérinaire",
    pharmacology: "Pharmacologie",
    "internal-medicine": "Médecine interne",
    "ob-gyn": "Gynécologie-Obstétrique",
    orthopedics: "Orthopédie",
    rheumatology: "Rhumatologie",
    hematology: "Hématologie",
    nephrology: "Néphrologie",
    pulmonology: "Pneumologie",
    ophthalmology: "Ophtalmologie",
    ent: "ORL",
    urology: "Urologie",
    geriatrics: "Gériatrie",
    dermatology: "Dermatologie",
    "drug-reference": "Référence médicamenteuse",
    "surgery-procedures": "Actes chirurgicaux",
    "allergy-immunology": "Allergologie & Immunologie",
    "diagnostics-interpretation": "Interprétation des examens",
    "travel-medicine": "Médecine du voyage",
    "sports-medicine": "Médecine du sport",
    genetics: "Génétique",
    "mental-health": "Santé mentale",
    "infectious-specific": "Maladies infectieuses (spécifiques)",
    "clinical-syndromes": "Syndromes cliniques",
    "public-health": "Santé publique",
    rehabilitation: "Rééducation",
    "pediatrics-specific": "Pédiatrie (spécifique)",
    radiology: "Radiologie",
    toxicology: "Toxicologie",
    "palliative-care": "Soins palliatifs",
    "cardiology-advanced": "Cardiologie avancée",
    "womens-health": "Santé féminine",
    "pain-management": "Gestion de la douleur",
    "preventive-medicine": "Médecine préventive",
    "addiction-medicine": "Addictologie",
    pathology: "Pathologie",
    "neurology-advanced": "Neurologie avancée",
    "occupational-medicine": "Médecine du travail",
    "sleep-medicine": "Médecine du sommeil",
    immunology: "Immunologie",
    biochemistry: "Biochimie",
    anesthesiology: "Anesthésiologie",
    physiology: "Physiologie",
    microbiology: "Microbiologie",
    "critical-care": "Réanimation",
    "sexual-health": "Santé sexuelle",
    "mens-health": "Santé masculine",
    "lab-medicine": "Biologie médicale",
    "clinical-nutrition": "Nutrition clinique",
    "infectious-disease": "Maladies infectieuses",
    gastroenterology: "Gastroentérologie",
    obstetrics: "Obstétrique",
    "general-medicine": "Médecine générale",
  },

  es: {
    diseases: "Enfermedades y Condiciones",
    drugs: "Medicamentos y Fármacos",
    procedures: "Procedimientos y Técnicas",
    symptoms: "Síntomas y Signos",
    diagnostics: "Diagnósticos y Análisis",
    emergency: "Medicina de Urgencias",
    nutrition: "Nutrición y Prevención",
    pediatrics: "Pediatría",
    cardiology: "Cardiología",
    neurology: "Neurología",
    oncology: "Oncología",
    surgery: "Cirugía",
    psychiatry: "Psiquiatría",
    endocrinology: "Endocrinología",
    "infectious-diseases": "Enfermedades Infecciosas",
    veterinary: "Medicina Veterinaria",
    pharmacology: "Farmacología",
    "internal-medicine": "Medicina Interna",
    "ob-gyn": "Ginecología y Obstetricia",
    orthopedics: "Ortopedia",
    rheumatology: "Reumatología",
    hematology: "Hematología",
    nephrology: "Nefrología",
    pulmonology: "Neumología",
    ophthalmology: "Oftalmología",
    ent: "Otorrinolaringología",
    urology: "Urología",
    geriatrics: "Geriatría",
    dermatology: "Dermatología",
    "drug-reference": "Referencia de Medicamentos",
    "surgery-procedures": "Procedimientos Quirúrgicos",
    "allergy-immunology": "Alergología e Inmunología",
    "diagnostics-interpretation": "Interpretación Diagnóstica",
    "travel-medicine": "Medicina del Viajero",
    "sports-medicine": "Medicina Deportiva",
    genetics: "Genética",
    "mental-health": "Salud Mental",
    "infectious-specific": "Enfermedades Infecciosas (Específicas)",
    "clinical-syndromes": "Síndromes Clínicos",
    "public-health": "Salud Pública",
    rehabilitation: "Rehabilitación",
    "pediatrics-specific": "Pediatría (Específica)",
    radiology: "Radiología",
    toxicology: "Toxicología",
    "palliative-care": "Cuidados Paliativos",
    "cardiology-advanced": "Cardiología Avanzada",
    "womens-health": "Salud de la Mujer",
    "pain-management": "Manejo del Dolor",
    "preventive-medicine": "Medicina Preventiva",
    "addiction-medicine": "Medicina de Adicciones",
    pathology: "Patología",
    "neurology-advanced": "Neurología Avanzada",
    "occupational-medicine": "Medicina Ocupacional",
    "sleep-medicine": "Medicina del Sueño",
    immunology: "Inmunología",
    biochemistry: "Bioquímica",
    anesthesiology: "Anestesiología",
    physiology: "Fisiología",
    microbiology: "Microbiología",
    "critical-care": "Cuidados Intensivos",
    "sexual-health": "Salud Sexual",
    "mens-health": "Salud Masculina",
    "lab-medicine": "Medicina de Laboratorio",
    "clinical-nutrition": "Nutrición Clínica",
    "infectious-disease": "Enfermedades Infecciosas",
    gastroenterology: "Gastroenterología",
    obstetrics: "Obstetricia",
    "general-medicine": "Medicina General",
  },

  tr: {
    diseases: "Hastalıklar ve Durumlar",
    drugs: "İlaçlar ve Preparatlar",
    procedures: "Prosedürler ve Teknikler",
    symptoms: "Semptomlar ve Belirtiler",
    diagnostics: "Tanı ve Laboratuvar",
    emergency: "Acil Tıp",
    nutrition: "Beslenme ve Koruyucu Sağlık",
    pediatrics: "Pediatri",
    cardiology: "Kardiyoloji",
    neurology: "Nöroloji",
    oncology: "Onkoloji",
    surgery: "Cerrahi",
    psychiatry: "Psikiyatri",
    endocrinology: "Endokrinoloji",
    "infectious-diseases": "Enfeksiyon Hastalıkları",
    veterinary: "Veteriner Hekimlik",
    pharmacology: "Farmakoloji",
    "internal-medicine": "İç Hastalıkları",
    "ob-gyn": "Kadın Doğum",
    orthopedics: "Ortopedi",
    rheumatology: "Romatoloji",
    hematology: "Hematoloji",
    nephrology: "Nefroloji",
    pulmonology: "Göğüs Hastalıkları",
    ophthalmology: "Göz Hastalıkları",
    ent: "KBB",
    urology: "Üroloji",
    geriatrics: "Geriatri",
    dermatology: "Dermatoloji",
    "drug-reference": "İlaç Referansı",
    "surgery-procedures": "Cerrahi Prosedürler",
    "allergy-immunology": "Allerji ve İmmünoloji",
    "diagnostics-interpretation": "Tanı Yorumu",
    "travel-medicine": "Seyahat Tıbbı",
    "sports-medicine": "Spor Hekimliği",
    genetics: "Genetik",
    "mental-health": "Ruh Sağlığı",
    "infectious-specific": "Enfeksiyon Hastalıkları (Özgün)",
    "clinical-syndromes": "Klinik Sendromlar",
    "public-health": "Halk Sağlığı",
    rehabilitation: "Rehabilitasyon",
    "pediatrics-specific": "Pediatri (Özgün)",
    radiology: "Radyoloji",
    toxicology: "Toksikoloji",
    "palliative-care": "Palyatif Bakım",
    "cardiology-advanced": "İleri Kardiyoloji",
    "womens-health": "Kadın Sağlığı",
    "pain-management": "Ağrı Yönetimi",
    "preventive-medicine": "Koruyucu Hekimlik",
    "addiction-medicine": "Bağımlılık Tıbbı",
    pathology: "Patoloji",
    "neurology-advanced": "İleri Nöroloji",
    "occupational-medicine": "İş Hekimliği",
    "sleep-medicine": "Uyku Tıbbı",
    immunology: "İmmünoloji",
    biochemistry: "Biyokimya",
    anesthesiology: "Anesteziyoloji",
    physiology: "Fizyoloji",
    microbiology: "Mikrobiyoloji",
    "critical-care": "Yoğun Bakım",
    "sexual-health": "Cinsel Sağlık",
    "mens-health": "Erkek Sağlığı",
    "lab-medicine": "Laboratuvar Tıbbı",
    "clinical-nutrition": "Klinik Beslenme",
    "infectious-disease": "Enfeksiyon Hastalıkları",
    gastroenterology: "Gastroenteroloji",
    obstetrics: "Obstetri",
    "general-medicine": "Genel Tıp",
  },

  ar: {
    diseases: "الأمراض والحالات",
    drugs: "الأدوية والعقاقير",
    procedures: "الإجراءات والتقنيات",
    symptoms: "الأعراض والعلامات",
    diagnostics: "التشخيص والمختبر",
    emergency: "طب الطوارئ",
    nutrition: "التغذية والوقاية",
    pediatrics: "طب الأطفال",
    cardiology: "أمراض القلب",
    neurology: "الأعصاب",
    oncology: "الأورام",
    surgery: "الجراحة",
    psychiatry: "الطب النفسي",
    endocrinology: "الغدد الصماء",
    "infectious-diseases": "الأمراض المعدية",
    veterinary: "الطب البيطري",
    pharmacology: "علم الأدوية",
    "internal-medicine": "الطب الداخلي",
    "ob-gyn": "النساء والتوليد",
    orthopedics: "جراحة العظام",
    rheumatology: "أمراض الروماتيزم",
    hematology: "أمراض الدم",
    nephrology: "أمراض الكلى",
    pulmonology: "أمراض الصدر",
    ophthalmology: "طب العيون",
    ent: "أمراض الأنف والأذن والحنجرة",
    urology: "المسالك البولية",
    geriatrics: "طب الشيخوخة",
    dermatology: "الأمراض الجلدية",
    "drug-reference": "مرجع الأدوية",
    "surgery-procedures": "الإجراءات الجراحية",
    "allergy-immunology": "الحساسية والمناعة",
    "diagnostics-interpretation": "تفسير نتائج التشخيص",
    "travel-medicine": "طب السفر",
    "sports-medicine": "طب الرياضة",
    genetics: "الوراثة",
    "mental-health": "الصحة النفسية",
    "infectious-specific": "الأمراض المعدية (محددة)",
    "clinical-syndromes": "المتلازمات السريرية",
    "public-health": "الصحة العامة",
    rehabilitation: "إعادة التأهيل",
    "pediatrics-specific": "طب الأطفال (محدد)",
    radiology: "الأشعة",
    toxicology: "السُّمِّيَّات",
    "palliative-care": "الرعاية التلطيفية",
    "cardiology-advanced": "أمراض القلب المتقدمة",
    "womens-health": "صحة المرأة",
    "pain-management": "إدارة الألم",
    "preventive-medicine": "الطب الوقائي",
    "addiction-medicine": "طب الإدمان",
    pathology: "علم الأمراض",
    "neurology-advanced": "الأعصاب المتقدمة",
    "occupational-medicine": "طب المهن",
    "sleep-medicine": "طب النوم",
    immunology: "علم المناعة",
    biochemistry: "الكيمياء الحيوية",
    anesthesiology: "التخدير",
    physiology: "علم وظائف الأعضاء",
    microbiology: "الأحياء الدقيقة",
    "critical-care": "العناية المركزة",
    "sexual-health": "الصحة الجنسية",
    "mens-health": "صحة الرجل",
    "lab-medicine": "الطب المختبري",
    "clinical-nutrition": "التغذية السريرية",
    "infectious-disease": "الأمراض المعدية",
    gastroenterology: "أمراض الجهاز الهضمي",
    obstetrics: "التوليد",
    "general-medicine": "الطب العام",
  },
};

/** Get category label for a given locale. Falls back to humanized slug if unknown. */
export function getCategoryLabel(category: string, locale: string): string {
  const labels = STATIC_LABELS[locale] ?? STATIC_LABELS.en;
  if (labels[category]) return labels[category];
  // Humanize unknown slug: "sleep-medicine" → "Sleep Medicine"
  return category
    .split("-")
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

const MORE_IN: Record<string, string> = {
  en: "More in", ru: "Ещё в разделе", de: "Mehr in",
  fr: "Plus dans", es: "Más en", tr: "Daha fazlası", ar: "المزيد في",
};

export function getMoreIn(locale: string): string {
  return MORE_IN[locale] ?? MORE_IN.en;
}

/** Short category descriptions for SEO (English only). */
export const CATEGORY_DESCRIPTIONS: Record<string, string> = {
  // original
  diseases: "Evidence-based articles on medical conditions, pathophysiology, diagnosis, and treatment.",
  drugs: "Drug monographs: mechanisms of action, dosing, contraindications, and interactions.",
  procedures: "Step-by-step guides to clinical procedures and techniques.",
  symptoms: "Clinical approach to common and rare symptoms — differential diagnosis and workup.",
  diagnostics: "Laboratory tests, imaging, and diagnostic criteria for clinical practice.",
  emergency: "Rapid-reference articles on acute medical emergencies and critical care.",
  nutrition: "Evidence-based nutritional guidelines and preventive medicine recommendations.",
  pediatrics: "Medical content tailored to pediatric patients — growth, development, and disease.",
  cardiology: "Heart diseases, arrhythmias, heart failure, and cardiovascular pharmacology.",
  neurology: "Neurological disorders, stroke, epilepsy, neurodegenerative diseases.",
  oncology: "Cancer biology, diagnosis, staging, and treatment modalities.",
  surgery: "Surgical principles, operative techniques, and perioperative care.",
  psychiatry: "Mental health conditions, psychopharmacology, and psychiatric emergencies.",
  endocrinology: "Hormonal disorders, diabetes, thyroid, adrenal, and metabolic conditions.",
  "infectious-diseases": "Bacterial, viral, fungal, and parasitic infections — diagnosis and antimicrobial therapy.",
  veterinary: "Veterinary medicine: animal diseases, pharmacology, and clinical techniques.",
  pharmacology: "Drug mechanisms, clinical pharmacology, dosing, side effects, and drug interactions.",
  "internal-medicine": "Comprehensive internal medicine: systemic diseases, clinical reasoning, and management.",
  "ob-gyn": "Obstetrics and gynecology: pregnancy, childbirth, and women's reproductive health.",
  orthopedics: "Musculoskeletal medicine: fractures, joint disorders, and orthopedic surgery.",
  rheumatology: "Autoimmune and inflammatory diseases: arthritis, lupus, vasculitis.",
  hematology: "Blood disorders: anemia, coagulation, leukemia, lymphoma, and bone marrow conditions.",
  nephrology: "Kidney diseases: acute kidney injury, CKD, dialysis, and electrolyte disorders.",
  pulmonology: "Respiratory medicine: COPD, asthma, pneumonia, and lung diseases.",
  ophthalmology: "Eye diseases: glaucoma, cataracts, retinal disorders, and ocular emergencies.",
  ent: "Ear, nose and throat: otitis, sinusitis, hearing loss, and head & neck conditions.",
  urology: "Urinary tract and male reproductive medicine: stones, BPH, and urological cancers.",
  geriatrics: "Medicine for older adults: frailty, polypharmacy, dementia, and age-related conditions.",
  dermatology: "Skin diseases: dermatitis, psoriasis, skin cancer, and dermatological emergencies.",
  // new
  "drug-reference": "Comprehensive drug reference: dosing, indications, contraindications, and pharmacokinetics.",
  "surgery-procedures": "Surgical techniques, operative steps, and procedural guides for clinical practice.",
  "allergy-immunology": "Allergic diseases, hypersensitivity reactions, immunodeficiencies, and immunotherapy.",
  "diagnostics-interpretation": "How to read and interpret lab results, imaging findings, and diagnostic tests.",
  "travel-medicine": "Pre-travel vaccinations, tropical diseases, malaria prophylaxis, and travel health.",
  "sports-medicine": "Sports injuries, exercise physiology, rehabilitation, and athlete health.",
  genetics: "Genetic disorders, inheritance patterns, genetic testing, and molecular medicine.",
  "mental-health": "Mental health conditions, evidence-based therapies, and psychiatric pharmacology.",
  "infectious-specific": "Specific infectious diseases: pathogen profiles, epidemiology, and targeted treatment.",
  "clinical-syndromes": "Recognizing and managing clinical syndromes across specialties.",
  "public-health": "Epidemiology, disease prevention, health policy, and population medicine.",
  rehabilitation: "Physical and occupational rehabilitation after injury, surgery, or illness.",
  "pediatrics-specific": "Specific pediatric conditions: neonatal, developmental, and childhood diseases.",
  radiology: "Radiological imaging: X-ray, CT, MRI, ultrasound interpretation and findings.",
  toxicology: "Poisoning, overdose management, antidotes, and environmental toxins.",
  "palliative-care": "Symptom management, end-of-life care, and supportive oncology.",
  "cardiology-advanced": "Advanced cardiology: interventional procedures, electrophysiology, and heart failure management.",
  "womens-health": "Women's health beyond OB/GYN: hormones, bone health, and preventive care.",
  "pain-management": "Acute and chronic pain assessment, analgesic pharmacology, and multidisciplinary management.",
  "preventive-medicine": "Screening guidelines, vaccination schedules, lifestyle medicine, and risk reduction.",
  "addiction-medicine": "Substance use disorders, withdrawal management, pharmacotherapy, and harm reduction.",
  pathology: "Disease mechanisms, histopathology, autopsy findings, and laboratory pathology.",
  "neurology-advanced": "Advanced neurology: movement disorders, demyelinating diseases, and neuroimmunology.",
  "occupational-medicine": "Work-related diseases, occupational exposures, and workplace health.",
  "sleep-medicine": "Sleep disorders: insomnia, sleep apnea, narcolepsy, and circadian rhythm disorders.",
  immunology: "Immune system disorders, autoimmunity, transplant immunology, and biologics.",
  biochemistry: "Metabolic pathways, enzyme disorders, and clinical biochemistry for medical practice.",
  anesthesiology: "Anesthetic agents, airway management, perioperative care, and regional anesthesia.",
  physiology: "Human physiology: organ systems, homeostasis, and clinical correlations.",
  microbiology: "Medical microbiology: bacteria, viruses, fungi, and antimicrobial resistance.",
  "critical-care": "ICU management: mechanical ventilation, hemodynamic support, and organ failure.",
  "sexual-health": "Sexually transmitted infections, sexual dysfunction, and reproductive health.",
  "mens-health": "Male-specific conditions: prostate, testosterone, fertility, and cardiovascular risk.",
  "lab-medicine": "Laboratory medicine: reference ranges, test interpretation, and quality control.",
  "clinical-nutrition": "Nutritional assessment, parenteral nutrition, malnutrition, and therapeutic diets.",
};

/** Locale-aware descriptions for categories that have translations. Falls back to CATEGORY_DESCRIPTIONS (English). */
const CATEGORY_DESCRIPTIONS_I18N: Partial<Record<string, Record<string, string>>> = {
  veterinary: {
    en: "Veterinary medicine: animal diseases, pharmacology, and clinical techniques.",
    ru: "Ветеринарная медицина: болезни животных, фармакология и клинические методы.",
    de: "Veterinärmedizin: Tierkrankheiten, Pharmakologie und klinische Techniken.",
    fr: "Médecine vétérinaire : maladies animales, pharmacologie et techniques cliniques.",
    es: "Medicina veterinaria: enfermedades animales, farmacología y técnicas clínicas.",
    tr: "Veteriner hekimlik: hayvan hastalıkları, farmakoloji ve klinik teknikler.",
    ar: "الطب البيطري: أمراض الحيوانات والصيدلة والتقنيات السريرية.",
  },
  diseases: {
    en: "Evidence-based articles on medical conditions, pathophysiology, diagnosis, and treatment.",
    ru: "Доказательные статьи о заболеваниях, патофизиологии, диагностике и лечении.",
    de: "Evidenzbasierte Artikel zu Erkrankungen, Pathophysiologie, Diagnose und Therapie.",
    fr: "Articles fondés sur des preuves sur les maladies, la physiopathologie, le diagnostic et le traitement.",
    es: "Artículos basados en evidencia sobre enfermedades, fisiopatología, diagnóstico y tratamiento.",
    tr: "Hastalıklar, patofizyoloji, tanı ve tedavi hakkında kanıta dayalı makaleler.",
    ar: "مقالات مستندة إلى الأدلة حول الأمراض والفيزيولوجيا المرضية والتشخيص والعلاج.",
  },
  drugs: {
    en: "Drug monographs: mechanisms of action, dosing, contraindications, and interactions.",
    ru: "Монографии препаратов: механизм действия, дозировка, противопоказания и взаимодействия.",
    de: "Arzneimittelmonografien: Wirkmechanismen, Dosierung, Kontraindikationen und Wechselwirkungen.",
    fr: "Monographies de médicaments : mécanismes d'action, posologie, contre-indications et interactions.",
    es: "Monografías de fármacos: mecanismos de acción, dosificación, contraindicaciones e interacciones.",
    tr: "İlaç monografileri: etki mekanizmaları, dozaj, kontrendikasyonlar ve etkileşimler.",
    ar: "مونوجرافات الأدوية: آليات العمل والجرعات وموانع الاستخدام والتفاعلات.",
  },
};

export function getCategoryDescription(cat: string, locale: string): string {
  return CATEGORY_DESCRIPTIONS_I18N[cat]?.[locale]
    ?? CATEGORY_DESCRIPTIONS_I18N[cat]?.["en"]
    ?? CATEGORY_DESCRIPTIONS[cat]
    ?? "";
}
